Repository replicatedhq/embedded-cluster, pull requests merged in 2023-10, with the labels that each got.

#91 chore: fix end to end tests
  .github/workflows/e2e.yaml
  e2e/embed_test.go
  e2e/install_test.go
  e2e/scripts/addons-only.sh
  e2e/scripts/embed-and-install.sh
  e2e/scripts/install-with-disabled-addons.sh
Labels: type::chore

#93 chore: using apt-get instead of apt
  .github/workflows/e2e.yaml
  e2e/embed_test.go
  e2e/install_test.go
  e2e/scripts/addons-only.sh
  e2e/scripts/embed-and-install.sh
  e2e/scripts/install-with-disabled-addons.sh
Labels: type::chore

#94 chore: allow build on mac os environment
  Makefile
Labels: type::chore

#95 chore(tests): using staging metrics endpoint
  e2e/scripts/addons-only.sh
  e2e/scripts/embed-and-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/install-with-disabled-addons.sh
  e2e/scripts/interactive-multi-node-install.exp
  e2e/scripts/multi-node-install.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/wait-for-ready-nodes.sh
Labels: type::chore

#104 Free up some storage on pull requests to build
  .github/workflows/pull-request.yaml
Labels: type::chore

#103 chore: enable golangci-lint
  .github/workflows/pull-request.yaml
  .golangci.yml
Labels: type::chore

#108 feat: include installer version to the cluster configuration configmap
  pkg/addons/adminconsole/customize.go
Labels: type::feature

#107 chore: unify two ci jobs doing the same thing
  .github/workflows/pull-request.yaml
Labels: type::chore

#115 feat: allow for ssh-agent key management
  pkg/config/config.go
Labels: type::feature

#114 feat: apply embedded unsupported overrides
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/host.go
  pkg/config/testdata/override-change-name.yaml
  pkg/config/testdata/override-enable-telemetry.yaml
  pkg/config/testdata/override-setting-ip-forward.yaml
  pkg/config/testdata/override-zero-out-sans-list.yaml
  pkg/customization/customization.go
  pkg/metrics/reporter.go
  pkg/metrics/sender.go
Labels: type::feature

#116 feat: remove load balancer configuration
  e2e/scripts/interactive-multi-node-install.exp
  pkg/config/config.go
Labels: type::feature

#119 chore: remove builder source code
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Dockerfile
  Makefile
  README.md
  cmd/builder/main.go
  cmd/builder/request.go
Labels: type::chore

#120 feat: allow users to provide an embedded cluster config path
  cmd/helmvm/install.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: type::feature

#121 chore: remove unused code
  pkg/goods/goods.go
  pkg/goods/web/download.sh
Labels: type::chore

#122 chore: removed code to support disconnected environments
  .github/workflows/e2e.yaml
  Makefile
  README.md
  cmd/helmvm/bundle.go
  cmd/helmvm/embed.go
  cmd/helmvm/install.go
  cmd/helmvm/main.go
  e2e/bundle_test.go
  e2e/scripts/build-bundle.sh
  go.mod
  go.sum
  pkg/config/config.go
  pkg/goods/goods.go
  pkg/hembed/hembed.go
  pkg/metrics/reporter.go
Labels: type::chore

#123 Fix Helm Addon Upgrades
  Makefile
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/charts/charts.go
  pkg/addons/applier.go
  pkg/addons/custom/custom.go
  pkg/addons/openebs/charts/charts.go
  pkg/addons/openebs/openebs.go
  pkg/config/config.go
Labels: type::bug

#126 feat: hide --overrides flag
  cmd/helmvm/install.go
Labels: type::feature

#128 chore: getting rid of linting complains
  pkg/addons/custom/custom.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/hembed/hembed.go
  pkg/logging/logging.go
  pkg/preflights/output.go
  pkg/preflights/preflights.go
  pkg/progressbar/options.go
  pkg/prompts/prompts.go
  pkg/ssh/ssh.go
Labels: type::chore

#129 chore: cosmetic changes to makefile
  Makefile
Labels: type::chore

#127 feat: using short token instead of k0s token
  .github/workflows/e2e.yaml
  cmd/helmvm/join.go
  e2e/install_test.go
Labels: type::feature

#130 Remove the '.' from helmvm folder name
  README.md
  e2e/scripts/addons-only.sh
  e2e/scripts/embed-and-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/install-with-disabled-addons.sh
  e2e/scripts/multi-node-install.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/wait-for-ready-nodes.sh
  pkg/defaults/provider.go
Labels: type::feature

#132 chore: allow for embedding development license
  .gitignore
  Makefile
Labels: type::chore

#136 bug: disable konnectivity-server on join
  cmd/helmvm/join.go
Labels: bug

#134 feat: deploy the helmvm operator crds helm chart
  Makefile
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature

#135 feat: wait for admin console
  .github/workflows/e2e.yaml
  cmd/helmvm/install.go
  e2e/install_test.go
  e2e/scripts/addons-only.sh
  e2e/scripts/embed-and-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/install-with-disabled-addons.sh
  e2e/scripts/interactive-multi-node-install.exp
  e2e/scripts/multi-node-install.sh
  e2e/scripts/single-node-install.sh
  pkg/addons/adminconsole/adminconsole.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
Labels: type::feature

#138 bug: cleanup progress bar output
  pkg/addons/adminconsole/adminconsole.go
Labels: bug, type::bug

#142 feat: create installation cr before ending the install
  cmd/helmvm/install.go
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/kubeutils/kubeutils.go
  pkg/metrics/sender.go
Labels: type::feature

#144 bug: reuse admin-console password when reusing config
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/config/config.go
  pkg/customization/customization.go
Labels: type::bug

#163 bug: fix wrong url protocol for kotsadm access
  pkg/addons/adminconsole/adminconsole.go
Labels: type::chore

#162 chore: remove the not working 'node token create' command
  cmd/embedded-cluster/node.go
  cmd/embedded-cluster/token.go
Labels: type::chore

#164 chore: fix 'timed out waiting for admin console: <nil>'
  pkg/addons/adminconsole/adminconsole.go
Labels: type::chore
