Repository replicatedhq/embedded-cluster, pull requests merged in 2023-11, with the labels that each got.

#161 chore: change metrics endpoint path
  pkg/metrics/sender.go
  pkg/metrics/sender_test.go
Labels: type::chore

#166 chore: bump embedded cluster operator version
  Makefile
Labels: type::chore

#172 chore: use a license during e2e tests
  .gitignore
  Makefile
  e2e/README.md
  e2e/embed_test.go
  e2e/kots-release/kots-app.yaml
  e2e/kots-release/license.yaml
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/interactive-multi-node-install.exp
  pkg/kubeutils/kubeutils.go
Labels: type::chore

#174 chore: bump embedded cluster operator version
  Makefile
  go.mod
  go.sum
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::chore

#176 bug: bring systemd unit file installation back
  cmd/embedded-cluster/install.go
  e2e/install_test.go
  e2e/scripts/embed-and-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/install-with-disabled-addons.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/zz-scripts.go
Labels: type::bug

#173 chore: create workflow to update makefile dependencies
  .github/workflows/dependencies.yaml
Labels: type::chore

#175 chore: removed unused e2e test script
  e2e/scripts/addons-only.sh
Labels: type::chore

#182 chore: bump makefile dependencies
  Makefile
Labels: type::chore

#186 update to embedded-cluster-operator v0.4.1
  Makefile
  e2e/kots-release/config.yaml
  go.mod
  go.sum
  pkg/config/config.go
Labels: type::feature
