Repository replicatedhq/embedded-cluster, pull requests merged in 2024-08, with the labels that each got.

#907 bug: return failure if unable to push lam image
  chainguard.mk
Labels: type::bug, bug::regression

#909 Fix automated PRs author filtering
  .github/workflows/automated-prs-manager.yaml
Labels: type::chore

#905 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: automated-pr, images, type::security

#910 Update host preflight wording
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#911 Use original pause image but proxy it
  cmd/buildtools/k0s.go
  deploy/images/pause/apko.tmpl.yaml
  pkg/config/images.go
  pkg/config/images_test.go
Labels: type::feature

#912 Use upstream pause image
  cmd/buildtools/k0s.go
  pkg/config/images.go
  pkg/config/static/metadata.yaml
Labels: type::feature

#913 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#916 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#914 chore: fix host-support-bundle.yaml permissions
  pkg/goods/materializer.go
Labels: type::chore

#917 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#920 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#921 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#922 feat: update registry version
  pkg/addons/registry/static/metadata.yaml
Labels: type::chore, automated-pr

#925 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#924 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#923 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#926 feat: update adminconsole version
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#930 feat: update velero version
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#929 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#928 feat: update embeddedclusteroperator version
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::chore, automated-pr

#927 feat: update registry version
  pkg/addons/registry/static/values-ha.yaml
  pkg/addons/registry/static/values.yaml
Labels: type::chore, automated-pr

#932 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#931 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#936 Use latest upstream instead of k0s images
  .github/workflows/ci.yaml
  chainguard.mk
  cmd/buildtools/addon.go
  cmd/buildtools/adminconsole.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/utils.go
  cmd/buildtools/utils_test.go
  cmd/buildtools/velero.go
  deploy/images/calico-cni/apko.tmpl.yaml
  deploy/images/calico-kube-controllers/apko.tmpl.yaml
  deploy/images/calico-node/apko.tmpl.yaml
  deploy/images/coredns/apko.tmpl.yaml
  deploy/images/envoy-distroless/apko.tmpl.yaml
  deploy/images/kube-proxy/apko.tmpl.yaml
  deploy/images/kubectl/apko.tmpl.yaml
  deploy/images/metrics-server/apko.tmpl.yaml
  deploy/images/openebs-provisioner-localpv/apko.tmpl.yaml
  deploy/images/seaweedfs/apko.tmpl.yaml
  deploy/images/velero-plugin-for-aws/apko.tmpl.yaml
  deploy/images/velero-restore-helper/apko.tmpl.yaml
  deploy/images/velero/apko.tmpl.yaml
  e2e/version_test.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.tpl.yaml
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
  pkg/addons/openebs/openebs.go
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.tpl.yaml
  pkg/addons/openebs/static/values.yaml
  pkg/addons/registry/registry.go
  pkg/addons/registry/static/metadata.yaml
  pkg/addons/registry/static/values-ha.tpl.yaml
  pkg/addons/registry/static/values-ha.yaml
  pkg/addons/registry/static/values.tpl.yaml
  pkg/addons/registry/static/values.yaml
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.tpl.yaml
  pkg/addons/seaweedfs/static/values.yaml
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.tpl.yaml
  pkg/addons/velero/static/values.yaml
  pkg/addons/velero/velero.go
  pkg/config/images.go
  pkg/config/images_test.go
  pkg/config/static/metadata.yaml
  pkg/helpers/addon.go
  pkg/release/addon.go
  pkg/release/k0s.go
Labels: type::feature

#937 Fix OpenEBS path in preflight
  pkg/preflights/host-preflight.yaml
Labels: type::bug, bug::normal

#938 feat: update registry version
  pkg/addons/registry/static/metadata.yaml
  pkg/addons/registry/static/values.yaml
Labels: type::chore, automated-pr

#940 feat: update registry version
  pkg/addons/registry/static/values-ha.yaml
Labels: type::chore, automated-pr

#941 Build one-off registry 2.8.3 image with apko
  cmd/buildtools/registry.go
  pkg/addons/registry/static/metadata.yaml
  pkg/addons/registry/static/values-ha.yaml
  pkg/addons/registry/static/values.yaml
Labels: type::feature

#943 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#944 feat: update embeddedclusteroperator version
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::chore, automated-pr

#945 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#949 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#950 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#951 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#952 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#955 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#956 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#957 List 100 GH releases per page
  cmd/buildtools/utils.go
Labels: type::chore

#958 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#959 Update to v1.29.7+k0s.0
  Makefile
Labels: type::chore

#960 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#962 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#966 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#963 fix(reset): handle crd installation not installed error
  pkg/kubeutils/kubeutils.go
Labels: type::bug, bug::normal

#964 fix(reset): do not drain node if only one in the cluster
  cmd/embedded-cluster/uninstall.go
Labels: type::bug, bug::normal

#967 test upgrading to test EC from 1.8.0-1.28
  .github/workflows/ci.yaml
  e2e/install_test.go
  e2e/restore_test.go
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/common.sh
  e2e/scripts/vandoor-prepare.sh
Labels: type::chore

#970 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#969 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#973 feat: update registry version
  pkg/addons/registry/static/metadata.yaml
  pkg/addons/registry/static/values-ha.yaml
  pkg/addons/registry/static/values.yaml
Labels: type::chore, automated-pr

#974 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#975 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#978 feat: update embeddedclusteroperator version
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::chore, automated-pr

#977 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#976 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#979 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#980 feat: update openebs version
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#983 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: automated-pr, images, type::security

#984 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#981 fix: pass service node port range to installation for join
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/list_images.go
  cmd/embedded-cluster/metadata.go
  cmd/embedded-cluster/restore.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/options.go
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/velero.go
  pkg/config/config.go
  pkg/helpers/parse.go
Labels: type::bug, bug::normal

#985 fix(reset): fix panic
  cmd/embedded-cluster/uninstall.go
Labels: type::bug, bug::regression

#986 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#995 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#994 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#997 Bug: Don't check absolute paths for mount binaries
  pkg/preflights/host-preflight.yaml
Labels: type::bug, bug::normal

#1004 resolv.conf preflight
  pkg/preflights/host-preflight.yaml
Labels: type::chore

#1007 fix(e2e): fail on airgap build failure rather than continuing with test
  e2e/airgap.go
  e2e/install_test.go
  e2e/restore_test.go
  e2e/utils.go
Labels: type::chore

#1008 feat: update embeddedclusteroperator version
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::chore, automated-pr

#1009 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#1010 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1011 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#1006 fix(e2e): collect cluster support bundle if ec install fails
  e2e/scripts/collect-support-bundle-cluster.sh
Labels: type::chore

#1018 feat(troubleshoot): add filesystem latency check
  Makefile
  cmd/embedded-cluster/install.go
  e2e/materialize_test.go
  fio/Dockerfile
  pkg/defaults/defaults.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/preflights.go
  pkg/preflights/preflights_test.go
Labels: type::feature

#1021 Fix validating non-AWS S3-compatible stores
  cmd/embedded-cluster/restore.go
Labels: type::bug, bug::normal

#1020 update tests for node join command UI
  e2e/playwright/tests/get-join-controller-command/test.spec.ts
  e2e/playwright/tests/get-join-worker-command/test.spec.ts
  e2e/playwright/tests/shared/deploy-app.ts
Labels: type::feature

#1025 fix: make reset work with bind mounts
  cmd/embedded-cluster/reset.go
  pkg/helpers/fs.go
  pkg/helpers/fs_test.go
Labels: type::bug, bug::normal

#1024 Revert "feat(troubleshoot): add filesystem latency check"
  Makefile
  cmd/embedded-cluster/install.go
  e2e/materialize_test.go
  fio/Dockerfile
  pkg/defaults/defaults.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/preflights.go
  pkg/preflights/preflights_test.go
Labels: type::bug, bug::normal

#1028 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1022 chore(e2e): missing checks and cleanup
  .github/workflows/ci.yaml
  Makefile
  e2e/install_test.go
  e2e/proxy_test.go
  e2e/reset_test.go
  e2e/restore_test.go
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/check-pre-minio-removal-installation-state.sh
  e2e/scripts/common.sh
  e2e/scripts/install-playwright.sh
  e2e/scripts/pre-minio-removal-install.sh
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/single-node-proxy-install.sh
  e2e/utils.go
  scripts/cache-files.sh
Labels: type::chore

#1032 fix(ci): cluster bundle is broken in airgap mode
  e2e/scripts/collect-support-bundle-cluster.sh
Labels: type::chore

#1033 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1035 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1041 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: automated-pr, images, type::security

#1042 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#1036 chore(e2e): more test inconsistencies
  e2e/install_test.go
Labels: type::chore

#1045 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#1047 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: automated-pr, images, type::security

#1049 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type::chore

#1043 Set default value for pod/service CIDRs with flag
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/network.go
  cmd/embedded-cluster/proxy.go
  cmd/embedded-cluster/restore.go
Labels: type::feature

#1012 Make preflight messages more specific and actionable
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1052 fix(ci): operator release fails with "no rule to make target 'build-chart'"
  .github/workflows/release-prod.yaml
Labels: type::chore

#1053 fix(ci): operator release fails with "build/chart: No such file or directory
  common.mk
  operator/Makefile
Labels: type::chore

#1054 fix(ci): operator release fails with "buildtools: No such file or directory"
  .github/workflows/release-prod.yaml
Labels: type::chore

#1055 fix(ci): operator release fails with "buildtools: No such file or directory"
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  scripts/cache-files.sh
Labels: type::chore

#1057 feat: update embeddedclusteroperator version
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::chore, automated-pr

#1058 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1030 Revert "Revert "feat(troubleshoot): add filesystem latency check""
  .github/workflows/ci.yaml
  Makefile
  cmd/embedded-cluster/install.go
  e2e/docker/docker.go
  e2e/docker/id.go
  e2e/materialize_test.go
  e2e/preflights_test.go
  fio/Dockerfile
  go.mod
  go.sum
  pkg/defaults/defaults.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/preflights.go
  pkg/preflights/preflights_test.go
Labels: type::feature

#1056 fix(ci): operator release fails with "chart not found"
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  operator/Makefile
  scripts/cache-files.sh
  scripts/create-previous-k0s-release.sh
  scripts/create-upgrade-release.sh
Labels: type::chore

#1059 fix(ci): operator release fails with "unbound variables"
  .github/workflows/release-prod.yaml
Labels: type::chore

#1060 fix(ci): opreator binary should not be prefixed with v
  .github/workflows/release-prod.yaml
  e2e/scripts/vandoor-prepare.sh
Labels: type::chore

#1067 fix(operator): use this repo for operator
  docs/resources.md
  go.mod
  go.sum
  operator/PROJECT
  operator/controllers/installation_controller.go
  operator/controllers/installation_controller_test.go
  operator/controllers/k0s.go
  operator/main.go
  operator/pkg/artifacts/upgrade.go
  operator/pkg/artifacts/upgrade_test.go
  operator/pkg/charts/charts.go
  operator/pkg/charts/charts_test.go
  operator/pkg/cli/migrate.go
  operator/pkg/cli/root.go
  operator/pkg/cli/upgrade.go
  operator/pkg/metadata/airgap.go
  operator/pkg/migrations/registry.go
  operator/pkg/openebs/openebs_test.go
  operator/pkg/registry/migrate.go
  operator/pkg/registry/registry.go
  operator/pkg/registry/seaweedfs.go
  operator/pkg/upgrade/upgrade.go
  operator/schemagen/main.go
  pkg/config/config.go
  pkg/highavailability/seaweed.go
Labels: type::chore

#1068 fix(e2e): wait for internet to succeed multiple times
  e2e/cluster/cluster.go
Labels: type::chore

#1069 chore(ci): speed up build with static make cache
  Makefile
  local-artifact-mirror/Makefile
Labels: type::chore

#1081 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1085 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#1086 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1083 chore: update embeddedclusteroperator images
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: automated-pr, images, type::security
