Repository replicatedhq/embedded-cluster, pull requests merged in 2024-02, with the labels that each got.

#312 regenerate items under pkg/goods/bins when Makefile updates
  Makefile
Labels: type::chore

#310 fix kotsadm chart apply error
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  e2e/install_test.go
  e2e/kots-release-onmerge/config.yaml
  e2e/kots-release-onpr/config.yaml
  e2e/reset_test.go
  e2e/scripts/check-installation-state.sh
  e2e/scripts/single-node-install.sh
  e2e/unsupported-overrides_test.go
  e2e/version_test.go
  pkg/addons/adminconsole/adminconsole.go
Labels: type::bug, bug::normal

#299 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#313 feat: check sshd config before starting the install
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  cmd/embedded-cluster/install.go
  e2e/install_test.go
  e2e/scripts/single-node-install-without-root.sh
Labels: type::feature

#315 update embedded-cluster-operator from v0.22.0 to v0.22.1
  Makefile
Labels: type::chore

#316 get the logs of the embedded-cluster-operator upon failure
  e2e/scripts/check-installation-state.sh
Labels: type::chore

#325 fix puppeteer tests
  e2e/scripts/check-app-and-cluster-status.js
  e2e/scripts/install-puppeteer.sh
Labels: type::chore

#324 feat: show the app version in appslug version output
  cmd/embedded-cluster/version.go
  e2e/kots-release-onmerge/release.yaml
  e2e/kots-release-onpr/release.yaml
  e2e/version_test.go
Labels: type::feature

#332 update embedded-cluster-operator to 0.22.2
  Makefile
  e2e/install_test.go
Labels: type::chore

#334 update embedded-cluster-operator to 0.22.3
  Makefile
Labels: type::chore

#318 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#317 Adds `kubectl` completion to shell command
  README.md
  cmd/embedded-cluster/shell.go
Labels: type::feature

#333 feat: disable openebs-device storage class
  e2e/scripts/single-node-install.sh
  pkg/addons/openebs/openebs.go
Labels: type::feature

#336 ensure that the makefile only redownloads bins in goods when required
  Makefile
Labels: type::chore

#337 fix bash completion on ubuntu by sourcing /etc/bash_completion
  cmd/embedded-cluster/shell.go
Labels: type::chore

#339 feat: protect embeddedClusterID
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature

#346 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#345 add e2e tests that upgrade the embedded-cluster-operator chart
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  e2e/install_test.go
  e2e/kots-release-install/cluster-config.yaml
  e2e/kots-release-install/deployment-2.yaml
  e2e/kots-release-install/deployment.yaml
  e2e/kots-release-install/k8s-app.yaml
  e2e/kots-release-install/kots-app.yaml
  e2e/kots-release-install/kots-lint-config.yaml
  e2e/kots-release-onmerge/license.yaml
  e2e/kots-release-onmerge/release.yaml
  e2e/kots-release-onpr/license.yaml
  e2e/kots-release-onpr/release.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/kots-release-upgrade/deployment-2.yaml
  e2e/kots-release-upgrade/deployment.yaml
  e2e/kots-release-upgrade/k8s-app.yaml
  e2e/kots-release-upgrade/kots-app.yaml
  e2e/kots-release-upgrade/kots-lint-config.yaml
  e2e/license.yaml
  e2e/scripts/check-postupgrade-state.sh
  scripts/cache-files.sh
  scripts/create-upgrade-release.sh
Labels: type::feature

#348 fix on-merge tests
  .github/workflows/release-dev.yaml
Labels: type::chore

#351 fix on-merge tests, mk2
  .github/workflows/release-dev.yaml
Labels: type::chore

#352 update embedded-cluster-operator chart values as an upgrade in CI
  e2e/scripts/check-postupgrade-state.sh
  scripts/create-upgrade-release.sh
Labels: type::feature

#354 feat: fix join command output
  .gitignore
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  pkg/preflights/preflights.go
  pkg/progressbar/progressbar.go
  pkg/progressbar/progressbar_test.go
Labels: type::feature

#355 feat: add proxy infra support on e2e tests
  e2e/cluster/cluster.go
  e2e/proxy_test.go
Labels: type::feature

#356 feat: polishing cli arguments and help messages
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/main.go
  cmd/embedded-cluster/reset.go
  cmd/embedded-cluster/shell.go
  cmd/embedded-cluster/version.go
Labels: type::feature

#357 feat: remove node start, stop, list commands
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/node.go
  cmd/embedded-cluster/reset.go
Labels: type::feature

#358 feat: remove --disable-addon flag
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  cmd/embedded-cluster/install.go
  e2e/install_test.go
  e2e/scripts/install-with-disabled-addons.sh
  pkg/addons/applier.go
  pkg/addons/options.go
Labels: type::feature

#349 New embedded cluster binary format and accept license as a flag
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/version.go
  e2e/cluster/cluster.go
  e2e/embedded-cluster-release-builder/main.go
  e2e/install_test.go
  e2e/reset_test.go
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/single-node-install-without-root.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/unsupported-overrides.sh
  e2e/unsupported-overrides_test.go
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/options.go
  pkg/config/config.go
  pkg/embed/elf.go
  pkg/embed/elf_test.go
  pkg/embed/helpers.go
  pkg/helpers/parse.go
  pkg/kubeutils/client.go
  pkg/metrics/reporter.go
  pkg/metrics/sender.go
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/release/testdata/release.tar.gz
Labels: type::feature

#359 embedded cluster v0.22.6
  Makefile
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-postupgrade-state.sh
Labels: type::chore

#361 fix 'failed to find preflight specs' error
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
Labels: type::chore

#362 Add license to applier when running outro
  cmd/embedded-cluster/install.go
Labels: type::feature

#363 test installation without anything embedded in the binary
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
  e2e/scripts/default-install.sh
Labels: type::chore

#364 fix prod release builds
  .github/workflows/release-prod.yaml
Labels: type::chore

#366 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#367 remove k0s restart in CI
  e2e/kots-release-install/cluster-config.yaml
  e2e/scripts/single-node-install.sh
Labels: type::chore

#369 feat: improve user feedback upon reinstall
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  go.mod
  go.sum
  pkg/logging/logging.go
Labels: type::feature

#370 feat: only enable auto completion when /etc/autocompletion exists
  cmd/embedded-cluster/shell.go
Labels: type::feature

#374 Set embedded cluster version Helm value for the adminconsole addon
  pkg/addons/adminconsole/adminconsole.go
Labels: type::feature

#373 download the build from staging.replicated.app and install upon merge
  .github/workflows/release-dev.yaml
  e2e/install_test.go
  e2e/scripts/vandoor-prepare.sh
Labels: type::chore

#376 feat: remove cluster ID file
  pkg/metrics/reporter.go
Labels: type::feature

#379 feat: observe context while waiting for kots deployment
  pkg/addons/adminconsole/adminconsole.go
Labels: type::feature

#380 feat: bump embedded cluster operator
  Makefile
Labels: type::feature

#377 feat: use k0s kubeconfig
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/shell.go
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-nodes-removed.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/default-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/unsupported-overrides.sh
  e2e/scripts/wait-for-ready-nodes.sh
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
Labels: type::feature

#378 feat: no longer ship kubectl, instead alias k0s, use /var/lib/embedded-cluster
  .github/workflows/dependencies.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-nodes-removed.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/default-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/unsupported-overrides.sh
  e2e/scripts/wait-for-ready-nodes.sh
  e2e/sudo_test.go
  e2e/version_test.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/defaults/provider_test.go
  pkg/logging/logging.go
Labels: type::feature

#382 return to using the kubectl binary, not k0s
  .github/workflows/dependencies.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
Labels: type::chore

#383 feat: update kotsadm to 1.107.4
  Makefile
Labels: type::feature

#384 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#386 feat: only print "running preflights" if preflights exist
  cmd/embedded-cluster/install.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/spinner/options.go
  pkg/spinner/spinner.go
  pkg/spinner/spinner_test.go
Labels: type::feature

#387 add a hidden command that prints the embedded data
  cmd/embedded-cluster/version.go
  e2e/version_test.go
Labels: type::chore

#381 feat: change shell command to spawn in the current directory
  cmd/embedded-cluster/shell.go
Labels: type::feature

#394 bug: still use default logger with regular user
  pkg/logging/logging.go
Labels: type::bug, bug::normal

#393 fix missing admin console branding
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-postupgrade-state.sh
  pkg/addons/adminconsole/adminconsole.go
Labels: type::bug, bug::normal

#395 better log failures to upgrade the nginx helm chart and why
  e2e/scripts/check-postupgrade-state.sh
Labels: type::chore

#398 add reset and reinstall test
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
  e2e/scripts/reset-installation.sh
Labels: type::chore

#396 feat: update default chart order values
  Makefile
  e2e/kots-release-install/cluster-config.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/scripts/check-postupgrade-state.sh
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/config/config.go
Labels: type::feature

#399 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#400 feat: improve 'missing license'/'mismatched license' error messages
  cmd/embedded-cluster/install.go
Labels: type::feature

#401 feat: only wait 60s draining a node during reset
  cmd/embedded-cluster/reset.go
Labels: type::feature

#405 feat: materialize host support bundle
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  e2e/scripts/collect-support-bundle.sh
  e2e/scripts/install-puppeteer.sh
  e2e/scripts/puppeteer.sh
  e2e/support-bundle_test.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/goods/goods.go
  pkg/goods/support/host-support-bundle.yaml
Labels: type::feature

#407 feat: show a spinner when OpenEBS is installing, before the Operator spinner
  e2e/scripts/single-node-install.sh
  pkg/addons/openebs/openebs.go
Labels: type::feature

#406 feat: move join and reset commands to top level
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/main.go
  cmd/embedded-cluster/node.go
  cmd/embedded-cluster/uninstall.go
  e2e/reset_test.go
  e2e/scripts/reset-installation.sh
  e2e/sudo_test.go
Labels: type::feature

#409 feat: v1.29.2+k0s.0
  Makefile
Labels: type::feature

#410 feat: ensure we always process add-ons the same order
  pkg/addons/applier.go
Labels: type::feature

#411 feat: allow additional controller nodes to run workloads
  cmd/embedded-cluster/join.go
  e2e/kots-release-install/cluster-config.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/wait-for-ready-nodes.sh
  e2e/version_test.go
Labels: type::feature

#413 feat: check if support bundle contains expected files
  e2e/scripts/collect-support-bundle.sh
Labels: type::feature

#417 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#418 remove redundant reset flag
  cmd/embedded-cluster/uninstall.go
Labels: type::feature

#422 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#423 run the full integration test suite for dependabot PRs
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
Labels: type::chore
