Repository replicatedhq/embedded-cluster, pull requests merged in 2024-01, with the labels that each got.

#239 feat: bump kots, kubectl, openebs, embedded-cluster-operator and troubleshoot
  Makefile
Labels: type::feature

#213 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#240 feat: save end user configuration in the crd
  Makefile
  cmd/embedded-cluster/install.go
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/options.go
Labels: type::feature

#241 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#242 cache k0s and metadata files in S3 bucket
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  .github/workflows/release-prod.yaml
  scripts/cache-files.sh
Labels: type::feature

#243 feat: apply config overrides during node join
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/join_test.go
  cmd/embedded-cluster/testdata/join-command-response/empty-overrides.yaml
  cmd/embedded-cluster/testdata/join-command-response/multiple-port-overrides.yaml
  cmd/embedded-cluster/testdata/join-command-response/multiple-unused-overlays.yaml
  cmd/embedded-cluster/testdata/join-command-response/no-overrides.yaml
  cmd/embedded-cluster/testdata/join-command-response/override-ports.yaml
  cmd/embedded-cluster/testdata/join-command-response/storage-and-port-overrides.yaml
  cmd/embedded-cluster/testdata/patch-k0s-config/change-external-address.yaml
  cmd/embedded-cluster/testdata/patch-k0s-config/change-sans.yaml
  cmd/embedded-cluster/testdata/patch-k0s-config/extra-args.yaml
  cmd/embedded-cluster/testdata/patch-k0s-config/k0s-storage.yaml
  cmd/embedded-cluster/testdata/patch-k0s-config/no-embedded-cluster-config.yaml
  cmd/embedded-cluster/testdata/patch-k0s-config/no-overrides.yaml
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/k0s-config/overide-helm-charts.yaml
  pkg/config/testdata/k0s-config/override-change-name.yaml
  pkg/config/testdata/k0s-config/override-enable-telemetry.yaml
  pkg/config/testdata/k0s-config/overrides-helm-chart-version.yaml
  pkg/config/testdata/unsupported-overrides/override-change-name.yaml
  pkg/config/testdata/unsupported-overrides/override-enable-telemetry.yaml
  pkg/config/testdata/unsupported-overrides/override-helm-charts.yaml
  pkg/config/testdata/unsupported-overrides/override-setting-ip-forward.yaml
  pkg/config/testdata/unsupported-overrides/override-zero-out-sans-list.yaml
  pkg/customization/helpers.go
  pkg/metrics/reporter.go
  pkg/metrics/sender.go
Labels: type::feature

#250 do not run the cache action for dependabot PRs
  .github/workflows/pull-request.yaml
Labels: type::chore

#251 update embedded-cluster-operator chart version
  Makefile
Labels: type::feature

#252 fix an error in the github release process
  .github/workflows/release-prod.yaml
Labels: type::chore

#254 feat: fixes unsupported overrides for extensions
  cmd/embedded-cluster/install.go
  e2e/scripts/unsupported-overrides.sh
  pkg/config/config.go
Labels: type::feature

#257 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#259 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#260 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#262 feat: provide clusterID to kotsadm
  pkg/addons/adminconsole/adminconsole.go
  pkg/metrics/reporter.go
Labels: type::feature

#263 feat: install kotsadm in default namespace, not embedded-cluster
  e2e/scripts/unsupported-overrides.sh
  pkg/addons/applier.go
Labels: type::feature

#264 feat: bump ec operator
  Makefile
Labels: type::feature

#270 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#271 feat: save release files to output directory
  .gitignore
  Makefile
Labels: type::feature

#272 feat: bump operator version
  Makefile
  release.tar.gz
Labels: type::feature

#274 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#261 chore: enable kurl-proxy in the admin console helm chart
  .gitignore
  Makefile
  README.md
  pkg/addons/adminconsole/adminconsole.go
Labels: type::feature

#275 feat: checking cluster and app state during ci
  e2e/install_test.go
  e2e/scripts/check-app-and-cluster-status.js
  e2e/scripts/install-puppeteer.sh
  e2e/scripts/puppeteer.sh
Labels: type::feature

#277 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#278 feat: remove the embed command
  .github/workflows/e2e.yaml
  README.md
  cmd/embedded-cluster/embed.go
  cmd/embedded-cluster/main.go
  e2e/embed_test.go
  e2e/scripts/embed-and-install.sh
  e2e/scripts/install-with-disabled-addons.sh
  pkg/addons/applier.go
  pkg/addons/custom/custom.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/hembed/hembed.go
Labels: type::feature

#276 feat: reset command
  cmd/embedded-cluster/node.go
  cmd/embedded-cluster/reset.go
  go.mod
Labels: type::feature

#279 feat: create library for embedding kots release
  .gitignore
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join_test.go
  e2e/embedded-cluster-release-builder/main.go
  go.mod
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/config/config.go
  pkg/embed/customization.go
  pkg/embed/elf.go
  pkg/embed/elf_test.go
  pkg/embed/helpers.go
  pkg/embed/testdata/release.tar.gz
  pkg/metrics/reporter.go
  pkg/metrics/sender.go
Labels: type::feature

#284 allow untrusted https certificates when joining nodes to the cluster
  cmd/embedded-cluster/join.go
Labels: bug, type::bug, bug::normal

#286 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#287 allow a vendor to specify additional helm charts
  cmd/embedded-cluster/version.go
  e2e/install_test.go
  e2e/kots-release/config.yaml
  e2e/scripts/single-node-install.sh
  e2e/version_test.go
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/config/config.go
Labels: type::feature

#282 feat: retry if unable to access the internet
  e2e/cluster/cluster.go
Labels: type::feature

#285 feat: e2e tests for multi node clusters
  .github/workflows/e2e.yaml
  e2e/install_test.go
  e2e/scripts/check-app-and-cluster-status.js
  e2e/scripts/generate-controller-join-token.js
  e2e/scripts/generate-worker-join-token.js
Labels: type::feature

#294 feat: create methods to better deal with embedded data
  cmd/embedded-cluster/join_test.go
  pkg/embed/customization.go
  pkg/embed/elf.go
  pkg/embed/elf_test.go
  pkg/embed/helpers.go
  pkg/embed/release.go
  pkg/embed/release_test.go
Labels: type::feature

#295 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#296 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#281 feat: improve node rests
  .github/workflows/e2e.yaml
  cmd/embedded-cluster/reset.go
  e2e/reset_test.go
  e2e/scripts/check-nodes-removed.sh
  go.mod
  go.sum
Labels: type::feature

#297 feat: publish releases to the s3 bucket
  scripts/cache-files.sh
Labels: type::feature

#298 Revert "Update Makefile versions"
  Makefile
Labels: type::chore

#300 feat: protect binary name
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature

#301 feat: check etcd health before controller reset
  cmd/embedded-cluster/reset.go
  go.mod
  go.sum
Labels: type::feature

#302 update embedded-cluster-operator to v0.21.0
  Makefile
  go.mod
  go.sum
Labels: type::chore

#304 feat: reset should be run as root + k0s path
  cmd/embedded-cluster/reset.go
Labels: type::feature

#305 feat: return error if kube client is not initialised
  cmd/embedded-cluster/reset.go
Labels: type::feature

#303 set the version to 'dev-metadata' in integration tests
  .github/actions/e2e/action.yml
  .github/workflows/e2e.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  e2e/README.md
  e2e/install_test.go
  e2e/kots-release-onmerge/config.yaml
  e2e/kots-release-onmerge/kots-app.yaml
  e2e/kots-release-onmerge/license.yaml
  e2e/kots-release-onpr/config.yaml
  e2e/kots-release-onpr/kots-app.yaml
  e2e/kots-release-onpr/license.yaml
  e2e/kots-release/license.yaml
  e2e/scripts/check-installation-state.sh
  e2e/scripts/single-node-install.sh
Labels: type::chore

#306 feat: require uid 0 for install, shell and node commands
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  .gitignore
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/node.go
  cmd/embedded-cluster/reset.go
  cmd/embedded-cluster/shell.go
  e2e/cluster/cluster.go
  e2e/sudo_test.go
  e2e/utils.go
Labels: type::feature
