Repository replicatedhq/embedded-cluster, pull requests merged in 2024-04, with the labels that each got.

#470 use a pvc, not emptydir, for registry storage
  e2e/scripts/single-node-airgap-install.sh
  pkg/addons/registry/registry.go
Labels: type::feature

#473 test with different application and embedded-cluster versions to ensure we're not confusing the two
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/vandoor-prepare.sh
  pkg/addons/adminconsole/adminconsole.go
Labels: type::chore

#478 log kots install cmd before close on failure
  pkg/addons/adminconsole/adminconsole.go
Labels: type::bug, bug::regression

#480 do not print debug log to screen on install failure
  pkg/addons/adminconsole/adminconsole.go
Labels: type::chore

#482 update embedded-cluster-operator to v0.26.1
  Makefile
Labels: type::feature

#472 replace puppeteer with testim
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/README.md
  e2e/install_test.go
  e2e/reset_test.go
  e2e/scripts/deploy-kots-application.js
  e2e/scripts/generate-controller-join-token.js
  e2e/scripts/generate-worker-join-token.js
  e2e/scripts/install-puppeteer.sh
  e2e/scripts/install-testim.sh
  e2e/scripts/puppeteer.sh
  e2e/scripts/testim.sh
  e2e/utils.go
Labels: type::chore

#483 fix on-merge testim branch
  .github/workflows/release-dev.yaml
Labels: type::chore

#485 move the embedded-cluster binary to /var/lib/embedded-cluster/bin after materialize
  Makefile
  cmd/local-artifact-mirror/pull.go
  go.mod
  go.sum
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature

#487 allow compiling embedded-cluster with overridden operator image
  Makefile
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::chore

#488 print the download link for a PR's build
  .github/workflows/pull-request.yaml
Labels: type::chore

#466 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#489 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#490 improve testing nginx version after chart upgrade
  e2e/scripts/check-postupgrade-state.sh
Labels: type::chore

#496 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#497 rename the embedded-cluster binary before running 'materialize'
  cmd/local-artifact-mirror/pull.go
Labels: bug, type::bug, bug::normal

#499 fix version label and add airgap command
  .github/workflows/pull-request.yaml
Labels: type::chore

#500 chore: preserve charts and images file mode
  pkg/airgap/materialize.go
Labels: type::chore

#501 feat: remove /var/openebs during reset
  cmd/embedded-cluster/uninstall.go
Labels: type::feature

#502 rename k0s image file from 'install.tar' to 'images-amd64.tar'
  pkg/airgap/materialize.go
Labels: type::feature

#503 Update Makefile versions
  Makefile
  go.mod
  go.sum
Labels: type::chore, automated-pr, makefile

#504 run 'go mod tidy'
  go.mod
  go.sum
Labels: type::chore

#506 feat: add 'new line' capability to spinner
  pkg/spinner/options.go
  pkg/spinner/spinner.go
  pkg/spinner/spinner_test.go
Labels: type::feature

#508 bug: show success in the previous step instead of current
  pkg/spinner/spinner.go
  pkg/spinner/spinner_test.go
Labels: type::bug, bug::normal

#511 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#498 feat: improve finalizing step feedback
  Makefile
  pkg/addons/adminconsole/adminconsole.go
  pkg/helpers/command.go
  pkg/spinner/spinner.go
  pkg/spinner/spinner_test.go
Labels: type::feature

#512 chore: rephrase admin console password prompt
  pkg/addons/adminconsole/adminconsole.go
Labels: type::chore

#513 chore: small adjustments or reset's user feedback
  cmd/embedded-cluster/uninstall.go
Labels: type::chore

#520 ensure that app images (and env vars) change on update
  e2e/kots-release-install/deployment-2.yaml
  e2e/kots-release-install/deployment.yaml
  e2e/kots-release-upgrade/deployment-2.yaml
  e2e/kots-release-upgrade/deployment.yaml
Labels: type::chore

#515 chore: stop using linuxcontainers.org
  .github/actions/e2e/action.yml
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/uninstall.go
  e2e/cluster/cluster.go
  go.mod
  go.sum
  pkg/goods/goods.go
  pkg/goods/support/host-support-bundle.yaml
  pkg/goods/systemd/calico-network-manager.conf
  pkg/helpers/systemd.go
Labels: type::chore

#524 chore: temporarily enable linuxcontainers.org for testing
  e2e/cluster/cluster.go
Labels: type::chore

#521 cleanup additional files during reset
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/uninstall.go
  e2e/install_test.go
Labels: type::chore

#519 Update Makefile versions
  Makefile
  go.mod
  go.sum
Labels: type::chore, automated-pr, makefile

#525 add a password config item to the CI app
  e2e/kots-release-install/config.yaml
  e2e/kots-release-install/deployment.yaml
  e2e/kots-release-upgrade/config.yaml
  e2e/kots-release-upgrade/deployment.yaml
  e2e/scripts/single-node-install.sh
Labels: type::chore

#527 run 'make go.mod' when updating k0s to include a tidy
  .github/workflows/dependencies.yaml
  go.mod
  go.sum
Labels: type::chore

#526 Support airgap updates from the CLI
  cmd/embedded-cluster/main.go
  cmd/embedded-cluster/update.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/kotscli/kotscli.go
Labels: type::feature

#536 chore: collect k0scontroller systemd logs
  pkg/goods/support/host-support-bundle.yaml
Labels: type::chore

#539 chore: use k0s full path when collecting bundle
  pkg/goods/support/host-support-bundle.yaml
Labels: type::chore

#540 chore: remove /usr/local/bin/k0s on reset
  cmd/embedded-cluster/uninstall.go
Labels: type::chore

#542 remove the MS apt repo that is no longer signed
  .github/actions/e2e/action.yml
Labels: type::chore

#530 Feat: Add velero to EC
  .github/actions/e2e/action.yml
  .github/workflows/dependencies.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  cmd/embedded-cluster/version.go
  e2e/install_test.go
  e2e/kots-release-install/deployment.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/kots-release-upgrade/deployment.yaml
  e2e/scripts/check-velero-state.sh
  e2e/version_test.go
  pkg/addons/applier.go
  pkg/addons/velero/velero.go
  pkg/helpers/snapshots.go
  pkg/kubeutils/kubeutils.go
Labels: type::feature

#538 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#547 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#544 set license snapshot support status during installation
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature

#549 update troubleshoot and k8s dependencies
  go.mod
  go.sum
Labels: type::chore

#548 Update admin console chart to v1.108.9-build.1
  Makefile
Labels: type::bug, bug::normal

#546 specify velero credentials secret name
  pkg/addons/velero/velero.go
Labels: type::feature

#543 feat: allow overrides on add-on values at install time
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/addons/applier_test.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/testdata/generate-helm-config-overrides-multiple-addons.yaml
  pkg/addons/testdata/generate-helm-config-overrides-openebs.yaml
  pkg/addons/testdata/generate-helm-config-overrides-registry.yaml
Labels: type::feature

#552 chore: bump operator to v0.29.0
  Makefile
Labels: type::chore

#551 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#554 use openebs-archive chart repo
  Makefile
  e2e/scripts/unsupported-overrides.sh
Labels: bug, type::bug, bug::regression

#561 use openebs/openebs 4.0 at new repo
  .github/workflows/dependencies.yaml
  Makefile
  e2e/scripts/single-node-install.sh
  e2e/scripts/unsupported-overrides.sh
  pkg/addons/openebs/openebs.go
  pkg/addons/testdata/generate-helm-config-overrides-multiple-addons.yaml
  pkg/addons/testdata/generate-helm-config-overrides-openebs.yaml
Labels: type::feature

#541 generate support bundles in e2e tests
  .github/actions/e2e/action.yml
  e2e/cluster/cluster.go
  e2e/install_test.go
  e2e/scripts/collect-support-bundle.sh
  e2e/scripts/validate-support-bundle.sh
  e2e/support-bundle_test.go
Labels: type::chore

#553 add backup label to initial installation object
  e2e/scripts/single-node-install.sh
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature
