Repository replicatedhq/embedded-cluster, pull requests merged in 2024-11, with the labels that each got.

#1436 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1433 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1438 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1444 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1446 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1447 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1449 feat: add preflight for ip forwarding
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1424 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr

#1450 chore(ci): e2e test previous stable release
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  e2e/install_test.go
  e2e/kots-release-install-stable/cluster-config.yaml
  e2e/kots-release-install-stable/config.yaml
  e2e/kots-release-install-stable/deployment-2.yaml
  e2e/kots-release-install-stable/deployment.yaml
  e2e/kots-release-install-stable/k8s-app.yaml
  e2e/kots-release-install-stable/kots-app.yaml
  e2e/kots-release-install-stable/kots-lint-config.yaml
  e2e/kots-release-install-stable/preflight.yaml
  e2e/kots-release-install-stable/troubleshoot.yaml
  e2e/utils.go
Labels: type::chore

#1455 feat: support for aws ec2 imdsv2
  pkg/defaults/cloudprovider.go
  pkg/defaults/defaults.go
Labels: type::feature

#1459 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1456 fix(registry): logs missing from support bundle
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::bug, bug::normal

#1461 fix: fail to discover azure standard sku public ip address
  operator/pkg/artifacts/upgrade_test.go
  pkg/defaults/cloudprovider.go
  pkg/defaults/cloudprovider_test.go
Labels: type::bug, bug::normal

#1457 fix: possibly leaking connections
  cmd/local-artifact-mirror/artifact.go
  operator/pkg/artifacts/artifacts.go
Labels: type::chore

#1453 fix: unable to upgrade EC when introducing a required config item w/o…
  Makefile
  README.md
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/playwright/tests/shared/deploy-app.ts
  e2e/playwright/tests/shared/deploy-ec18-app-version.ts
  e2e/playwright/tests/shared/login.ts
  scripts/ci-upload-binaries.sh
Labels: type::bug, bug::regression

#1464 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1460 automated postrelease testing
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  e2e/install_test.go
  e2e/proxy_test.go
  e2e/restore_test.go
  e2e/scripts/check-postupgrade-state.sh
  e2e/utils.go
Labels: type::chore

#1469 fix(ci): e2e test fails ntp preflight
  dev/distros/entrypoint.sh
Labels: type::chore

#1462 fix(ci): collect fallback cluster support bundle in airgap
  e2e/cluster/docker/cluster.go
  e2e/cluster/docker/container.go
  e2e/cluster/lxd/cluster.go
  e2e/scripts/collect-support-bundle-cluster.sh
Labels: type::chore

#1471 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1470 Revert "feat: add preflight for ip forwarding"
  pkg/preflights/host-preflight.yaml
Labels: type::chore

#1472 Fix clock sync flakiness for docker-based clusters
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/centos-9.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/debian-bullseye.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
  dev/distros/entrypoint.sh
  e2e/cluster/docker/container.go
Labels: type::chore

#1473 chore: sync go mods
  dagger/go.mod
  dagger/go.sum
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
  utils/go.mod
  utils/go.sum
Labels: type::chore

#1474 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1466 chore(ci): add openebs integration tests
  .github/workflows/ci.yaml
  README.md
  tests/integration/Makefile
  tests/integration/README.md
  tests/integration/openebs/analytics_test.go
  tests/integration/openebs/common.go
  tests/integration/openebs/customdatadir_test.go
  tests/integration/openebs/static/podandpvc.yaml
  tests/integration/openebs/static/static.go
  tests/integration/util/helm.go
  tests/integration/util/io.go
  tests/integration/util/k8s.go
  tests/integration/util/kind.go
  tests/integration/util/kind/config.go
  tests/integration/util/testing.go
Labels: type::chore

#1476 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1485 fix(ci): previous stable tests do not work for k0s 1.29
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
Labels: type::chore

#1488 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1486 run online ci tests against tagged releases
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
Labels: type::chore

#1475 feat: warn if online installation is attempted on air gap
  pkg/cmd/install.go
  pkg/cmd/join.go
  pkg/cmd/restore.go
  pkg/release/release.go
Labels: type::feature

#1489 chore(local-dev): fixes the metadata generation file for the operator version
  scripts/ci-build-deps.sh
Labels: type::chore

#1491 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1492 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1493 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1494 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1484 feat: enable ip_forward, disable arp_ignore arp_filter
  pkg/cmd/install.go
  pkg/cmd/join.go
  pkg/cmd/preflights.go
  pkg/cmd/reset.go
  pkg/cmd/restore.go
  pkg/configutils/runtime.go
  pkg/configutils/runtime_test.go
  pkg/goods/goods.go
  pkg/goods/materializer.go
  pkg/goods/materializer_test.go
  pkg/goods/static/99-embedded-cluster.conf
Labels: type::feature

#1454 feat(preflights): add arp filtering related preflights
  Makefile
  go.mod
  go.sum
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1496 chore: fix message when join node is not included in the no-proxy addresses
  pkg/cmd/join.go
Labels: type::chore

#1497 Use warn function when doing online install after downloading air gap
  pkg/cmd/install.go
Labels: type::chore

#1498 update to k0s 1.30.6
  Makefile
  go.mod
  go.sum
  k0s-patches/release-1.29/0001-fix-chart-crd-forceUpgrade-field-should-be-nil-by-de.patch
  k0s-patches/release-1.30/0001-fix-chart-crd-forceUpgrade-field-should-be-nil-by-de.patch
Labels: type::chore

#1502 Include binutils in distro images to avoid network flakiness
  .github/workflows/distros.yaml
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/centos-9.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/debian-bullseye.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
  e2e/install_test.go
  e2e/unsupported-overrides_test.go
Labels: type::chore

#1501 do not use a 'v' prefix for the embedded cluster version in post-release testing
  .github/workflows/release-prod.yaml
Labels: type::chore

#1503 promote the current EC version to the stable channel on release
  .github/workflows/release-prod.yaml
Labels: type::chore

#1100 Mention SeaweedFS in readme
  README.md
Labels: type::chore

#1505 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1506 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1499 Mention that HA can be enabled on or after 3rd node, not just on 3rd node
  pkg/cmd/join.go
Labels: type::chore

#1500 feat: add preflight for ip forwarding
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1487 chore: use cobra and viper for local-artifact-mirror
  Makefile
  cmd/local-artifact-mirror/main.go
  cmd/local-artifact-mirror/pull.go
  cmd/local-artifact-mirror/pull_binaries.go
  cmd/local-artifact-mirror/pull_helmcharts.go
  cmd/local-artifact-mirror/pull_images.go
  cmd/local-artifact-mirror/serve.go
Labels: type::chore

#1509 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1510 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1507 chore(preflights): replace run collector with host sysctl for ip_forwarding
  pkg/preflights/host-preflight.yaml
Labels: type::chore

#1515 validate that the registry is still available for pulls after HA migration
  e2e/kots-release-install/deployment-2.yaml
  e2e/kots-release-upgrade/deployment-2.yaml
  e2e/scripts/check-airgap-post-ha-state.sh
Labels: type::chore

#1439 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1490 feat: prompt in the install command if newer app release version is available
  pkg/cmd/install.go
  pkg/cmd/vendorapp.go
  pkg/cmd/vendorapp_test.go
  pkg/prompts/decorative/decorative.go
  pkg/prompts/plain/plain.go
  pkg/prompts/prompts.go
  scripts/ci-release-app.sh
Labels: type::feature

#1518 Update config value help, and alphabetize flags
  pkg/cmd/install.go
Labels: type::chore

#1519 fix: new app version prompt default to no, do not prompt if no terminal
  cmd/embedded-cluster/main.go
  dagger/go.mod
  dagger/go.sum
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
  pkg/cmd/install.go
  pkg/cmd/vendorapp.go
  pkg/cmd/vendorapp_test.go
  pkg/prompts/prompts.go
Labels: type::feature

#1522 fix: cli warn and error should go to stdout like the lower levels
  e2e/install_test.go
  pkg/logging/logging.go
Labels: type::chore

#1524 Clarify air gap bundle warning
  pkg/cmd/install.go
  pkg/cmd/restore.go
Labels: type::feature

#1521 chore(gitignore): ignore preflight bundles
  .gitignore
Labels: type::chore

#1465 feat: add preflight for network connectivity (aka firewall preflight)
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/template.go
Labels: type::feature

#1529 Cleaning up some cobra flags
  cmd/installer/cli/cidr.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/proxy.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/root.go
  pkg/cmd/flags.go
  pkg/cmd/network.go
  pkg/cmd/network_test.go
  pkg/cmd/proxy.go
  pkg/cmd/proxy_test.go
  pkg/cmd/util.go
  pkg/k0s/install.go
Labels: type::chore

#1530 increase maximum airgap bundle build wait from 10m to 20m, with shorter increments
  e2e/airgap.go
Labels: type::chore

#1532 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1533 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1536 refactor root.go
  cmd/installer/cli/root.go
  cmd/installer/cli/shell.go
Labels: type::chore

#1535 bump chart version of ingress-nginx to 4.11.3/4.12.0-beta.0
  e2e/kots-release-install/cluster-config.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/scripts/airgap-prepare.sh
  e2e/scripts/check-postupgrade-state.sh
Labels: type::chore

#1537 Add ability to attach a replicated release to an unreleased EC binary
  .gitignore
  Makefile
  hack/dev-embed.go
Labels: type::chore

#1528 fix(metrics): redact specific flags which might hold secrets
  pkg/metrics/reporter.go
  pkg/metrics/reporter_test.go
  pkg/metrics/util.go
  pkg/metrics/util_test.go
Labels: type::bug, bug::normal

#1495 feat: always run host preflights
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/restore.go
  e2e/scripts/default-install.sh
  e2e/scripts/resume-restore.exp
  pkg/preflights/output.go
Labels: type::feature

#1547 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1548 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1551 Add comment about nil runtime config in old installation objects
  pkg/runtimeconfig/runtimeconfig.go
Labels: type::chore

#1549 [chore] bump troubleshoot
  Makefile
  go.mod
  go.sum
Labels: type::chore

#1546 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1545 change "no-prompt" to "yes"
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/restore.go
  e2e/install_test.go
  e2e/preflights_test.go
  e2e/reset_test.go
  e2e/scripts/default-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/reset-installation.sh
  e2e/scripts/single-node-host-preflight-install.sh
  e2e/scripts/unsupported-overrides.sh
  e2e/sudo_test.go
  tests/dryrun/util.go
Labels: type::feature

#1552 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1525 Bootstrap the manager process
  Makefile
  cmd/manager/main.go
  cmd/manager/start.go
  cmd/manager/status.go
  go.mod
  go.sum
  pkg/socket/server.go
  pkg/websocket/server.go
Labels: type::chore

#1527 chore(metrics): kots will send upgrade events instead of the operator
  Makefile
  operator/Makefile
  operator/controllers/installation_controller.go
  operator/pkg/cli/upgrade.go
  operator/pkg/cli/upgrade_job.go
  operator/pkg/metrics/metrics.go
  pkg/addons/adminconsole/adminconsole.go
Labels: type::bug, bug::normal

#1560 chore(ci): address melange's latest change
  .github/workflows/ci.yaml
  common.mk
  operator/deploy/apko.tmpl.yaml
  operator/deploy/melange.tmpl.yaml
  pkg/addons/adminconsole/adminconsole.go
  scripts/build-and-release.sh
  scripts/ci-build-bin.sh
  scripts/ci-build-deps.sh
  scripts/ci-embed-release.sh
  scripts/ci-release-app.sh
  scripts/ci-upload-binaries.sh
Labels: type::chore

#1556 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1561 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security
