Repository replicatedhq/embedded-cluster, pull requests merged in 2024-05, with the labels that each got.

#564 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#565 backup infra charts
  Makefile
  e2e/kots-release-install/deployment-2.yaml
  e2e/kots-release-install/deployment.yaml
  e2e/kots-release-upgrade/deployment-2.yaml
  e2e/kots-release-upgrade/deployment.yaml
  e2e/scripts/check-postupgrade-state.sh
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  scripts/create-previous-k0s-release.sh
  scripts/create-upgrade-release.sh
Labels: type::feature

#566 sort embedded cluster installations by name, not creation time, to handle restores
  Makefile
Labels: type::bug, bug::normal

#568 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#567 Add note about no-prompt and password
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/shell.go
  cmd/embedded-cluster/uninstall.go
  cmd/embedded-cluster/update.go
  cmd/embedded-cluster/version.go
  cmd/local-artifact-mirror/main.go
  cmd/local-artifact-mirror/pull.go
Labels: type::chore

#576 update operator version
  Makefile
Labels: type::feature

#578 test with Alma, not Rocky, Linux
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
Labels: type::chore

#575 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#579 chore: capture and analyse ipv4 interfaces
  pkg/goods/support/host-support-bundle.yaml
Labels: type::chore

#532 Add a test for multi-node airgapped install & upgrade
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  cmd/embedded-cluster/join.go
  e2e/install_test.go
  e2e/utils.go
  pkg/airgap/containerd.go
Labels: type::feature

#586 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#588 chore: bump eco and related dependencies
  Makefile
  go.mod
  go.sum
Labels: type::chore

#577 Wait for installation status on install/restore
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/unsupported-overrides.sh
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/kotscli/kotscli.go
  pkg/kubeutils/kubeutils.go
  pkg/spinner/options.go
Labels: type::feature

#592 add a validate-success job to the PR workflow
  .github/workflows/pull-request.yaml
Labels: type::chore

#590 remove embedded-cluster from additional components installation output
  pkg/kotscli/kotscli.go
  pkg/kubeutils/kubeutils.go
Labels: bug, type::bug, bug::normal

#594 be equally excited for all of our messages
  cmd/embedded-cluster/install.go
Labels: type::feature

#593 Backup registry
  pkg/addons/registry/registry.go
  pkg/addons/testdata/generate-helm-config-overrides-multiple-addons.yaml
  pkg/addons/testdata/generate-helm-config-overrides-registry.yaml
Labels: type::feature

#601 check for installation updates every second instead of every 5 seconds
  pkg/kubeutils/kubeutils.go
Labels: type::chore

#602 remove the 'restic' backup setting in velero as we are moving forward with kopia
  pkg/addons/velero/velero.go
Labels: type::chore

#595 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#596 Use Playwright instead of testIM
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/README.md
  e2e/install_test.go
  e2e/playwright/tests/deploy-airgap-upgrade/test.spec.ts
  e2e/playwright/tests/deploy-app/test.spec.ts
  e2e/playwright/tests/get-join-controller-command/test.spec.ts
  e2e/playwright/tests/get-join-worker-command/test.spec.ts
  e2e/playwright/tests/shared/deploy-app.ts
  e2e/reset_test.go
  e2e/restore_test.go
  e2e/scripts/install-testim.sh
  e2e/scripts/testim.sh
  e2e/support-bundle_test.go
  e2e/utils.go
Labels: type::chore, type::tests

#610 feat: apply built in overrides before end user overrides
  cmd/embedded-cluster/install.go
  e2e/kots-release-install/cluster-config.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/scripts/single-node-install.sh
  pkg/addons/applier.go
  pkg/addons/applier_test.go
  pkg/addons/testdata/generate-helm-config-overrides-multiple-addons.yaml
  pkg/addons/testdata/generate-helm-config-overrides-openebs.yaml
  pkg/addons/testdata/generate-helm-config-overrides-registry.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/builtin-extensions-overrides-override-admin-console.yaml
  pkg/config/testdata/builtin-extensions-overrides-override-multiple-charts.yaml
  pkg/config/testdata/builtin-extensions-overrides-override-unknown.yaml
Labels: type::feature

#603 feat: ability to resume a previously interrupted restore operation
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  cmd/embedded-cluster/restore.go
  e2e/restore_test.go
  e2e/scripts/resume-restore.exp
Labels: type::feature

#619 Update KOTS to v1.109.3
  Makefile
Labels: type::feature

#620 update to latest versions of everything besides k0s
  Makefile
Labels: type::chore

#621 feat: wait for coredns and metrics-server
  pkg/addons/applier.go
Labels: type::feature

#623 Revert "feat: wait for coredns and metrics-server"
  pkg/addons/applier.go
Labels: type::bug, bug::regression

#622 feat: break early if installation object has fatal error
  pkg/kubeutils/kubeutils.go
Labels: type::feature

#624 feat: wait for coredns and metrics-server, mk2
  cmd/embedded-cluster/restore.go
  pkg/addons/applier.go
  pkg/kubeutils/kubeutils.go
Labels: type::feature

#631 watch for all deployments in kube-system
  cmd/embedded-cluster/restore.go
  pkg/addons/applier.go
  pkg/kubeutils/kubeutils.go
Labels: type::feature

#614 feat: implement airgap restore
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  cmd/embedded-cluster/restore.go
  e2e/install_test.go
  e2e/restore_test.go
  e2e/scripts/bypass-kurl-proxy.sh
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/restore-installation-airgap.exp
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/registry/registry.go
  pkg/addons/velero/velero.go
  pkg/defaults/defaults.go
  pkg/helpers/ip.go
  pkg/helpers/ip_test.go
Labels: type::feature

#633 use the updated wait_for_nginx_pods code in all tests
  e2e/scripts/check-pre-minio-removal-installation-state.sh
  e2e/scripts/pre-minio-removal-install.sh
  e2e/scripts/single-node-install.sh
Labels: type::chore

#634 allow releases without the v prefix
  .github/workflows/release-prod.yaml
  cmd/embedded-cluster/restore.go
Labels: type::chore

#635 feat: allow materialize with a prefix
  cmd/embedded-cluster/materialize.go
  pkg/goods/goods.go
  pkg/goods/materializer.go
Labels: type::feature

#632 airgap disaster recovery CI test
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/restore.go
  e2e/cluster/cluster.go
  e2e/playwright/tests/deploy-airgap-upgrade/test.spec.ts
  e2e/restore_test.go
  e2e/scripts/install-playwright.sh
  e2e/scripts/restore-installation-airgap.exp
  e2e/scripts/single-node-airgap-install.sh
  e2e/utils.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/options.go
  pkg/addons/velero/velero.go
Labels: type::chore

#630 feat: add tls to internal registry
  Makefile
  cmd/local-artifact-mirror/artifact.go
  go.mod
  pkg/addons/registry/registry.go
  pkg/airgap/containerd.go
  pkg/certs/certs.go
  pkg/certs/options.go
Labels: type::feature

#637 Use new DR license field
  Makefile
  e2e/scripts/unsupported-overrides.sh
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/helpers/snapshots.go
Labels: type::feature

#646 unmask access key id input during restore
  cmd/embedded-cluster/restore.go
Labels: type::chore

#649 update dependencies to allow building with k0s v1.28.8+k0s.0
  Makefile
  go.mod
  go.sum
Labels: type::chore

#650 bump ECO to 0.33.1
  Makefile
  e2e/scripts/unsupported-overrides.sh
  go.mod
  go.sum
Labels: type::feature

#651 admin console chart version 1.109.7
  Makefile
Labels: type::feature

#652 feat: update k0s to v1.29.5
  Makefile
  go.mod
  go.sum
Labels: type::chore

#656 admin console chart 1.109.8
  Makefile
Labels: type::chore

#659 Update LICENSE
  LICENSE
Labels: type::chore
