Repository replicatedhq/embedded-cluster, pull requests merged in 2024-06, with the labels that each got.

#664 test on centos 9 stream, not 8
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
Labels: type::chore

#660 use api.replicated.com for e2e check-internet
  e2e/cluster/cluster.go
Labels: type::chore

#657 prompt for high availability during node join
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/join_test.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/kubeutils/kubeutils.go
Labels: type::feature

#662 chore: add e2e test for airgap upgrades using the same k0s version
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
  e2e/playwright/tests/deploy-airgap-upgrade/test.spec.ts
  e2e/restore_test.go
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/playwright.sh
Labels: type::chore

#674 release three airgap versions in on-merge tests as well as on-pr
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
Labels: type::chore

#675 Clean up existing embedded cluster systemd service before creating symlink
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/restore.go
  cmd/embedded-cluster/uninstall.go
Labels: type::bug, bug::normal

#677 feat(ha): print warning on control plane node reset
  cmd/embedded-cluster/uninstall.go
  e2e/install_test.go
Labels: type::feature

#682 handle github version tags without a 'v'
  .github/workflows/release-prod.yaml
Labels: type::chore

#691 feat: build and publish local-artifact-mirror image
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  .github/workflows/release-prod.yaml
  Dockerfile
  Makefile
Labels: type::feature

#697 test with Debian 11
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
Labels: type::chore

#698 feat: publish lam image location in version metadata
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  .github/workflows/release-prod.yaml
  Makefile
  cmd/embedded-cluster/version.go
  go.mod
  go.sum
  pkg/defaults/defaults.go
Labels: type::feature

#683 cache operator and kots binaries in the public files s3 bucket
  Makefile
  cmd/embedded-cluster/version.go
  e2e/version_test.go
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/defaults/defaults.go
  scripts/cache-files.sh
Labels: type::feature

#700 fix: add to k8s scheme once in init
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/uninstall.go
  cmd/local-artifact-mirror/pull.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/kubeutils/kubeutils.go
  pkg/kubeutils/scheme.go
Labels: type::chore

#701 fix: metadata has wrong ec version
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  scripts/create-upgrade-release.sh
Labels: type::chore

#715 Add proxy support to Velero
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/restore.go
Labels: type::feature

#720 cache compressed versions of the kots and embedded-cluster-operator binaries
  cmd/embedded-cluster/version.go
  scripts/cache-files.sh
Labels: type::feature

#722 feat: bump kots version to 1.109.13
  Makefile
Labels: type::chore

#730 feat: ask for the admin console password before materializing binaries
  cmd/embedded-cluster/install.go
Labels: type::chore

#731 bug: allow resetting clusters that do not have an installation object
  cmd/embedded-cluster/uninstall.go
  pkg/kubeutils/kubeutils.go
Labels: type::bug, bug::normal
