Repository replicatedhq/embedded-cluster, pull requests merged in 2024-03, with the labels that each got.

#426 add short flag alias for --license
  cmd/embedded-cluster/install.go
Labels: type::feature

#432 include troubleshoot and kubectl binary versions in metadata
  Makefile
  cmd/embedded-cluster/types/types.go
  cmd/embedded-cluster/version.go
  e2e/version_test.go
  pkg/defaults/defaults.go
Labels: type::chore

#437 promote pre-minio-removal in release-dev workflow too
  .github/workflows/release-dev.yaml
  e2e/scripts/vandoor-prepare.sh
Labels: type::chore

#439 include k0s images within metadata output
  .github/workflows/dependencies.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  .github/workflows/release-prod.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/types/types.go
  cmd/embedded-cluster/version.go
  e2e/version_test.go
  go.mod
  go.sum
  pkg/config/config.go
Labels: type::feature

#441 update to the first release version of embedded-cluster-utils
  go.mod
  go.sum
Labels: type::chore

#438 chore: enable debug output on test scripts
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-nodes-removed.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/collect-support-bundle.sh
  e2e/scripts/default-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/pre-minio-removal-install.sh
  e2e/scripts/puppeteer.sh
  e2e/scripts/reset-installation.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/unsupported-overrides.sh
  e2e/scripts/vandoor-prepare.sh
  e2e/scripts/wait-for-ready-nodes.sh
  e2e/scripts/yum-install-tar.sh
Labels: type::chore

#443 feat: introduces local artifact server and materialize subcommand
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/main.go
  cmd/embedded-cluster/materialize.go
  cmd/embedded-cluster/uninstall.go
  cmd/local-artifact-mirror/main.go
  e2e/local-artifact-mirror_test.go
  e2e/materialize_test.go
  e2e/utils.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/goods/goods.go
  pkg/goods/support/host-support-bundle.yaml
  pkg/goods/systemd/local-artifact-mirror.service
Labels: type::feature

#444 bug: fix moving files across different filesystems
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  pkg/helpers/fs.go
  pkg/helpers/fs_test.go
Labels: type::bug, bug::normal

#435 add airgap support to installer
  .github/workflows/dependencies.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/types/types.go
  cmd/embedded-cluster/version.go
  e2e/cluster/cluster.go
  e2e/version_test.go
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/options.go
  pkg/addons/registry/registry.go
  pkg/airgap/app_configmaps.go
  pkg/airgap/app_configmaps_test.go
  pkg/airgap/config.go
  pkg/airgap/containerd.go
  pkg/airgap/materialize.go
  pkg/airgap/remap.go
  pkg/airgap/testfiles/tiny-airgap-noimages-app/cluster-config.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages-app/example-deployment.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages-app/k8s-app.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages-app/kots-app.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages-app/kots-config.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages-app/kots-lint-config.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages-app/kots-preflight.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages-app/kots-support-bundle.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages/airgap.yaml
  pkg/airgap/version.go
  pkg/airgap/version_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/helpers/string.go
  pkg/kubeutils/kubeutils.go
  pkg/metrics/airgap.go
  pkg/metrics/sender.go
  pkg/preflights/preflights.go
  pkg/release/release.go
Labels: type::feature

#436 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#454 add a 'dev' prefix to binaries/metadata pushed by CI testing
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
Labels: type::chore

#455 Adds a reboot flag to `reset`
  cmd/embedded-cluster/uninstall.go
Labels: type::feature

#457 test airgap in CI
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  e2e/install_test.go
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/vandoor-prepare.sh
Labels: type::feature

#459 hide airgap bundle flag on install
  cmd/embedded-cluster/install.go
Labels: type::chore

#456 Embed the KOTS CLI binary and use it to install the app
  .gitignore
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/uninstall.go
  e2e/scripts/default-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/pre-minio-removal-install.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/unsupported-overrides.sh
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/options.go
  pkg/airgap/app_configmaps.go
  pkg/airgap/app_configmaps_test.go
  pkg/airgap/materialize.go
  pkg/airgap/version_test.go
  pkg/goods/goods.go
  pkg/helpers/command.go
Labels: type::feature

#458 Update Makefile versions
  Makefile
Labels: type::chore, automated-pr, makefile

#446 feature: implement artifact puller
  cmd/local-artifact-mirror/artifact.go
  cmd/local-artifact-mirror/main.go
  cmd/local-artifact-mirror/pull.go
  cmd/local-artifact-mirror/serve.go
  go.mod
  go.sum
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/goods/goods.go
  pkg/tgzutils/tgz.go
Labels: type::feature

#463 chore: remove duplicated log lines
  e2e/install_test.go
  e2e/local-artifact-mirror_test.go
  e2e/reset_test.go
  e2e/support-bundle_test.go
  e2e/unsupported-overrides_test.go
Labels: type::chore

#461 feat: restart mirror on binary change
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/uninstall.go
  cmd/local-artifact-mirror/serve.go
  e2e/local-artifact-mirror_test.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/goods/systemd/local-artifact-mirror.service
Labels: type::feature

#464 feat: create installation object with airgap set
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature

#462 test with real airgap
  .github/actions/e2e/action.yml
  .github/workflows/dependencies.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  cmd/embedded-cluster/version.go
  e2e/cluster/cluster.go
  e2e/install_test.go
  e2e/kots-release-install/cluster-config.yaml
  e2e/scripts/airgap-prepare.sh
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/vandoor-prepare.sh
  e2e/version_test.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/registry/registry.go
Labels: type::feature

#465 feat: create version metadata config map
  .github/workflows/pull-request.yaml
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/version.go
  e2e/scripts/single-node-install.sh
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/options.go
Labels: type::feature

#467 further enhance airgap test
  .github/workflows/dependencies.yaml
  Makefile
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::feature

#468 use pvc for registry storage
  pkg/addons/registry/registry.go
Labels: type::feature

#469 feat: make a copy of the binary under /var/lib/embedded-cluster
  e2e/scripts/single-node-install.sh
  pkg/goods/goods.go
Labels: type::feature
