Repository replicatedhq/embedded-cluster, pull requests merged in 2024-09, with the labels that each got.

#1087 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1088 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1027 update admin console version v1.115.1
  e2e/install_test.go
  e2e/playwright/tests/deploy-ec18-app-version/test.spec.ts
  e2e/playwright/tests/get-join-controller-command/test.spec.ts
  e2e/playwright/tests/get-join-worker-command/test.spec.ts
  e2e/playwright/tests/shared/deploy-app.ts
  e2e/playwright/tests/shared/deploy-ec18-app-version.ts
  e2e/playwright/tests/shared/index.ts
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::feature

#1095 bump go to 1.23.0
  .github/workflows/ci.yaml
  cmd/embedded-cluster/install.go
  go.mod
  go.sum
  kinds/go.mod
  pkg/logging/logging.go
Labels: type::chore

#1098 rename the kinds CI validate-success task to 'validate-success-kinds'
  .github/workflows/kinds.yaml
Labels: type::chore

#1091 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1092 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#1094 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1101 fix(utils): change module path and update go version
  utils/go.mod
Labels: type::chore

#1104 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1106 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#1108 test with a noproxy that doesn't include every private IP
  e2e/cluster/cluster.go
  e2e/proxy_test.go
  e2e/restore_test.go
  e2e/utils.go
Labels: type::chore

#1110 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1111 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#1115 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: automated-pr, images, type::security

#1125 chore: upgrade k0s to 1.29.8
  Makefile
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
  scripts/cache-files.sh
Labels: type::chore

#1130 kotsadm 1.116.0 testing
  e2e/playwright/tests/get-restore-join-controller-command/test.spec.ts
  e2e/restore_test.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore

#1133 chore(kinds): add binaryOverrideUrl and metadataOverrideUrl
  kinds/apis/v1beta1/config_types.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
Labels: type::chore

#1134 fix(ci): release using ttl.sh image
  .github/workflows/release-prod.yaml
Labels: type::bug, bug::regression

#1135 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#1127 feat: add --private-ca flag
  .github/workflows/ci.yaml
  .gitignore
  Makefile
  cmd/embedded-cluster/install.go
  e2e/cluster/cluster.go
  e2e/install_test.go
  e2e/utils.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
  pkg/addons/applier.go
  pkg/addons/options.go
  pkg/goods/bins/.placeholder
  pkg/goods/internal/bins/.placeholder
  pkg/goods/materializer.go
Labels: type::feature

#1137 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.tpl.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#1126 fix(proxy): do not pass unnecessary values to no-proxy
  cmd/embedded-cluster/proxy_test.go
  e2e/cluster/cluster.go
  pkg/defaults/defaults.go
Labels: type::chore

#1147 chore(ci): build and release cleanup
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  .gitignore
  Makefile
  operator/pkg/release/release.go
  scripts/build-and-release.sh
  scripts/ci-build-bin.sh
  scripts/ci-upload-binaries.sh
Labels: type::chore

#1146 chore: implement e2e for mitm proxy installations
  .github/workflows/ci.yaml
  e2e/cluster/cluster.go
  e2e/proxy_test.go
  e2e/scripts/install-and-configure-squid.sh
  e2e/utils.go
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-operator-deployment.yaml
  operator/charts/embedded-cluster-operator/values.yaml
  operator/charts/embedded-cluster-operator/values.yaml.tmpl
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::chore

#1149 fix(ci): image-scan workflow missing buildtools
  .github/workflows/image-scan.yaml
Labels: type::chore

#1153 chore(ci): fix release pipeline
  .github/workflows/release-prod.yaml
  scripts/ci-build-bin.sh
  scripts/ci-upload-binaries.sh
Labels: type::chore

#1154 Add development section to README.md
  README.md
Labels: type::chore

#1159 clarify that kots should be in the same parent directory, not a subdirectory
  README.md
Labels: type::chore

#1168 Update kotsadm dev readme
  README.md
Labels: type::chore

#1161 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1169 chore(ci): do not setup go twice
  .github/actions/setup-melange/action.yml
  .github/workflows/ci.yaml
  .github/workflows/image-scan.yaml
  .github/workflows/release-prod.yaml
Labels: type::chore

#1170 chore(ci): cache fio builds
  Makefile
  fio/Dockerfile
Labels: type::chore

#1171 Fix downloading KOTS bin for versions with build suffix
  Makefile
Labels: type::chore

#1172 Fix arm64 upgrades for dev env
  scripts/ci-build-bin.sh
Labels: type::chore

#1173 Update Dev requirements
  README.md
Labels: type::chore

#1174 Separate command blocks in dev README
  README.md
Labels: type::chore

#1175 Update dev SSH README
  README.md
Labels: type::chore

#1177 add local-dev dir to gitignore
  .gitignore
Labels: type::chore

#1178 bug: fix fio build so it can be used on other cpus
  fio/Dockerfile
Labels: type::bug, bug::normal

#1181 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr

#1182 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#1183 feat: update embeddedclusteroperator version
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
Labels: type::chore, automated-pr

#1184 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1185 fix(ci): build fails with no component found for metrics-server
  cmd/buildtools/k0s.go
Labels: type::chore

#1187 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1180 generate after-completion support bundles in parallel
  e2e/install_test.go
Labels: type::chore

#1160 chore(ci): build and tag all image architectures
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
  cmd/buildtools/addon.go
  cmd/buildtools/adminconsole.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/update.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  common.mk
  kinds/go.mod
  kinds/go.sum
  local-artifact-mirror/Makefile
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/registry/static/metadata.yaml
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/velero/static/metadata.yaml
  pkg/config/images.go
  pkg/config/images_test.go
  pkg/config/static/metadata.yaml
  pkg/release/k0s.go
Labels: type::chore

#1179 chore(ci): experiment with dagger
  .github/workflows/ci.yaml
  .github/workflows/image-scan.yaml
  .github/workflows/release-prod.yaml
  README.md
  dagger.json
  dagger/.gitattributes
  dagger/.gitignore
  dagger/README.md
  dagger/common.go
  dagger/go.mod
  dagger/go.sum
  dagger/main.go
  dagger/melange.go
  operator/Makefile
  operator/deploy/apko.tmpl.yaml
Labels: type::chore

#1198 chore: skip proxy tests on k0s < 1.29
  Makefile
  e2e/proxy_test.go
  e2e/restore_test.go
Labels: type::chore

#1194 check if chart values parse as yaml before installing application
  cmd/embedded-cluster/install.go
  pkg/preflights/app.go
  pkg/preflights/app_test.go
Labels: type::feature

#1197 fix(ci): do not override digest for wrong architecture
  cmd/buildtools/utils.go
Labels: type::chore

#1195 feat(preflights): include preflight collect results in support bundle
  Makefile
  cmd/embedded-cluster/install.go
  e2e/preflights_test.go
  go.mod
  go.sum
  pkg/goods/support/host-support-bundle.yaml
  pkg/preflights/preflights.go
Labels: type::feature

#1107 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1186 automatically detect node ip during install for noproxy
  README.md
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/preflights.go
  cmd/embedded-cluster/proxy.go
  cmd/embedded-cluster/proxy_test.go
  cmd/embedded-cluster/restore.go
  e2e/proxy_test.go
  kinds/apis/v1beta1/installation_types.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  pkg/netutils/ips.go
  pkg/netutils/ips_test.go
Labels: type::feature

#1202 feat(kinds): ability to override admin console and lam host ports
  kinds/apis/v1beta1/installation_types.go
  kinds/apis/v1beta1/zz_generated.deepcopy.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  operator/schemas/config-embeddedcluster-v1beta1.json
Labels: type::feature

#1203 hardcode proxy.replicated.com and replicated.app static IPs in troubleshoot output
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1204 feat: ability to specify network interface
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/preflights.go
  cmd/embedded-cluster/proxy.go
  cmd/embedded-cluster/restore.go
  dagger.json
  dagger/go.mod
  dagger/go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/defaults/defaults.go
  pkg/defaults/provider.go
  pkg/defaults/provider_test.go
  pkg/netutils/ips.go
  pkg/netutils/ips_test.go
Labels: type::feature

#1209 Fix joining worker nodes in dev env
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Labels: type::chore

#1207 feat: determine network interface / IP on join
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/preflights.go
  cmd/embedded-cluster/restore.go
  pkg/config/config.go
  pkg/netutils/ips.go
Labels: type::feature

#1206 chore(ci): build and publish operator and lam image with dagger
  common.mk
  dagger/chainguard.go
  dagger/go.mod
  dagger/go.sum
  dagger/localartifactmirror.go
  dagger/main.go
  dagger/melange.go
  dagger/operator.go
  deploy/README.md
  kinds/go.mod
  kinds/go.sum
  local-artifact-mirror/Makefile
  operator/Makefile
  operator/deploy/apko.tmpl.yaml
Labels: type::chore

#1201 feat: ability to override admin console and lam host ports
  Makefile
  cmd/embedded-cluster/flags.go
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/restore.go
  cmd/embedded-cluster/util.go
  cmd/local-artifact-mirror/serve.go
  dev/dockerfiles/operator/Dockerfile.ttlsh
  e2e/install_test.go
  e2e/local-artifact-mirror_test.go
  e2e/scripts/default-install.sh
  e2e/scripts/restore-multi-node-airgap-phase1.exp
  operator/controllers/installation_controller.go
  operator/pkg/artifacts/upgrade.go
  operator/pkg/charts/charts.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/options.go
  pkg/defaults/defaults.go
  pkg/helm/values.go
Labels: type::feature

#1199 report embedded cluster and k8s versions with metrics object
  pkg/metrics/sender.go
  pkg/metrics/sender_test.go
Labels: type::chore

#1211 use the entire installation spec object in node join response
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/join_test.go
  cmd/embedded-cluster/preflights.go
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore

#1218 fix(ci): remove unnecessary apko install
  .github/workflows/image-scan.yaml
Labels: type::chore

#1221 fix(ci): apko login mounting wrong auth dir
  dagger/localartifactmirror.go
  dagger/operator.go
Labels: type::chore

#1143 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1189 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1223 chore: eco is built at release time and is no longer needed in auto updates
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
Labels: type::chore

#1225 Document ability to manage kotsadm web packages in the dev env
  README.md
Labels: type::chore

#1226 Mention new terminal session for managing kotsadm web packages
  README.md
Labels: type::chore

#1205 feat: add host preflights for all needed ports
  cmd/embedded-cluster/reset.go
  e2e/cluster/cluster.go
  e2e/install_test.go
  e2e/preflights_test.go
  e2e/restore_test.go
  e2e/scripts/default-route-through-proxy.sh
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1191 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1229 fix: unable to get network interface for address when joining nodes
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/preflights.go
  pkg/netutils/ips.go
Labels: type::bug, bug::regression

#1227 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#1228 chore(e2e): make sure squid proxy generates a cert containing SANs
  e2e/scripts/install-and-configure-squid.sh
Labels: type::chore

#1224 feat: preflight support for custom lam and kots ports
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/preflights.go
  cmd/embedded-cluster/version.go
  go.mod
  go.sum
  pkg/preflights/host-preflight.yaml
  pkg/preflights/output.go
  pkg/preflights/preflights.go
  pkg/preflights/template.go
Labels: type::feature

#1220 Check for presence of channel in multichan license at install
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/install_test.go
  go.mod
  go.sum
Labels: type::bug, bug::normal

#1232 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#1233 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#1235 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1237 chore(dev): rebuild release
  Makefile
Labels: type::chore

#1240 chore: Bump troubleshoot version
  Makefile
Labels: type::chore

#1247 update the LXD client
  go.mod
  go.sum
Labels: type::chore

#1246 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1242 add additional reporting info
  operator/controllers/installation_controller.go
  operator/pkg/metrics/metrics.go
  pkg/metrics/events.go
  pkg/metrics/reporter.go
Labels: type::chore

#1254 update admin console chart to 1.117.3-build.1
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore
