Repository replicatedhq/embedded-cluster, pull requests merged in 2024-12, with the labels that each got.

#1568 fix(cli): join run-preflights should not use cidr flags but on instaled state
  cmd/installer/cli/join_runpreflights.go
Labels: type::bug, bug::regression

#1569 fix(cli): join run-preflights should define skip & ignore preflights flags with defaults
  cmd/installer/cli/join_runpreflights.go
Labels: type::bug, bug::regression

#1557 Install EC manager systemd service on install, join, and restore
  Makefile
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/restore.go
  pkg/goods/materializer.go
  pkg/goods/systemd/manager.service
  pkg/runtimeconfig/defaults.go
  pkg/websocket/server.go
Labels: type::chore

#1570 Include EC manager systemd service logs in support bundles
  pkg/goods/support/host-support-bundle.tmpl.yaml
  pkg/support/materialize.go
Labels: type::chore

#1572 refactor install2
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  pkg/preflights/run.go
Labels: type::chore

#1573 Install k0s
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  pkg/k0s/install.go
  pkg/metrics/reporter.go
Labels: type::chore

#1577 install openebs and admin console
  cmd/installer/cli/install2.go
  go.mod
  pkg/addons2/addons.go
  pkg/addons2/adminconsole/adminconsole.go
  pkg/addons2/adminconsole/install.go
  pkg/addons2/adminconsole/prepare.go
  pkg/addons2/adminconsole/static/metadata.yaml
  pkg/addons2/adminconsole/static/values.tpl.yaml
  pkg/addons2/openebs/install.go
  pkg/addons2/openebs/openebs.go
  pkg/addons2/openebs/prepare.go
  pkg/addons2/openebs/static/metadata.yaml
  pkg/addons2/openebs/static/values.tpl.yaml
  pkg/addons2/openebs/upgrade.go
  pkg/addons2/types/types.go
  pkg/helm/client.go
Labels: type::chore

#1553 send preflight results event when preflights fail
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/restore.go
  pkg/metrics/reporter.go
  pkg/metrics/types/types.go
Labels: type::feature

#1579 Auto select network iface when not provided
  cmd/installer/cli/install2.go
  cmd/installer/cli/network_interface.go
Labels: type::bug, bug::normal

#1578 Run host preflights as part of the install2 command
  Makefile
  cmd/installer/cli/cidr.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/proxy.go
  cmd/installer/cli/restore.go
  e2e/preflights_test.go
  pkg/addons2/adminconsole/prepare.go
  pkg/addons2/openebs/prepare.go
  pkg/metrics/reporter.go
  pkg/preflights/embed.go
  pkg/preflights/preflights.go
  pkg/preflights/run.go
  pkg/preflights/template.go
  pkg/preflights/template_test.go
  pkg/preflights/types/output.go
  pkg/preflights/types/template.go
Labels: type::feature

#1562 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1582 Configure sysctl before running preflights in install2
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
Labels: type::feature

#1554 feat(preflights): add support for TCP connection checks on the hpc template
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  pkg/dryrun/dryrun.go
  pkg/dryrun/kotsadm.go
  pkg/kotsadm/client.go
  pkg/kotsadm/interface.go
  pkg/kotsadm/types.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/template_test.go
  pkg/preflights/types/template.go
  tests/dryrun/join_test.go
  tests/dryrun/util.go
Labels: type::feature

#1555 Run all CI tests on prerelease
  .github/workflows/release-prod.yaml
Labels: type::chore

#1581 Clean up error output in cobra
  cmd/installer/cli/adminconsole_resetpassword.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/materialize.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/shell.go
  cmd/installer/cli/supportbundle.go
  cmd/installer/cli/update.go
  cmd/installer/cli/version.go
  cmd/installer/cli/version_embeddeddata.go
  cmd/installer/cli/version_listimages.go
  cmd/installer/cli/version_metadata.go
Labels: type::chore

#1586 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1587 Add firewall-cmd --list-all to host support bundle
  pkg/goods/support/host-support-bundle.tmpl.yaml
Labels: type::chore

#1596 Free up more disk space on the github runner
  .github/actions/free-disk-space/action.yml
Labels: type::chore

#1585 Install Velero as part of install2 command
  cmd/installer/cli/install2.go
  pkg/addons2/addons.go
  pkg/addons2/velero/install.go
  pkg/addons2/velero/prepare.go
  pkg/addons2/velero/static/metadata.yaml
  pkg/addons2/velero/static/values.tpl.yaml
  pkg/addons2/velero/velero.go
  pkg/helm/client.go
Labels: type::feature

#1594 Backport setting the best network interface to install
  cmd/installer/cli/install.go
Labels: type::bug, bug::normal

#1598 Install Helm extensions as part of install2 command
  cmd/installer/cli/install2.go
  pkg/addons2/addons.go
  pkg/extensions/extensions.go
Labels: type::feature

#1597 feat: add an API san for kubernetes.default.svc.cluster.local
  pkg/config/config.go
  pkg/config/config_test.go
  tests/dryrun/install_test.go
Labels: type::chore

#1602 Install Registry as part of install2 command
  cmd/installer/cli/install2.go
  pkg/addons2/addons.go
  pkg/addons2/adminconsole/install.go
  pkg/addons2/openebs/install.go
  pkg/addons2/registry/install.go
  pkg/addons2/registry/prepare.go
  pkg/addons2/registry/registry.go
  pkg/addons2/registry/static/metadata.yaml
  pkg/addons2/registry/static/values.tpl.yaml
  pkg/addons2/velero/install.go
  pkg/extensions/extensions.go
Labels: type::feature

#1603 Respect timeout field for helm extensions in install2 command
  pkg/addons2/adminconsole/install.go
  pkg/addons2/openebs/install.go
  pkg/addons2/registry/install.go
  pkg/addons2/velero/install.go
  pkg/extensions/extensions.go
  pkg/helm/client.go
Labels: type::feature

#1605 Accept CVE 2023 47108
  .github/actions/scan-image/action.yml
  .trivyignore.yaml
Labels: type::chore

#1604 Don't wrap CIDR errors
  cmd/installer/cli/cidr.go
  cmd/installer/cli/install.go
  pkg/netutils/nets.go
  pkg/netutils/nets_test.go
Labels: type::feature

#1607 Using a flat irvyignore file to be compatible with GHA
  .github/actions/scan-image/action.yml
  .trivyignore
  .trivyignore.yaml
Labels: type::chore

#1584 Update some flags' help texts
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
Labels: type::feature

#1610 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1613 chore(ci): fix velero 1.15 addon update
  cmd/buildtools/velero.go
Labels: type::chore

#1600 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1617 chore(ci): free disk space on large runners
  .github/actions/e2e/action.yml
Labels: type::chore

#1612 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1609 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1616 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1620 chore(ci): fix dagger install, pin to 1.14.0
  .github/workflows/ci.yaml
  .github/workflows/image-scan.yaml
  .github/workflows/release-prod.yaml
Labels: type::chore

#1622 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1621 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1583 feat(dr): new improved dr restore capability
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  Makefile
  cmd/installer/cli/restore.go
  cmd/installer/cli/restore_test.go
  cmd/installer/cli/testing/assets/release-restore-legacydr/backup.yaml
  cmd/installer/cli/testing/assets/release-restore-legacydr/release.yaml
  cmd/installer/cli/testing/assets/release-restore-newdr/backup.yaml
  cmd/installer/cli/testing/assets/release-restore-newdr/release.yaml
  cmd/installer/cli/testing/assets/release-restore-newdr/restore.yaml
  cmd/installer/cli/testing/static.go
  e2e/kots-release-install-newdr/backup.yaml
  e2e/kots-release-install-newdr/cluster-config.yaml
  e2e/kots-release-install-newdr/config.yaml
  e2e/kots-release-install-newdr/deployment-2.yaml
  e2e/kots-release-install-newdr/deployment.yaml
  e2e/kots-release-install-newdr/k8s-app.yaml
  e2e/kots-release-install-newdr/kots-app.yaml
  e2e/kots-release-install-newdr/kots-lint-config.yaml
  e2e/kots-release-install-newdr/preflight.yaml
  e2e/kots-release-install-newdr/restore.yaml
  e2e/kots-release-install-newdr/troubleshoot.yaml
  e2e/restore_test.go
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-config-values.sh
  e2e/scripts/check-post-restore-newdr.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/common.sh
  kinds/go.mod
  kinds/go.sum
  operator/Makefile
  operator/pkg/charts/charts_test.go
  operator/pkg/charts/detection.go
  operator/pkg/charts/reconcile_test.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/disasterrecovery/backup.go
  pkg/disasterrecovery/backup_test.go
  pkg/kotscli/kotscli.go
  pkg/kubeutils/scheme.go
  pkg/release/release.go
Labels: type::feature

#1623 chore: add back cli unit tests
  cmd/installer/cli/cidr_test.go
  cmd/installer/cli/install_runpreflights_test.go
  cmd/installer/cli/install_test.go
  cmd/installer/cli/proxy_test.go
  cmd/installer/cli/release_test.go
  pkg/k0s/install_test.go
  pkg/k0s/testdata/patch-k0s-config-change-external-address.yaml
  pkg/k0s/testdata/patch-k0s-config-change-sans.yaml
  pkg/k0s/testdata/patch-k0s-config-extra-args.yaml
  pkg/k0s/testdata/patch-k0s-config-k0s-storage.yaml
  pkg/k0s/testdata/patch-k0s-config-no-embedded-cluster-config.yaml
  pkg/k0s/testdata/patch-k0s-config-no-overrides.yaml
  pkg/kotsadm/testdata/join-command-response-empty-overrides.yaml
  pkg/kotsadm/testdata/join-command-response-multiple-port-overrides.yaml
  pkg/kotsadm/testdata/join-command-response-multiple-unused-overlays.yaml
  pkg/kotsadm/testdata/join-command-response-no-overrides.yaml
  pkg/kotsadm/testdata/join-command-response-override-ports.yaml
  pkg/kotsadm/testdata/join-command-response-storage-and-port-overrides.yaml
  pkg/kotsadm/types_test.go
Labels: type::chore

#1626 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1632 fix(ci): chainguard build is broken
  dagger.json
  dagger/go.mod
  dagger/go.sum
  kinds/go.mod
  kinds/go.sum
  local-artifact-mirror/deploy/melange.tmpl.yaml
  operator/deploy/melange.tmpl.yaml
Labels: type::chore

#1629 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1625 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1628 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1633 Handle webscoket upgrade command
  cmd/manager/main.go
  cmd/manager/send-upgradecluster.go
  cmd/manager/send.go
  cmd/manager/start.go
  hack/test-installation.yaml
  pkg/socket/server.go
  pkg/upgrade/autopilot.go
  pkg/upgrade/installation.go
  pkg/upgrade/upgrade.go
  pkg/websocket/server.go
Labels: type::chore

#1631 fix: Update hard coded paths of system binaries in support bundle analysers
  pkg/goods/support/host-support-bundle.tmpl.yaml
Labels: type::bug, bug::normal

#1635 chore(ci): add utils and dagger gomods to dependabot.yml
  .github/dependabot.yml
Labels: type::chore

#1648 chore(ci): group some dependabot gomod deps
  .github/dependabot.yml
Labels: type::chore

#1636 fix manager cluster upgrades and report status
  pkg/upgrade/installation.go
  pkg/upgrade/upgrade.go
  pkg/websocket/report.go
  pkg/websocket/server.go
  pkg/websocket/util.go
Labels: type::feature

#1649 chore: update deps
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
Labels: type::chore

#1634 feat(ci): change e2e tests to use new dr
  .github/workflows/ci.yaml
  e2e/kots-release-install-legacydr/cluster-config.yaml
  e2e/kots-release-install-legacydr/config.yaml
  e2e/kots-release-install-legacydr/deployment-2.yaml
  e2e/kots-release-install-legacydr/deployment.yaml
  e2e/kots-release-install-legacydr/k8s-app.yaml
  e2e/kots-release-install-legacydr/kots-app.yaml
  e2e/kots-release-install-legacydr/kots-lint-config.yaml
  e2e/kots-release-install-legacydr/preflight.yaml
  e2e/kots-release-install-legacydr/troubleshoot.yaml
  e2e/kots-release-install/backup.yaml
  e2e/kots-release-install/restore.yaml
  e2e/kots-release-upgrade/backup.yaml
  e2e/kots-release-upgrade/restore.yaml
  e2e/playwright/README.md
  e2e/restore_test.go
  e2e/scripts/bypass-kurl-proxy.sh
  e2e/scripts/check-post-restore.sh
  pkg/kotscli/kotscli.go
Labels: type::feature

#1650 fix: handle copy preflight results job already exists error
  operator/controllers/installation_controller.go
Labels: type::bug, bug::normal

#1651 Add / Upgrade / Remove extensions via websocket
  pkg/extensions/extensions.go
  pkg/extensions/util.go
  pkg/helm/client.go
  pkg/websocket/report.go
  pkg/websocket/server.go
Labels: type::feature

#1652 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1653 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1655 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1657 Add isEC2Install helm value to adminconsole chart
  pkg/addons2/adminconsole/static/values.tpl.yaml
Labels: type::feature

#1661 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1659 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1660 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1658 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1663 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1664 feat: [sc-117738] detect "plugin/forward: no nameservers found" from support bundles
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::feature

#1666 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1667 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1665 feat: [sc-117743] preflight check: ensure valid nameservers in /etc/resolv.conf
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1601 feat: Collect license used to install cluster in support bundles
  cmd/installer/cli/install.go
  e2e/host-support-bundle_test.go
  e2e/install_test.go
  e2e/proxy_test.go
  e2e/reset_test.go
  e2e/restore_test.go
  e2e/scripts/common.sh
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/validate-support-bundle.sh
  e2e/support-bundle_test.go
  pkg/goods/support/host-support-bundle.tmpl.yaml
Labels: type::feature

#1673 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1672 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1674 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1671 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr
