Repository replicatedhq/embedded-cluster, pull requests merged in 2024-07, with the labels that each got.

#733 Add -f as alias for --force
  cmd/embedded-cluster/uninstall.go
Labels: type::feature

#721 chore: remove binary file from repo
  pkg/release/release_test.go
  pkg/release/testdata/release.tar.gz
  pkg/release/testdata/release.yaml
Labels: type::chore

#743 feat: update openebs version
  Makefile
Labels: type::chore, automated-pr

#742 add DR restore behind proxy test
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  cmd/embedded-cluster/restore.go
  e2e/restore_test.go
  e2e/scripts/restore-installation.exp
Labels: type::chore

#745 feat: update seaweedfs version
  Makefile
Labels: type::chore, automated-pr

#680 feat: mirroring helm charts
  .github/workflows/mirror-helm-charts.yaml
  Makefile
  cmd/buildtools/addon.go
  cmd/buildtools/helm.go
  cmd/buildtools/main.go
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  go.mod
  go.sum
Labels: type::feature

#751 chore: remove job to update upstream add ons
  .github/workflows/dependencies.yaml
Labels: type::chore

#753 chore: fix github action yaml
  .github/workflows/mirror-helm-charts.yaml
Labels: type::chore

#747 feat: use mirrored helm charts
  Makefile
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/velero.go
Labels: type::feature

#755 fix: add spinner to show installation of k0s
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/restore.go
  go.mod
  pkg/preflights/preflights.go
Labels: type::chore

#746 feat: Use filesystem specific checks for host preflights
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#766 fix(ci): add back LDFLAGS for kots regression tests
  Makefile
  pkg/addons/adminconsole/adminconsole.go
Labels: type::chore

#765 feat: update openebs version
  Makefile
Labels: type::chore, automated-pr

#728 add 'pod-cidr' and 'service-cidr' install/restore flags
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/restore.go
  cmd/embedded-cluster/util.go
  e2e/install_test.go
  e2e/proxy_test.go
  e2e/restore_test.go
  e2e/scripts/check-cidr-ranges.sh
  e2e/scripts/restore-installation-airgap.exp
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/wait-for-ready-nodes.sh
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/options.go
  pkg/addons/registry/registry.go
  pkg/defaults/defaults.go
Labels: type::feature

#771 Add host-preflight to check for default route
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#769 CLI flag and password prompt improvements
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/restore.go
  cmd/embedded-cluster/uninstall.go
Labels: type::feature

#773 Formatting for CIDR mismatch error
  cmd/embedded-cluster/restore.go
Labels: type::feature

#772 Update wording for host preflights
  cmd/embedded-cluster/install.go
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#666 get apiserver & etcd certificates and their http health checks
  pkg/goods/support/host-support-bundle.yaml
Labels: type::chore

#684 feat: ability to upgrade the cluster via the new binary
  .github/actions/e2e/action.yml
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
  Makefile
  cmd/embedded-cluster/update.go
  cmd/local-artifact-mirror/pull.go
  deploy/local-artifact-mirror/Dockerfile
  e2e/cluster/cluster.go
  e2e/install_test.go
  e2e/kots-release-install/preflight.yaml
  e2e/kots-release-upgrade/preflight.yaml
  e2e/local-artifact-mirror_test.go
  e2e/materialize_test.go
  e2e/playwright/tests/deploy-airgap-upgrade/test.spec.ts
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/playwright/tests/shared/deploy-app.ts
  e2e/playwright/tsconfig.json
  e2e/restore_test.go
  e2e/scripts/collect-support-bundle-cluster.sh
  e2e/scripts/collect-support-bundle-host.sh
  e2e/scripts/install-playwright.sh
  e2e/scripts/playwright.sh
  e2e/scripts/single-node-install.sh
  e2e/sudo_test.go
  e2e/support-bundle_test.go
  e2e/unsupported-overrides_test.go
  e2e/utils.go
  e2e/version_test.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/goods/support/host-support-bundle.yaml
  pkg/kotscli/kotscli.go
  pkg/kubeutils/scheme.go
  scripts/cache-files.sh
  scripts/create-previous-k0s-release.sh
  scripts/create-upgrade-release.sh
Labels: type::feature

#785 Make suggestions if typo in command name
  cmd/embedded-cluster/main.go
Labels: type::feature

#738 chore: use reimplimented types
  cmd/embedded-cluster/version.go
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/velero.go
  pkg/config/config.go
Labels: type::chore

#788 speed up kotsadm readiness check
  Makefile
Labels: type::chore

#789 update to k0s 1.29.6
  Makefile
  go.mod
  go.sum
Labels: type::feature

#792 fix(ci): VERSION var collision
  Makefile
  deploy/images/local-artifact-mirror/apko.tmpl.yaml
  deploy/images/utils/apko.tmpl.yaml
  deploy/packages/local-artifact-mirror/melange.tmpl.yaml
Labels: type::chore

#793 feat: build k0s images with chainguard
  .github/workflows/image-deps-updater.yaml
  Makefile
  cmd/buildtools/k0s.go
  cmd/buildtools/main.go
  cmd/buildtools/update.go
  cmd/buildtools/utils.go
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/restore.go
  cmd/embedded-cluster/version.go
  deploy/images/calico-node/apko.tmpl.yaml
  deploy/images/coredns/apko.tmpl.yaml
  deploy/images/metrics-server/apko.tmpl.yaml
  pkg/config/images.go
  pkg/config/images/images.go
Labels: type::feature

#797 Build k0s calico-cni and calico-kube-controllers images with Chainguard
  Makefile
  cmd/buildtools/k0s.go
  deploy/images/calico-cni/apko.tmpl.yaml
  deploy/images/calico-kube-controllers/apko.tmpl.yaml
  pkg/config/images.go
  pkg/config/images/images.go
Labels: type::feature

#799 build images in parallel to the binary
  .github/workflows/pull-request.yaml
  .github/workflows/release-dev.yaml
Labels: type::chore

#800 Refactor apko related functions and move to utils
  cmd/buildtools/k0s.go
  cmd/buildtools/utils.go
Labels: type::feature

#801 unify on-PR and on-merge workflows
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  .github/workflows/pull-request.yaml
  e2e/cluster/cluster.go
  e2e/install_test.go
Labels: type::chore

#808 chore: Add hostname mismatch support bundle check
  pkg/goods/support/host-support-bundle.yaml
Labels: type::chore

#794 feat: use chainguard for OpenEBS images
  .github/workflows/image-deps-updater.yaml
  Makefile
  cmd/buildtools/addon.go
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/update.go
  cmd/buildtools/utils.go
  cmd/buildtools/utils_test.go
  deploy/images/openebs-kubectl/apko.tmpl.yaml
  deploy/images/openebs-linux-utils/apko.tmpl.yaml
  deploy/images/openebs-provisioner-localpv/apko.tmpl.yaml
  e2e/version_test.go
  pkg/addons/openebs/openebs.go
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.tpl.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::feature

#810 ensure both images and binaries are built before creating releases
  .github/workflows/ci.yaml
Labels: type::chore

#809 feat: use chainguard for OpenEBS images - feedback
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
  Makefile
  cmd/buildtools/addon.go
  cmd/buildtools/k0s.go
  cmd/buildtools/main.go
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
Labels: type::feature

#812 Automated openebs image updates
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: automated-pr, images, type::security

#811 Automated k0s image updates
  Makefile
Labels: automated-pr, images, type::security

#816 feat: use chainguard for velero
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
  cmd/buildtools/openebs.go
  cmd/buildtools/update.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  deploy/images/kubectl/apko.tmpl.yaml
  deploy/images/velero-plugin-for-aws/apko.tmpl.yaml
  deploy/images/velero-restore-helper/apko.tmpl.yaml
  deploy/images/velero/apko.tmpl.yaml
  pkg/addons/openebs/openebs.go
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.tpl.yaml
  pkg/addons/openebs/static/values.yaml
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.tpl.yaml
  pkg/addons/velero/static/values.yaml
  pkg/addons/velero/velero.go
Labels: type::feature

#817 Build kube-proxy image with Chainguard
  Makefile
  cmd/buildtools/addon.go
  cmd/buildtools/k0s.go
  deploy/images/kube-proxy/apko.tmpl.yaml
  pkg/config/images.go
  pkg/config/images/images.go
Labels: type::feature

#818 feat: use chainguard for velero - feedback
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
Labels: type::feature

#819 Build envoy image with chainguard
  Makefile
  cmd/buildtools/addon.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/velero.go
  deploy/images/envoy-distroless/apko.tmpl.yaml
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/velero.go
  pkg/config/images.go
  pkg/config/images/images.go
  pkg/config/static/metadata.yaml
  pkg/release/k0s.go
Labels: type::feature

#825 feat: update embeddedclusteroperator version
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::chore, automated-pr

#821 feat: remove unused k0s images from airgap bundle
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/restore.go
  cmd/embedded-cluster/version.go
  pkg/config/config.go
  pkg/config/images.go
  pkg/config/images_test.go
Labels: type::feature

#826 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: type::chore, automated-pr

#823 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#831 use the downloadAirgapBundle for the ResetAndReinstallAirgap test
  e2e/install_test.go
Labels: type::chore

#798 fix HA cluster upgrades
  .github/workflows/ci.yaml
  Makefile
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/join_test.go
  cmd/embedded-cluster/restore.go
  e2e/install_test.go
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/restore_test.go
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
  pkg/constants/restore.go
  pkg/highavailability/enable.go
  pkg/highavailability/enable_test.go
  pkg/highavailability/registry.go
  pkg/highavailability/seaweed.go
Labels: type::bug, bug::normal

#824 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#832 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#830 fix(ci): eco update addon is broken
  cmd/buildtools/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
Labels: type::chore

#833 Build pause image with chainguard
  Makefile
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  deploy/images/pause/apko.tmpl.yaml
  pkg/config/images.go
  pkg/config/images_test.go
Labels: type::feature

#842 Build seaweedfs image with chainguard
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
  cmd/buildtools/openebs.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/update.go
  deploy/images/seaweedfs/apko.tmpl.yaml
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.tpl.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::feature

#827 feat: scan images for CVEs
  .github/actions/scan-image/action.yml
  .github/workflows/ci.yaml
  .github/workflows/image-scan.yaml
  Makefile
  cmd/buildtools/adminconsole.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/main.go
  cmd/buildtools/metadata.go
  cmd/buildtools/registry.go
  cmd/buildtools/utils.go
  cmd/embedded-cluster/list_images.go
  cmd/embedded-cluster/metadata.go
  cmd/embedded-cluster/version.go
  go.mod
  go.sum
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
  pkg/addons/openebs/openebs.go
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/velero.go
  pkg/config/images.go
  pkg/helm/client.go
  pkg/helm/images.go
  pkg/helpers/addon.go
  pkg/helpers/string.go
Labels: type::chore

#758 chore: Add host preflights to check k0s system requirements
  .github/workflows/ci.yaml
  Makefile
  e2e/install_test.go
  e2e/scripts/common.sh
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/single-node-host-preflight-install.sh
  e2e/scripts/single-node-proxy-install.sh
  go.mod
  go.sum
  pkg/goods/support/host-support-bundle.yaml
  pkg/preflights/host-preflight.yaml
Labels: type::chore

#855 use latest patch image versions
  cmd/buildtools/addon.go
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
  pkg/config/static/metadata.yaml
Labels: type::feature

#857 move a lot of test code to common.sh
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/check-pre-minio-removal-installation-state.sh
  e2e/scripts/common.sh
  e2e/scripts/default-install.sh
  e2e/scripts/pre-minio-removal-install.sh
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/single-node-host-preflight-install.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/single-node-proxy-install.sh
  e2e/scripts/unsupported-overrides.sh
Labels: type::chore

#845 fix: failed to upload sarif file permission denied
  .github/workflows/image-scan.yaml
Labels: type::feature

#858 fix(ci): add back helm repos for client pull
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
Labels: type::chore

#862 Always use latest kubectl version
  cmd/buildtools/addon.go
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
  pkg/config/static/metadata.yaml
Labels: type::feature

#863 feat: remove kube-rbac-proxy image
  .github/workflows/ci.yaml
  .github/workflows/image-deps-updater.yaml
  Makefile
  cmd/buildtools/addon.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/update.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
  pkg/release/addon.go
Labels: type::feature

#871 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.yaml
Labels: automated-pr, images, type::security

#873 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#872 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: automated-pr, images, type::security

#868 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.yaml
Labels: type::chore, automated-pr

#867 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#878 Add automated PRs manager
  .github/workflows/automated-prs-manager.yaml
Labels: type::chore

#879 Don't label automated PRs
  .github/workflows/automated-prs-manager.yaml
Labels: type::chore

#866 feat: update velero version
  cmd/embedded-cluster/assets/resource-modifiers.yaml
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.yaml
Labels: type::chore, automated-pr

#876 feat: upgrade operator to remove kube-rbac-proxy
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::feature

#884 fix(ci): no apko-output-image after apko-login
  chainguard.mk
Labels: type::chore

#885 fix(ci): upgrade action github/codeql-action/upload-sarif@v3
  .github/actions/scan-image/action.yml
Labels: type::chore

#887 Group dependabot patch PRs
  .github/dependabot.yml
Labels: type::chore

#886 chore: utils image is no longer built on merge
  .github/workflows/release-prod.yaml
  Makefile
Labels: type::chore

#883 feat: proxy envoy image
  pkg/config/images.go
  pkg/config/images_test.go
Labels: type::feature

#892 fix(ci): cves are not closed in code scanning alerts
  .github/actions/scan-image/action.yml
  .github/actions/scan-image/image_id.sh
Labels: type::chore

#837 chore: always collect e2e support bundles and recordings
  .github/actions/e2e/action.yml
  e2e/install_test.go
Labels: type::chore

#894 Ensure k8s version matches the target version after upgrades
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  e2e/install_test.go
  e2e/restore_test.go
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/common.sh
  e2e/utils.go
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.yaml
Labels: type::bug, bug::regression

#895 fix: pin kubectl version to same as k0s
  Makefile
Labels: type::bug, bug::normal

#836 chore: add an e2e test with 5 airgapped nodes
  .github/workflows/ci.yaml
  e2e/install_test.go
Labels: type::chore

#897 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#896 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.yaml
Labels: type::chore, automated-pr

#904 Use a different user/PAT for creating PRs
  .github/workflows/dependencies.yaml
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
Labels: type::chore

#903 fix: make git sha match commit
  .github/actions/e2e/action.yml
  .github/actions/git-sha/action.yml
  .github/workflows/ci.yaml
Labels: type::chore

#898 chore(ci): add pre-upgrade k0s verison check to e2e tests
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  e2e/install_test.go
  e2e/restore_test.go
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
  e2e/utils.go
Labels: type::chore

#899 fix: use k0s kubectl
  Makefile
  cmd/embedded-cluster/metadata.go
  cmd/embedded-cluster/shell.go
  cmd/local-artifact-mirror/pull.go
  e2e/version_test.go
  pkg/goods/completion.go
  pkg/goods/materializer.go
  pkg/goods/static/compalias_bash.tmpl.sh
  pkg/versions/versions.go
Labels: type::bug, bug::normal
