Repository replicatedhq/embedded-cluster, pull requests merged in 2024-10, with the labels that each got.

#1255 Minor wording tweaks for consistency
  cmd/embedded-cluster/reset.go
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1263 Publish dev/test EC distros to dockerhub
  .github/workflows/distros.yaml
  Makefile
  dev/distros/Makefile
  dev/distros/README.md
Labels: type::chore

#1264 build arm64 distro images
  .github/workflows/distros.yaml
  dev/distros/Makefile
Labels: type::chore

#1266 chore: make preflight pass on arm64
  cmd/embedded-cluster/install.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/template.go
Labels: type::chore

#1261 fix: upgrade k0s version and fix registry upgrade with helm upgrade --force=false
  Makefile
  go.mod
  go.sum
  kinds/apis/v1beta1/config_types.go
  kinds/apis/v1beta1/zz_generated.deepcopy.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  operator/pkg/charts/charts.go
  operator/pkg/charts/charts_test.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/velero.go
  pkg/config/static/metadata.yaml
  scripts/ci-upload-binaries.sh
Labels: type::bug, bug::normal

#1268 fix(ci): wrong 1.28 version, thanks ai...
  Makefile
  scripts/ci-upload-binaries.sh
Labels: type::chore

#1269 fix(ci): indicate patched k0s with ec suffix
  Makefile
Labels: type::bug, bug::normal

#1271 install expect package in dev/test images
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Labels: type::chore

#1270 fix(ci): retry failure to get latest fio version
  Makefile
Labels: type::chore

#1272 Add centos-9 and debian-bullseye distros
  dev/distros/dockerfiles/centos-9.Dockerfile
  dev/distros/dockerfiles/debian-bullseye.Dockerfile
Labels: type::chore

#1273 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1258 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1257 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1275 chore: bump troubleshoot version
  Makefile
Labels: type::chore

#1262 fix: validate admin console password length
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/install_test.go
Labels: type::bug, bug::normal

#1267 K0s 1 28 14
  .github/workflows/distros.yaml
  Makefile
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/install_test.go
  cmd/embedded-cluster/reset.go
  dev/distros/Makefile
  dev/distros/README.md
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
  go.mod
  go.sum
  kinds/apis/v1beta1/config_types.go
  kinds/apis/v1beta1/zz_generated.deepcopy.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  operator/controllers/installation_controller.go
  operator/pkg/charts/charts.go
  operator/pkg/charts/charts_test.go
  operator/pkg/metrics/metrics.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/velero.go
  pkg/config/static/metadata.yaml
  pkg/metrics/events.go
  pkg/metrics/reporter.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/template.go
  scripts/ci-upload-binaries.sh
Labels: type::chore

#1277 Add wget to utils image
  deploy/images/utils/apko.tmpl.yaml
Labels: type::chore

#1222 improve our upgrade architecture
  Makefile
  e2e/scripts/check-postupgrade-state.sh
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
  operator/controllers/installation_controller.go
  operator/controllers/installation_controller_test.go
  operator/pkg/artifacts/upgrade.go
  operator/pkg/charts/detection.go
  operator/pkg/charts/helm_test.go
  operator/pkg/charts/reconcile.go
  operator/pkg/charts/reconcile_test.go
  operator/pkg/cli/root.go
  operator/pkg/cli/upgrade-job.go
  operator/pkg/cli/upgrade.go
  operator/pkg/k8sutil/clusterVersion.go
  operator/pkg/k8sutil/clusterVersion_test.go
  operator/pkg/upgrade/autopilot.go
  operator/pkg/upgrade/installation.go
  operator/pkg/upgrade/job.go
  operator/pkg/upgrade/job_test.go
  operator/pkg/upgrade/upgrade.go
  pkg/kubeutils/kubeutils.go
  scripts/ci-build-bin.sh
Labels: type::feature

#1280 Mask systemd getty@tty1.service as it's flaky and doesn't apply in containers
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/centos-9.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/debian-bullseye.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Labels: type::chore

#1283 chore(ci): automate k0s patches
  .github/workflows/release-k0s-patch.yaml
Labels: type::chore

#1284 fix(ci): correct bucket for upload k0s binaries
  .github/workflows/release-k0s-patch.yaml
  Makefile
Labels: type::chore

#1291 feat: fix openebs log collector + adds log analyzer
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::feature

#1292 record events in the installation object
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml
  operator/controllers/installation_controller.go
  operator/pkg/charts/detection.go
  operator/pkg/charts/helm_test.go
  operator/pkg/charts/reconcile.go
  operator/pkg/charts/reconcile_test.go
  operator/pkg/cli/root.go
  operator/pkg/upgrade/upgrade.go
Labels: type::chore

#1296 run the daemonsets to collect k0s controller/worker logs in the embedded-cluster namespace
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
Labels: type::chore

#1298 do not overwrite existing custom k0s builds
  .github/workflows/release-k0s-patch.yaml
Labels: type::chore

#1297 feat: kinds ahead of overriding data dir feature
  kinds/apis/v1beta1/installation_types.go
  kinds/apis/v1beta1/installation_types_test.go
  kinds/apis/v1beta1/runtimeconfig_types.go
  kinds/apis/v1beta1/zz_generated.deepcopy.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  operator/schemas/config-embeddedcluster-v1beta1.json
Labels: type::feature

#1293 trim 'v' prefix from versions before checking skew
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/preflights.go
Labels: type::bug, bug::normal

#1300 Dev / testing: ensure a unique machine ID for each node
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/centos-9.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/debian-bullseye.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
  dev/distros/entrypoint.sh
  dev/distros/timesyncd-override.conf
Labels: type::chore

#1256 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1305 Disable unnecessary flaky systemd services
  dev/distros/entrypoint.sh
Labels: type::chore

#1308 feat: check if data-dir is a symlink
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1303 feat: keep custom k0s patches in the repo
  .github/workflows/release-k0s-patch.yaml
  k0s-patches/release-1.29/0001-fix-chart-crd-forceUpgrade-field-should-be-nil-by-de.patch
  k0s-patches/release-1.30/0001-revert-incompatible-helm-timeout-change.patch
Labels: type::feature

#1309 chore: fix missing quotes in aws command
  .github/workflows/release-k0s-patch.yaml
Labels: type::chore

#1311 Remove KUBECONFIG env var in distro images
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  dev/distros/dockerfiles/centos-9.Dockerfile
  dev/distros/dockerfiles/debian-bookworm.Dockerfile
  dev/distros/dockerfiles/debian-bullseye.Dockerfile
  dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Labels: type::chore

#1310 work on adding postrelease e2e testing
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  scripts/ci-embed-release.sh
  scripts/ci-release-app.sh
Labels: type::chore

#1315 github filter patterns are not quite regex
  .github/workflows/release-prod.yaml
Labels: type::chore

#1210 feat(preflights): add host dns wildcard check
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1319 Fix the k0scontroller and k0sworker logs collector
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
Labels: type::bug, bug::normal

#1325 remove wip postrelease testing
  .github/workflows/release-prod.yaml
Labels: type::chore

#1241 fix(ci): buildtools handle helm chart app version change
  cmd/buildtools/main.go
  cmd/buildtools/utils.go
  pkg/helm/client.go
  pkg/helm/images.go
Labels: type::chore

#1320 fix(k0s): images do not get updated on upgrades
  operator/pkg/cli/upgrade_job.go
  operator/pkg/upgrade/upgrade.go
Labels: type::bug, bug::normal

#1328 fix: install flake waiting for k0s
  cmd/embedded-cluster/install.go
  e2e/install_test.go
Labels: type::bug, bug::normal

#1312 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1330 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1339 bug: fix wrong link to upstream support bundle url
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::bug, bug::regression

#1340 collect local-artifact-mirror service logs
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
  pkg/goods/support/host-support-bundle.tmpl.yaml
Labels: type::chore

#1344 chore(makefile): fix the e2e single test execution
  Makefile
Labels: type::chore

#1324 feat: introduces a new `--cidr` command line flag
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/network.go
  cmd/embedded-cluster/preflights.go
  cmd/embedded-cluster/proxy.go
  cmd/embedded-cluster/proxy_test.go
  cmd/embedded-cluster/restore.go
  e2e/install_test.go
  go.mod
  go.sum
  kinds/apis/v1beta1/runtimeconfig_types.go
  pkg/netutils/nets.go
  pkg/netutils/nets_test.go
Labels: type::feature

#1326 Unhide air gap and alphabetize flags
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/reset.go
  cmd/embedded-cluster/restore.go
Labels: type::feature

#1341 fix: upgrades from versions prior to 1.15.0 have incorrect data directories
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  e2e/cluster/docker/cluster.go
  e2e/cluster/lxd/cluster.go
  e2e/install_test.go
  e2e/playwright/tests/get-ec18-join-worker-command/test.spec.ts
  e2e/scripts/common.sh
  e2e/scripts/reset-installation.sh
  operator/pkg/charts/charts.go
  operator/pkg/cli/upgrade.go
  operator/pkg/upgrade/installation.go
  operator/pkg/upgrade/job.go
  operator/pkg/upgrade/job_test.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/defaults/provider.go
  pkg/kubeutils/kubeutils.go
  pkg/kubeutils/kubeutils_test.go
Labels: type::bug, bug::regression

#1346 bug(seaweedfs): fix data path, add validation in e2e tests
  e2e/cluster/docker/cluster.go
  e2e/cluster/lxd/cluster.go
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/common.sh
  operator/pkg/charts/charts.go
  pkg/kubeutils/kubeutils.go
  pkg/kubeutils/kubeutils_test.go
Labels: type::bug, bug::regression

#1321 merge 'install' and 'upgrade' helm spec generation code
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/restore.go
  dev/dockerfiles/operator/Dockerfile.ttlsh
  e2e/cluster/lxd/cluster.go
  e2e/install_test.go
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/common.sh
  e2e/utils.go
  operator/Makefile
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
  operator/controllers/installation_controller.go
  operator/controllers/k0s.go
  operator/controllers/k0s_test.go
  operator/deploy/melange.tmpl.yaml
  operator/pkg/artifacts/upgrade_test.go
  operator/pkg/charts/charts.go
  operator/pkg/charts/charts_test.go
  operator/pkg/charts/reconcile.go
  operator/pkg/charts/reconcile_test.go
  operator/pkg/cli/root.go
  operator/pkg/cli/upgrade.go
  operator/pkg/cli/upgrade_job.go
  operator/pkg/cli/version.go
  operator/pkg/registry/seaweedfs.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/openebs/openebs.go
  pkg/addons/options.go
  pkg/addons/registry/registry.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/velero/velero.go
  pkg/helpers/snapshots.go
  pkg/highavailability/seaweed.go
  pkg/kubeutils/kubeutils.go
  pkg/metrics/reporter.go
  scripts/ci-upload-binaries.sh
Labels: type::chore

#1350 chore: unit test returned supernet
  e2e/install_test.go
  pkg/netutils/nets_test.go
Labels: type::chore

#1353 chore(ci): check pods not crashlooping in e2e tests
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/common.sh
Labels: type::chore

#1345 feat: add admin-console reset-password command
  cmd/embedded-cluster/admin_console.go
  cmd/embedded-cluster/k0s.go
  cmd/embedded-cluster/main.go
  e2e/install_test.go
  e2e/playwright/tests/login-with-custom-password/test.spec.ts
  e2e/playwright/tests/shared/login.ts
  e2e/scripts/playwright.sh
  pkg/helpers/command.go
  pkg/kotscli/kotscli.go
Labels: type::feature

#1356 fix: reset fails on worker nodes after an upgrade
  cmd/embedded-cluster/flags.go
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/materialize.go
  cmd/embedded-cluster/preflights.go
  cmd/embedded-cluster/provider.go
  cmd/embedded-cluster/restore.go
Labels: type::bug, bug::regression

#1357 chore(ci): improve airgap bundle download resilience in e2e tests with retry
  e2e/airgap.go
Labels: type::chore

#1359 fix(ci): avoid github rate limits
  .github/workflows/ci.yaml
  .github/workflows/dependencies.yaml
Labels: type::chore

#1276 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1332 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1250 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr

#1236 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1354 chore: simplify regex on e2e test
  e2e/install_test.go
Labels: type::chore

#1360 fix: worker reset fails with incorrect data directory
  cmd/embedded-cluster/provider.go
  cmd/embedded-cluster/reset.go
  cmd/embedded-cluster/shell.go
  pkg/defaults/provider.go
Labels: type::bug, bug::regression

#1362 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1351 feat: add support-bundle command
  cmd/embedded-cluster/main.go
  cmd/embedded-cluster/support_bundle.go
  e2e/scripts/validate-support-bundle.sh
  e2e/support-bundle_test.go
  pkg/helpers/command.go
Labels: type::feature

#1364 chore(ci): re-promote 1.8.0 release each time
  .github/workflows/ci.yaml
  e2e/install_test.go
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
Labels: type::chore

#1358 store runtime config in /etc/embedded-cluster/ec.yaml
  cmd/embedded-cluster/flags.go
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/join.go
  cmd/embedded-cluster/provider.go
  cmd/embedded-cluster/reset.go
  cmd/embedded-cluster/restore.go
  cmd/embedded-cluster/shell.go
  e2e/restore_test.go
  e2e/scripts/check-directory-empty.sh
  pkg/configutils/runtime.go
  pkg/defaults/defaults.go
  pkg/goods/support/host-support-bundle.tmpl.yaml
Labels: type::feature

#1366 Ignore .envrc for dev environment setup
  .gitignore
Labels: type::chore

#1307 feat(support-bundle): add runHostCollectorsInPod as host remote support bundle for kots
  .github/workflows/ci.yaml
  Makefile
  e2e/host-support-bundle_test.go
  e2e/install_test.go
  e2e/restore_test.go
  e2e/scripts/collect-support-bundle-host-in-cluster.sh
  go.mod
  go.sum
  operator/Makefile
  operator/pkg/upgrade/upgrade.go
  pkg/addons/applier.go
  pkg/goods/goods.go
  pkg/goods/support/host-support-bundle-remote.yaml
  pkg/kotscli/kotscli.go
Labels: type::feature

#1365 chore(ci): wait for app to deploy after upgrade
  e2e/scripts/check-postupgrade-state.sh
Labels: type::chore

#1372 instead of hardcoding values hashes in unit testing build them from the expected values
  operator/pkg/charts/reconcile_test.go
Labels: type::chore

#1367 fix operator binary metadata path
  operator/deploy/melange.tmpl.yaml
  operator/pkg/charts/charts.go
  operator/pkg/charts/charts_test.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
Labels: type::bug, bug::normal

#1374 Fix automated PRs manager detecting E2E CI jobs
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/ci.yaml
Labels: type::chore

#1375 Fix automated PRs manager detecting validate success branch protection job
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/ci.yaml
Labels: type::chore

#1361 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1368 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1369 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1355 feat(host-preflights): add cidr preflight checks
  cmd/embedded-cluster/install.go
  cmd/embedded-cluster/network.go
  cmd/embedded-cluster/network_test.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/template.go
  pkg/preflights/template_test.go
Labels: type::feature

#1352 chore: Collect LAM service config in support bundle
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-lam-service-config.yaml
  pkg/goods/support/host-support-bundle.tmpl.yaml
Labels: type::chore

#1377 fix mismatch between admin console and embedded cluster versions
  operator/deploy/melange.tmpl.yaml
  operator/pkg/charts/charts.go
  operator/pkg/charts/charts_test.go
Labels: type::chore

#1380 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1382 retry setting installation state on conflict
  operator/pkg/upgrade/installation.go
Labels: type::bug, bug::normal

#1389 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1390 update error message for repeated installation status failures
  operator/pkg/upgrade/installation.go
Labels: type::chore

#1387 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1392 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1393 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1386 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1391 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1370 chore: bump troubleshoot to allow optional cluster specs
  Makefile
  cmd/embedded-cluster/support_bundle.go
  pkg/goods/support/host-support-bundle-remote.yaml
Labels: type::chore

#1395 chore: improvements to support-bundle command
  cmd/embedded-cluster/support_bundle.go
Labels: type::chore

#1397 chore: stop using environment
  cmd/embedded-cluster/support_bundle.go
Labels: type::chore

#1396 chore: remove spurious printf
  pkg/kotscli/kotscli.go
Labels: type::chore

#1401 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1400 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1403 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1394 update some wording
  cmd/embedded-cluster/network.go
  cmd/embedded-cluster/proxy.go
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1406 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1407 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1413 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1411 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1318 feat: detect if a mitm proxy is being used in host preflights
  Makefile
  cmd/embedded-cluster/install.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/template.go
Labels: type::feature

#1414 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr

#1418 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1419 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1415 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1422 Update support bundle wording
  cmd/embedded-cluster/support_bundle.go
Labels: type::feature

#1423 Show password as argument in usage
  cmd/embedded-cluster/admin_console.go
Labels: type::feature

#1421 fix(preflights): panic on preflight warnings
  cmd/embedded-cluster/install.go
Labels: type::bug, bug::normal

#1425 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1426 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1429 chore(dev): allow rollback in dev environment
  e2e/cluster/lxd/cluster.go
  e2e/kots-release-install/kots-app.yaml
  e2e/kots-release-upgrade/kots-app.yaml
  go.mod
  go.sum
  pkg/airgap/testfiles/tiny-airgap-noimages-app/kots-app.yaml
  pkg/release/testdata/release.yaml
Labels: type::chore

#1434 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1432 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1435 Add additional namespaces for collection
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::feature

#1431 feat: update adminconsole version
  Makefile
  e2e/playwright/README.md
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/playwright/tests/get-restore-join-controller-command/test.spec.ts
  e2e/playwright/tests/shared/deploy-app.ts
  go.mod
  go.sum
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr
