Repository replicatedhq/embedded-cluster, pull requests merged in 2025-08, with the labels that each got.

#2610 Move app installation logic out of infrastructure setup
  api/controllers/app/install/apppreflight.go
  api/controllers/app/install/controller.go
  api/controllers/app/install/controller_mock.go
  api/controllers/app/install/install.go
  api/controllers/app/install/test_suite.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/kubernetes/install/controller_test.go
  api/controllers/kubernetes/install/infra.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_mock.go
  api/controllers/linux/install/controller_test.go
  api/controllers/linux/install/infra.go
  api/integration/kubernetes/install/infra_test.go
  api/integration/linux/install/infra_test.go
  api/internal/managers/app/install/install.go
  api/internal/managers/app/install/install_test.go
  api/internal/managers/app/install/manager.go
  api/internal/managers/app/install/mock.go
  api/internal/managers/kubernetes/infra/install.go
  api/internal/managers/kubernetes/infra/manager.go
  api/internal/managers/kubernetes/infra/manager_mock.go
  api/internal/managers/linux/infra/install.go
  api/internal/managers/linux/infra/install_test.go
  api/internal/managers/linux/infra/manager.go
  api/internal/managers/linux/infra/manager_mock.go
  api/internal/states/install/states.go
  cmd/installer/cli/install.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/update.go
  cmd/installer/goods/materializer.go
  cmd/installer/kotscli/kotscli.go
Labels: type::feature

#2611 bug: Fix label config item duplication
  e2e/kots-release-install-v3/config.yaml
Labels: type::bug, bug::normal

#2625 chore(deps): migrate to go aws sdk v2
  cmd/installer/cli/restore.go
  go.mod
  go.sum
Labels: type::chore

#2624 Create dedicated endpoints for app installation and status
  api/client/client.go
  api/client/client_test.go
  api/client/install.go
  api/controllers/app/install/controller.go
  api/controllers/app/install/controller_mock.go
  api/controllers/app/install/install.go
  api/controllers/app/install/test_suite.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/kubernetes/install/statemachine.go
  api/controllers/kubernetes/install/statemachine_test.go
  api/controllers/linux/install/controller_mock.go
  api/controllers/linux/install/statemachine.go
  api/controllers/linux/install/statemachine_test.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/internal/handlers/kubernetes/install.go
  api/internal/handlers/linux/install.go
  api/internal/managers/app/install/install.go
  api/internal/managers/app/install/install_test.go
  api/internal/managers/app/install/manager.go
  api/internal/managers/app/install/mock.go
  api/internal/managers/app/install/status.go
  api/internal/managers/app/install/util.go
  api/internal/managers/app/install/util_test.go
  api/internal/store/app/install/store.go
  api/internal/store/app/install/store_test.go
  api/routes.go
  api/types/app.go
Labels: type::feature

#2567 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2569 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2634 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2633 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2632 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2629 chore(ci): clean up account, archive old channel releases and instances
  .github/workflows/cleanup-resources.yaml
  scripts/archive-instances.sh
  scripts/demote-channel-releases.sh
Labels: type::chore

#2638 chore(ci): fix web unit test
  web/src/components/wizard/tests/LinuxValidationStep.test.tsx
Labels: type::chore

#2644 Add app installation phase tests
  web/src/components/wizard/installation/phases/AppInstallationPhase.tsx
  web/src/components/wizard/installation/phases/AppInstallationStatus.tsx
  web/src/components/wizard/installation/tests/AppInstallationPhase.test.tsx
  web/src/components/wizard/installation/tests/LinuxInstallationPhase.test.tsx
Labels: type::feature

#2654 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2659 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2635 fix(join): use local network interface and provided flag
  cmd/installer/cli/join.go
  pkg-new/config/network_interface.go
  pkg-new/config/network_interface_test.go
  pkg/dryrun/dryrun.go
  pkg/dryrun/network_interface.go
  pkg/netutils/ips.go
  pkg/netutils/ips_test.go
  tests/dryrun/join_test.go
Labels: type::bug, bug::regression

#2661 chore(ci): automate update k0s version dep
  .github/workflows/dependencies.yaml
  Makefile
  README.md
  cmd/buildtools/adminconsole.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/k0s.go
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/update.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  cmd/installer/cli/join.go
  operator/Makefile
  pkg-new/k0s/k0s_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  scripts/update-k0s-dep-version.sh
Labels: type::chore

#2665 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2660 chore(web): add netlify deploy preview
  .gitignore
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/types/status.go
  web/.gitignore
  web/README.md
  web/netlify.toml
  web/netlify/functions/api.ts
  web/package-lock.json
  web/package.json
  web/src/global.d.ts
  web/vite.config.ts
Labels: type::chore

#2641 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2666 chore: remove extra `/n`
  web/vite.config.ts
Labels: type::chore

#2639 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2667 fix(api): fix LicenseDockerCfg template function
  api/controllers/app/install/controller.go
  api/controllers/linux/install/controller_test.go
  api/integration/app/install/config_test.go
  api/internal/managers/linux/infra/install_test.go
Labels: type::feature

#2670 Update Makefile versions
  pkg/config/static/metadata.yaml
Labels: type::chore, automated-pr, makefile

#2673 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2674 chore(ci): move away from bitnami charts
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/common.sh
  hack/test-installation.yaml
Labels: type::chore

#2676 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2662 Add support for k0s 1.32
  .github/workflows/ci.yaml
  Makefile
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
  pkg/config/static/metadata.yaml
  scripts/update-k0s-dep-version.sh
Labels: type::feature

#2691 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2692 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2703 Update Claude agents and commands
  .claude/.manifest
  .claude/agents/architecture-patterns.md
  .claude/agents/codebase-analyzer.md
  .claude/agents/codebase-locator.md
  .claude/agents/codebase-pattern-finder.md
  .claude/agents/go-developer.md
  .claude/agents/proposal-needed.md
  .claude/agents/proposal-writer.md
  .claude/agents/proposals-analyzer.md
  .claude/agents/proposals-locator.md
  .claude/agents/researcher.md
  .claude/agents/shortcut.md
  .claude/agents/testing.md
  .claude/agents/web-search-researcher.md
  .claude/commands/implement.md
  .claude/commands/proposal.md
Labels: type::chore

#2701 Pin calico images to version 3.28.0 for k0s < 1.31
  cmd/buildtools/k0s.go
Labels: type::chore

#2706 Update Claude agents and commands
  .claude/.manifest
  .claude/agents/frontend-developer.md
  .claude/agents/proposal-writer.md
  .claude/commands/proposal.md
Labels: type::chore, claude-agent-sync

#2708 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2713 Update Makefile versions
  pkg/config/static/metadata.yaml
Labels: type::chore, automated-pr, makefile

#2714 Update Makefile versions
  pkg/config/static/metadata-1_32.yaml
Labels: type::chore, automated-pr, makefile

#2619 tests: add test that reports network events while deploying an EC app
  .github/workflows/ci.yaml
  e2e/cluster/cmx/cluster.go
  e2e/install_test.go
Labels: type::chore, type::tests

#2715 feat(v3): install Helm charts directly without KOTS CLI
  api/controllers/app/install/controller.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/linux/install/controller.go
  api/integration/kubernetes/install/appinstall_test.go
  api/integration/linux/install/appinstall_test.go
  api/internal/managers/app/install/install.go
  api/internal/managers/app/install/install_test.go
  api/internal/managers/app/install/manager.go
  api/internal/managers/app/install/status.go
  api/internal/managers/app/install/util.go
  api/internal/managers/app/release/template.go
  api/internal/managers/app/release/util.go
  proposals/helm_direct_install.md
  proposals/helm_direct_install_research.md
  proposals/v3_app_deployment_transition.md
Labels: type::feature

#2717 chore(ci): allow for specifying alternative image repo for dev env
  .gitignore
  Makefile
  local-artifact-mirror/Makefile
  operator/Makefile
  scripts/ci-build-deps.sh
  scripts/ci-upload-binaries.sh
Labels: type::chore

#2709 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2694 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2711 Add flag to ignore app preflights for V2 installs and update success message
  cmd/installer/cli/install.go
  cmd/installer/cli/install_test.go
  tests/dryrun/install_test.go
Labels: type::feature

#2718 chore: better error message for non-canonical cidr
  pkg/netutils/nets.go
  pkg/netutils/nets_test.go
Labels: type::chore

#2679 chore(ci): streamline k0s release process
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  .github/workflows/dependencies.yaml
  .github/workflows/image-deps-updater.yaml
  .github/workflows/release-prod.yaml
  Makefile
  README.md
  api/Makefile
  cmd/buildtools/k0s.go
  common.mk
  dagger/localartifactmirror.go
  dagger/main.go
  dagger/operator.go
  dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
  dev/dockerfiles/operator/Dockerfile.ttlsh
  e2e/install_test.go
  e2e/restore_test.go
  e2e/scripts/common.sh
  e2e/utils.go
  kinds/Makefile
  local-artifact-mirror/Makefile
  local-artifact-mirror/deploy/melange.tmpl.yaml
  operator/Makefile
  operator/deploy/melange.tmpl.yaml
  pkg/config/images.go
  pkg/config/images_test.go
  pkg/config/metadata.go
  pkg/config/static/metadata-1_29.yaml
  pkg/config/static/metadata-1_30.yaml
  pkg/config/static/metadata-1_31.yaml
  pkg/config/static/metadata-1_32.yaml
  pkg/config/static/metadata-1_33.yaml
  pkg/release/k0s.go
  scripts/ci-build-deps.sh
  scripts/ci-upload-binaries.sh
  scripts/k0s-update-dependencies.sh
  scripts/k0s-update-images.sh
  scripts/print-ec-version.sh
  scripts/update-k0s-dep-version.sh
  versions.mk
Labels: type::chore

#2720 Update go, go-getter, and troubleshoot
  dagger.json
  dagger/go.mod
  dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
  dev/dockerfiles/operator/Dockerfile.local
  dev/dockerfiles/operator/Dockerfile.ttlsh
  go.mod
  go.sum
  kinds/go.mod
  tests/dryrun/Dockerfile
  utils/go.mod
Labels: type::chore

#2742 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2743 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2750 feat(api): update app install status endpoint to return list of charts being installed
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/kubernetes/install/appinstall_test.go
  api/integration/linux/install/appinstall_test.go
  api/internal/managers/app/install/install.go
  api/internal/managers/app/install/install_test.go
  api/internal/managers/app/install/status.go
  api/internal/store/app/install/store.go
  api/internal/store/app/install/store_mock.go
  api/internal/store/app/install/store_test.go
  api/types/app.go
Labels: type::feature

#2754 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2751 fix(api): use correct helm client k8s version
  api/api.go
  api/controllers/app/install/controller.go
  api/controllers/app/install/test_suite.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_test.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_test.go
  api/handlers.go
  api/integration/app/install/config_test.go
  api/integration/auth/controller_test.go
  api/integration/console/controller_test.go
  api/integration/kubernetes/install/appconfig_test.go
  api/integration/kubernetes/install/appinstall_test.go
  api/integration/kubernetes/install/apppreflight_test.go
  api/integration/kubernetes/install/infra_test.go
  api/integration/kubernetes/install/installation_test.go
  api/integration/linux/install/appconfig_test.go
  api/integration/linux/install/appinstall_test.go
  api/integration/linux/install/apppreflight_test.go
  api/integration/linux/install/hostpreflight_test.go
  api/integration/linux/install/infra_test.go
  api/integration/linux/install/installation_test.go
  api/integration/util.go
  api/internal/clients/kube.go
  api/internal/clients/kube_test.go
  api/internal/handlers/kubernetes/kubernetes.go
  api/internal/handlers/kubernetes/util.go
  api/internal/managers/app/install/install_test.go
  api/internal/managers/app/install/manager.go
  api/internal/managers/app/install/util.go
  api/internal/managers/app/release/manager.go
  api/internal/managers/app/release/template.go
  api/internal/managers/app/release/template_test.go
  api/internal/managers/app/release/util.go
  api/internal/managers/linux/infra/util.go
  api/types/api.go
  cmd/buildtools/metadata.go
  cmd/buildtools/utils.go
  cmd/installer/cli/api.go
  cmd/installer/cli/api_test.go
  cmd/installer/cli/enable_ha.go
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/restore.go
  operator/pkg/cli/upgrade_job.go
  pkg/helm/client.go
Labels: type::feature

#2760 feat(v3): rely on kots to process the app airgap bundle and create the image pull secrets
  api/internal/managers/app/install/install.go
  api/internal/managers/app/install/install_test.go
Labels: type::feature

#2755 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2766 fix(web): code block rendering in markdown
  web/src/components/common/HelpText.tsx
  web/src/components/common/Label.tsx
  web/src/components/common/Markdown.tsx
Labels: type::bug, bug::normal

#2767 fix(v3): names of uploaded files are not displayed correctly
  api/pkg/template/config.go
  api/pkg/template/config_test.go
  api/pkg/template/execute_test.go
  e2e/kots-release-install-v3/config.yaml
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
  web/src/types/index.ts
  web/static.go
Labels: type::feature

#2769 feat(v3): update the app installation page to show charts being installed with progress
  api/internal/managers/app/install/install.go
  api/internal/managers/app/install/util.go
  e2e/kots-release-install-v3/nginx-app-helm-v1beta2.yaml
  web/src/components/wizard/installation/phases/AppInstallationPhase.tsx
  web/src/components/wizard/installation/tests/AppInstallationPhase.test.tsx
  web/src/types/index.ts
Labels: type::feature
