Repository replicatedhq/embedded-cluster, pull requests merged in 2025-04, with the labels that each got.

#2056 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2057 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2058 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2059 fix(adminconsole): loads old ui after upgrade
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::bug, bug::normal

#2060 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2061 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2062 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2064 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2065 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2039 ensure that images can be pulled via a MITM proxy in preflight checks
  e2e/proxy_test.go
  e2e/scripts/check-preflights-fail.sh
  pkg/preflights/host-preflight.yaml
Labels: type::chore

#2068 feat: add control plane node affinity for upgrade job
  operator/pkg/upgrade/job.go
  operator/pkg/upgrade/job_test.go
Labels: type::bug, bug::normal

#2069 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2070 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2075 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2081 add retries to leaveEtcdcluster
  cmd/installer/cli/reset.go
Labels: type::chore

#2080 feat: handle ctrl+c in reporting
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/signal.go
  cmd/installer/cli/signal_test.go
Labels: type::chore

#2084 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2085 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2086 [bug] don't set profiles flag if no profiles
  e2e/kots-release-unsupported-overrides/cluster-config.yaml
  e2e/scripts/unsupported-overrides.sh
  pkg/config/config.go
  pkg/config/config_test.go
Labels: type::bug, bug::regression

#2087 use ubuntu-latest not ubuntu-20.04
  .github/workflows/ci.yaml
  .github/workflows/image-deps-updater.yaml
  .github/workflows/release-prod.yaml
Labels: type::chore

#2091 sort the node role labels to make tests consistent
  pkg/config/config.go
Labels: type::chore

#2093 fix: ctrl+c handler should not report failure event
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/metrics.go
  cmd/installer/cli/signal.go
  cmd/installer/cli/signal_test.go
  pkg/metrics/reporter.go
  pkg/metrics/types/types.go
Labels: type::chore

#2095 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2082 St0rmz1/chore/grype migration
  .github/actions/scan-image/action.yml
  .github/workflows/image-scan.yaml
  .grype.yaml
Labels: type::chore

#2088 don't error on reset when nothing was wrong, continued
  cmd/installer/cli/reset.go
Labels: type::chore

#2025 feat: [sc-121571] respect env vars for http proxy, https proxy, and no proxy
  cmd/installer/cli/proxy.go
  cmd/installer/cli/proxy_test.go
  e2e/restore_test.go
  e2e/scripts/restore-installation-airgap.exp
  e2e/scripts/restore-multi-node-airgap-phase1.exp
  e2e/scripts/restore-multi-node-airgap-phase2.exp
Labels: type::feature

#2096 chore(metrics): add execution data and code cleanup
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/metrics.go
  cmd/installer/cli/metrics_test.go
  pkg/metrics/reporter.go
  pkg/metrics/reporter_test.go
  pkg/metrics/sender.go
  pkg/metrics/sender_test.go
  pkg/metrics/types/types.go
  pkg/preflights/run.go
  tests/dryrun/install_test.go
  tests/dryrun/join_test.go
Labels: type::chore

#2100 chore: update go to 1.24.1
  go.mod
  kinds/go.mod
  tests/dryrun/Dockerfile
  utils/go.mod
Labels: type::chore

#2102 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2103 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2094 fix: handle ctrl+c in prompts
  cmd/installer/cli/adminconsole_resetpassword.go
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/restore.go
  pkg/preflights/run.go
  pkg/prompts/decorative/decorative.go
  pkg/prompts/plain/plain.go
  pkg/prompts/prompts.go
Labels: type::chore

#2101 update helm and containerd
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
Labels: type::chore

#2090 fix and test joining nodes with worker profiles after upgrading from previous EC versions
  e2e/install_test.go
  operator/pkg/upgrade/upgrade.go
  operator/pkg/upgrade/upgrade_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/extract-respect-immutable-fields.yaml
  pkg/config/testdata/override-respect-immutable-fields.yaml
  pkg/k0s/install.go
Labels: type::chore

#2106 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2097 Respect the EC multi-node license option
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  Makefile
  README.md
  cmd/buildtools/adminconsole.go
  cmd/buildtools/utils.go
  cmd/installer/cli/enable_ha.go
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/restore.go
  e2e/host-support-bundle_test.go
  e2e/install_test.go
  e2e/licenses/airgap-license.yaml
  e2e/licenses/airgap-snapshot-license.yaml
  e2e/licenses/license.yaml
  e2e/licenses/multi-node-disabled-license.yaml
  e2e/licenses/snapshot-license.yaml
  e2e/local-artifact-mirror_test.go
  e2e/playwright/tests/shared/deploy-app.ts
  e2e/preflights_test.go
  e2e/proxy_test.go
  e2e/reset_test.go
  e2e/restore_test.go
  e2e/scripts/playwright.sh
  e2e/shared.go
  e2e/sudo_test.go
  e2e/support-bundle_test.go
  e2e/unsupported-overrides_test.go
  go.mod
  go.sum
  kinds/apis/v1beta1/installation_types.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/values.go
  pkg/addons/highavailability.go
  pkg/addons/install.go
  pkg/addons/upgrade.go
  scripts/ci-upload-binaries.sh
  tests/dryrun/assets/install-license.yaml
  tests/dryrun/install_test.go
  tests/integration/kind/registry/ha_test.go
Labels: type::feature

#2119 Fix replicated-sdk chart image name
  e2e/helm-charts/nginx-app/Chart.lock
  e2e/kots-release-install-failing-preflights/nginx-app-helm-v1beta2.yaml
  e2e/kots-release-install-legacydr/nginx-app-helm-v1beta2.yaml
  e2e/kots-release-install-stable/nginx-app-helm-v1beta2.yaml
  e2e/kots-release-install-warning-preflights/nginx-app-helm-v1beta2.yaml
  e2e/kots-release-install/nginx-app-helm-v1beta2.yaml
  e2e/kots-release-unsupported-overrides/nginx-app-helm-v1beta2.yaml
  e2e/kots-release-upgrade/nginx-app-helm-v1beta2.yaml
Labels: type::chore

#2118 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2112 feat: Enforce that the application version matches when joining nodes to the cluster
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  go.mod
  kinds/go.mod
  kinds/go.sum
  kinds/types/join/testdata/join-command-response-empty-overrides.yaml
  kinds/types/join/testdata/join-command-response-multiple-port-overrides.yaml
  kinds/types/join/testdata/join-command-response-multiple-unused-overlays.yaml
  kinds/types/join/testdata/join-command-response-no-overrides.yaml
  kinds/types/join/testdata/join-command-response-override-ports.yaml
  kinds/types/join/testdata/join-command-response-storage-and-port-overrides.yaml
  kinds/types/join/types.go
  kinds/types/join/types_test.go
  pkg/dryrun/kotsadm.go
  pkg/kotsadm/client.go
  pkg/kotsadm/interface.go
  tests/dryrun/join_test.go
Labels: type::feature

#2116 feat: generate controller join commands from the CLI
  cmd/installer/cli/join.go
  cmd/installer/cli/join_printcommand.go
  cmd/installer/kotscli/kotscli.go
  e2e/install_test.go
  e2e/scripts/check-node-join-command.sh
  e2e/scripts/common.sh
  e2e/shared.go
Labels: type::feature

#2104 chore: cli reset-password command should use cobra validation
  cmd/installer/cli/adminconsole_resetpassword.go
Labels: type::chore

#2099 chore: lam improvements
  cmd/local-artifact-mirror/artifact.go
  cmd/local-artifact-mirror/cli.go
  cmd/local-artifact-mirror/main.go
  cmd/local-artifact-mirror/pull.go
  cmd/local-artifact-mirror/pull_binaries.go
  cmd/local-artifact-mirror/pull_helmcharts.go
  cmd/local-artifact-mirror/pull_images.go
  cmd/local-artifact-mirror/pull_images_test.go
  cmd/local-artifact-mirror/root.go
  cmd/local-artifact-mirror/serve.go
  cmd/local-artifact-mirror/serve_test.go
  cmd/local-artifact-mirror/testing.go
  e2e/install_test.go
  pkg/helpers/fs.go
  pkg/kubeutils/installation.go
Labels: type::chore

#2120 E2E tests refactoring and cleanup
  e2e/install_test.go
  e2e/restore_test.go
  e2e/shared.go
  e2e/unsupported-overrides_test.go
Labels: type::chore

#2122 feat(lam): support for pull binaries command in online mode
  cmd/local-artifact-mirror/main.go
  cmd/local-artifact-mirror/pull.go
  cmd/local-artifact-mirror/pull_binaries.go
  cmd/local-artifact-mirror/pull_binaries_test.go
  cmd/local-artifact-mirror/pull_helmcharts.go
  cmd/local-artifact-mirror/pull_images.go
  cmd/local-artifact-mirror/pull_images_test.go
  operator/pkg/artifacts/upgrade.go
Labels: type::feature

#2123 Mount the EC data directory into the kots deployment
  pkg/addons/adminconsole/values.go
  tests/dryrun/install_test.go
Labels: type::feature

#2121 update troubleshoot to v0.119.0
  Makefile
  go.mod
  go.sum
Labels: type::chore

#2125 Install extension on upgrade if doesn't exist
  dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
  pkg/extensions/upgrade.go
  pkg/extensions/upgrade_test.go
Labels: type::feature, type::improvement

#2126 Mount the k0s data directory into the kots deployment
  pkg/addons/adminconsole/values.go
  tests/dryrun/install_test.go
Labels: type::feature

#2098 Refresh install CLI output
  README.md
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/shell.go
  cmd/installer/cli/supportbundle.go
  cmd/installer/kotscli/kotscli.go
  e2e/install_test.go
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/join-ha.exp
  e2e/scripts/pre-minio-removal-install.sh
  e2e/scripts/restore-installation-airgap.exp
  e2e/scripts/restore-installation.exp
  e2e/scripts/restore-multi-node-airgap-phase1.exp
  e2e/scripts/restore-multi-node-phase1.exp
  e2e/scripts/resume-restore.exp
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/single-node-host-preflight-install.sh
  e2e/scripts/single-node-install.sh
  e2e/scripts/unsupported-overrides.sh
  pkg/addons/install.go
  pkg/addons/upgrade.go
  pkg/extensions/install.go
  pkg/extensions/upgrade.go
  pkg/preflights/run.go
  pkg/spinner/options.go
  pkg/spinner/spinner.go
  pkg/spinner/spinner_test.go
Labels: type::feature

#2124 feat(multinode): online distribute artifacts on upgrade
  cmd/installer/cli/install.go
  cmd/installer/cli/metrics.go
  cmd/local-artifact-mirror/pull_binaries.go
  cmd/local-artifact-mirror/pull_binaries_test.go
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/proxy_test.go
  e2e/version_test.go
  operator/charts/embedded-cluster-operator/values.yaml
  operator/charts/embedded-cluster-operator/values.yaml.tmpl
  operator/pkg/artifacts/upgrade.go
  operator/pkg/artifacts/upgrade_test.go
  operator/pkg/cli/upgrade.go
  operator/pkg/cli/upgrade_job.go
  operator/pkg/metadata/metadata.go
  operator/pkg/upgrade/job.go
  operator/pkg/upgrade/job_test.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons/adminconsole/install.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/install.go
  pkg/addons/embeddedclusteroperator/install_test.go
  pkg/addons/embeddedclusteroperator/upgrade.go
  pkg/addons/embeddedclusteroperator/upgrade_test.go
  pkg/addons/embeddedclusteroperator/values.go
  pkg/addons/install.go
  pkg/addons/install_test.go
  pkg/addons/upgrade.go
  pkg/addons/upgrade_test.go
  pkg/helpers/snapshots.go
  pkg/kubeutils/installation.go
  pkg/kubeutils/installation_test.go
  pkg/kubeutils/kubeutils_test.go
  pkg/metrics/reporter.go
  pkg/metrics/reporter_test.go
  tests/integration/kind/registry/ha_test.go
  tests/integration/util/io.go
Labels: type::feature

#2132 Fix updating velero addon
  cmd/buildtools/velero.go
Labels: type::chore

#2128 fix: join should use same logic as install to determine network interface if unspecified
  cmd/installer/cli/join.go
  pkg/dryrun/kotsadm.go
  pkg/kotsadm/client.go
  pkg/kotsadm/interface.go
Labels: type::bug, bug::normal

#2130 use save_image_name in sarif upload category
  .github/actions/scan-image/action.yml
Labels: type::chore

#2129 preflight pass wording and enable HA by default
  cmd/installer/cli/join.go
  pkg/preflights/run.go
Labels: type::feature

#2131 Get charts and k0s images from KOTS and deprecate airgap bundle flag for node joins
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
  dev/dockerfiles/operator/Dockerfile.local
  dev/dockerfiles/operator/Dockerfile.ttlsh
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/airgap/materialize.go
  pkg/dryrun/kotsadm.go
  pkg/kotsadm/client.go
  pkg/kotsadm/interface.go
  tests/dryrun/Dockerfile
  tests/dryrun/join_test.go
  tests/dryrun/util.go
Labels: type::feature

#2134 chore: close gzip readers
  pkg/airgap/materialize.go
  pkg/airgap/version.go
  pkg/tgzutils/tgz.go
Labels: type::chore

#2034 improve cli help text
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/shell.go
  cmd/installer/cli/supportbundle.go
  cmd/installer/cli/update.go
Labels: type::feature
