Repository replicatedhq/embedded-cluster, pull requests merged in 2025-06, with the labels that each got.

#2217 feat(seaweedfs): update addon
  api/types/errors.go
  deploy/images/seaweedfs/apko.tmpl.yaml
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::feature

#2231 Bump e2e test timeouts to 70m
  Makefile
Labels: type::chore

#2230 chore(local-dev): gitgnore and operator makefile improvements
  .gitignore
  operator/Makefile
Labels: type::chore

#2232 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#2227 chore: add additional security tools check in support bundle
  cmd/installer/goods/support/host-support-bundle.tmpl.yaml
Labels: type::chore

#2233 chore(web): fix local web dev
  web/static.go
  web/static_test.go
Labels: type::chore

#2241 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2243 Increase preflight checks timeout on upgrade
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
Labels: type::chore

#2239 Set SSL Cert ConfigMap in KOTS and Improve Detection of Unhealthy Pods in Tests
  e2e/install_test.go
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/common.sh
  pkg/addons/adminconsole/static/values.tpl.yaml
  pkg/addons/adminconsole/values.go
  tests/dryrun/install_test.go
Labels: type::feature

#2250 Increase preflight initial load timeout on upgrade
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
Labels: type::chore

#2251 Wait for SSH to be available on CMX node
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2252 Log stdout and stderr if ssh isn't available
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2246 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2255 Address feedback from new API preflights PR
  api/api.go
  api/controllers/install/installation.go
  api/internal/managers/installation/store.go
  api/internal/managers/preflight/hostpreflight.go
  cmd/installer/cli/api.go
  cmd/installer/cli/api_test.go
  cmd/installer/cli/install.go
  operator/charts/embedded-cluster-operator/Chart.yaml
  pkg/helpers/fs_test.go
Labels: type::feature

#2257 feat: update registry version
  pkg/addons/registry/static/metadata.yaml
Labels: type::chore, automated-pr

#2262 Fix upgrade flakiness upon LAM restart
  operator/pkg/artifacts/upgrade.go
Labels: type::bug, bug::normal

#2264 chore(ci): fix flakey test TestConfigureInstallation
  api/integration/install_test.go
Labels: type::chore

#2258 Improvements to manager preflights UI
  web/src/components/wizard/ValidationStep.tsx
  web/src/components/wizard/preflight/LinuxPreflightCheck.tsx
  web/src/components/wizard/tests/LinuxPreflightCheck.test.tsx
  web/src/components/wizard/tests/SetupStep.test.tsx
  web/src/contexts/ConfigContext.tsx
  web/src/test/setup.tsx
Labels: type::feature

#2266 chore(ci): add pacakge-ecosystem npm for web and playwright directories
  .github/dependabot.yml
Labels: type::security

#2276 Create an interface for the addons package
  cmd/installer/cli/enable_ha.go
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/restore.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons/highavailability.go
  pkg/addons/highavailability_test.go
  pkg/addons/install.go
  pkg/addons/install_test.go
  pkg/addons/interface.go
  pkg/addons/mock.go
  pkg/addons/upgrade.go
  pkg/addons/upgrade_test.go
  pkg/addons/util.go
  pkg/addons/util_test.go
  pkg/dryrun/dryrun.go
  pkg/dryrun/kubeutils.go
  pkg/dryrun/types/types.go
  pkg/kubeutils/client.go
  pkg/kubeutils/interface.go
  tests/integration/kind/registry/ha_test.go
Labels: type::feature

#2278 chore(ci): fix flakey test TestRegistry_EnableHAAirgap
  pkg/addons/registry/migrate/pod.go
  pkg/dryrun/kubeutils.go
  pkg/kubeutils/interface.go
  pkg/kubeutils/kubeutils.go
  pkg/kubeutils/kubeutils_test.go
Labels: type::chore

#2226 chore(test): add tests to memory store
  Makefile
  api/Makefile
  api/integration/install_test.go
  api/internal/managers/installation/store_test.go
  cmd/installer/cli/signal_test.go
Labels: type::chore

#2279 Create an interface for the k0s package
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/restore.go
  pkg-new/hostutils/interface.go
  pkg-new/hostutils/mock.go
  pkg-new/hostutils/system.go
  pkg-new/k0s/interface.go
  pkg-new/k0s/k0s.go
  pkg-new/k0s/k0s_test.go
  pkg-new/k0s/mock.go
  pkg-new/k0s/testdata/patch-k0s-config-change-external-address.yaml
  pkg-new/k0s/testdata/patch-k0s-config-change-sans.yaml
  pkg-new/k0s/testdata/patch-k0s-config-extra-args.yaml
  pkg-new/k0s/testdata/patch-k0s-config-k0s-storage.yaml
  pkg-new/k0s/testdata/patch-k0s-config-no-embedded-cluster-config.yaml
  pkg-new/k0s/testdata/patch-k0s-config-no-overrides.yaml
  pkg/dryrun/dryrun.go
  pkg/dryrun/k0s.go
  pkg/k0s/client.go
  pkg/runtimeconfig/util/util.go
  tests/dryrun/update_test.go
  tests/integration/.k0s/install_test.go
Labels: type::feature

#2277 feat(ui): show install errors in the ui
  cmd/installer/cli/api.go
  cmd/installer/cli/install.go
  web/src/components/wizard/InstallationStep.tsx
Labels: type::feature

#2244 Fix "new version available" prompt appearing after manager experience URL
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
Labels: type::bug, bug::normal

#2290 bug: Remove lastUpdated timestamp and change CheckCircle icon color
  web/src/components/wizard/InstallationStep.tsx
Labels: type::bug, bug::normal

#2303 chore(test): actually wait for the os exit signal function to be called before asserting
  cmd/installer/cli/signal_test.go
Labels: type::chore

#2301 chore: pkg-new cloudutils.TryDiscoverPublicIP
  cmd/installer/cli/api.go
  cmd/installer/cli/install.go
  pkg-new/cloudutils/cloudutils.go
  pkg-new/cloudutils/interface.go
  pkg-new/cloudutils/mock.go
  pkg-new/cloudutils/publicip.go
  pkg-new/cloudutils/publicip_test.go
  pkg/netutils/ips.go
  pkg/netutils/ips_test.go
Labels: type::chore

#2309 Fix 401 bug
  web/src/components/wizard/SetupStep.tsx
  web/src/contexts/AuthContext.tsx
Labels: type::bug, bug::regression

#2310 Remove Back button from Setup page
  web/src/components/wizard/SetupStep.tsx
Labels: type::feature

#2311 Collapse advanced settings by default
  web/src/components/wizard/SetupStep.tsx
  web/src/components/wizard/tests/SetupStep.test.tsx
Labels: type::feature

#2313 prompt if manager will use self-signed cert
  api/integration/install_test.go
  cmd/installer/cli/install.go
Labels: type::feature

#2319 fix(openebs): disable loki components
  pkg/addons/openebs/static/values.tpl.yaml
Labels: type::chore

#2327 feat(ui): hide validation from install wizard navigation
  web/src/components/wizard/StepNavigation.tsx
  web/src/components/wizard/tests/StepNavigation.test.tsx
Labels: type::feature

#2329 chore: runtime config as argument
  api/client/install.go
  api/controllers/install/controller.go
  api/controllers/install/controller_test.go
  api/controllers/install/hostpreflight.go
  api/controllers/install/infra.go
  api/controllers/install/installation.go
  api/integration/hostpreflights_test.go
  api/integration/install_test.go
  api/internal/managers/infra/install.go
  api/internal/managers/infra/manager.go
  api/internal/managers/infra/manager_mock.go
  api/internal/managers/infra/util.go
  api/internal/managers/installation/config.go
  api/internal/managers/installation/config_test.go
  api/internal/managers/installation/manager.go
  api/internal/managers/installation/manager_mock.go
  api/internal/managers/preflight/hostpreflight.go
  api/internal/managers/preflight/hostpreflight_test.go
  api/internal/managers/preflight/manager.go
  api/internal/managers/preflight/manager_mock.go
  cmd/installer/cli/install.go
  pkg-new/k0s/k0s.go
  pkg/dryrun/k0s.go
Labels: type::chore

#2340 Some API cleanup
  api/client/client_test.go
  api/integration/auth_controller_test.go
  api/integration/install_test.go
  api/internal/managers/installation/config_test.go
  api/internal/managers/installation/status_test.go
  api/internal/store/infra/store.go
  api/internal/store/infra/store_test.go
  api/internal/store/installation/store.go
  api/internal/store/installation/store_test.go
  api/internal/store/preflight/store.go
  api/internal/store/preflight/store_test.go
  api/internal/store/store.go
Labels: type::feature

#2338 feat: add preflight to check for XFS filesystem with ftype=0
  pkg-new/preflights/host-preflight.yaml
Labels: type::feature

#2347 fix(e2e): Set sshArgs to mostly defaults
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2362 chore: validate state machine lock in tests
  api/controllers/install/controller_test.go
  api/internal/statemachine/statemachine.go
  api/internal/statemachine/statemachine_test.go
Labels: type::chore

#2335 feat: allow users to bypass host preflights in install wizard
  api/api.go
  api/controllers/install/controller.go
  api/controllers/install/controller_test.go
  api/controllers/install/infra.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/install.go
  api/integration/hostpreflights_test.go
  api/integration/install_test.go
  api/types/errors.go
  api/types/infra.go
  api/types/preflight.go
  api/types/responses.go
  cmd/installer/cli/api.go
  cmd/installer/cli/install.go
  web/src/components/common/Modal.tsx
  web/src/components/wizard/ValidationStep.tsx
  web/src/components/wizard/preflight/LinuxPreflightCheck.tsx
  web/src/components/wizard/tests/LinuxPreflightCheck.test.tsx
  web/src/components/wizard/tests/ValidationStep.test.tsx
Labels: type::feature

#2366 Unexport certain API types and functions
  api/api.go
  api/handlers.go
  api/routes.go
Labels: type::feature

#2367 Introduce KubernetesInstallation Type
  kinds/apis/v1beta1/kubernetes_installation_types.go
  kinds/apis/v1beta1/zz_generated.deepcopy.go
  pkg/kubernetesinstallation/installation.go
  pkg/kubernetesinstallation/interface.go
  pkg/kubernetesinstallation/mock.go
Labels: type::feature

#2368 chore(api): utils package should be internal
  api/controllers/console/controller.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/hostpreflight.go
  api/integration/auth_controller_test.go
  api/integration/console_test.go
  api/integration/install_test.go
  api/internal/managers/infra/install.go
  api/internal/managers/installation/config_test.go
  api/internal/managers/installation/manager.go
  api/internal/managers/preflight/hostpreflight_test.go
  api/internal/managers/preflight/manager.go
  api/internal/utils/domains.go
  api/internal/utils/netutils.go
  api/internal/utils/netutils_mock.go
Labels: type::chore

#2369 chore(web): text on welcome string reflects install target
  Makefile
  cmd/installer/cli/api.go
  cmd/installer/cli/install.go
  web/src/components/wizard/setup/LinuxSetup.tsx
  web/src/components/wizard/tests/SetupStep.test.tsx
  web/src/contexts/ConfigContext.tsx
  web/src/contexts/WizardModeContext.tsx
  web/src/global.d.ts
  web/src/test/setup.tsx
  web/src/test/testData.ts
  web/static.go
Labels: type::feature

#2363 chore: add statemachine event handlers
  api/internal/statemachine/event_handler.go
  api/internal/statemachine/interface.go
  api/internal/statemachine/statemachine.go
  api/internal/statemachine/statemachine_test.go
Labels: type::chore

#2371 feat(v3): customize install command help output based on targets
  cmd/installer/cli/cidr.go
  cmd/installer/cli/cidr_test.go
  cmd/installer/cli/flags.go
  cmd/installer/cli/install.go
  cmd/installer/cli/proxy_test.go
Labels: type::feature

#2374 feat(kubernetes): support for kubeconfig flag and from env
  cmd/installer/cli/cidr.go
  cmd/installer/cli/cidr_test.go
  cmd/installer/cli/flags.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/proxy.go
  cmd/installer/cli/proxy_test.go
  cmd/installer/cli/restore.go
Labels: type::feature

#2370 feat(ui): show modal when frontend loses connection to backend
  web/src/App.tsx
  web/src/components/common/ConnectionMonitor.tsx
  web/src/components/common/tests/ConnectionMonitor.test.tsx
Labels: type::feature

#2375 chore(api): export and document for more clear interface
  api/api.go
  api/controllers/linux/install/hostpreflight.go
  api/handlers.go
  api/routes.go
Labels: type::chore

#2337 feat(reporting): add metrics reporting to the new manager experience
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_test.go
  api/controllers/linux/install/hostpreflight.go
  api/controllers/linux/install/infra.go
  api/controllers/linux/install/installation.go
  api/controllers/linux/install/reporting_handlers.go
  api/controllers/linux/install/statemachine.go
  api/controllers/linux/install/statemachine_test.go
  api/integration/install_test.go
  api/internal/managers/preflight/hostpreflight.go
  api/internal/managers/preflight/hostpreflight_test.go
  api/internal/managers/preflight/manager.go
  api/internal/store/store_mock.go
  cmd/installer/cli/install.go
  pkg/metrics/reporter_mock.go
Labels: type::feature

#2377 chore(test): fix web unit test flake
  web/src/components/wizard/tests/ValidationStep.test.tsx
Labels: type::chore

#2379 bug: Use app slug in cli help menu
  cmd/installer/main.go
Labels: type::bug, bug::normal

#2381 chore(ci): fix unit test race condition
  api/controllers/linux/install/controller_test.go
Labels: type::chore

#2364 Adds a secret skip preflight environment variable
  cmd/installer/cli/install.go
  cmd/installer/cli/install_test.go
Labels: type::feature, type::improvement
