Repository replicatedhq/embedded-cluster, pull requests merged in 2025-02, with the labels that each got.

#1783 chore(v2): e2e test multiple upgrades
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  dev/dockerfiles/operator/Dockerfile.ttlsh
  e2e/cluster/lxd/cluster.go
  e2e/install_test.go
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/scripts/airgap-prepare.sh
  e2e/scripts/airgap-update2.sh
  e2e/scripts/common.sh
  e2e/scripts/install-kots-cli.sh
Labels: type::feature

#1792 feat(v2): upgrade job support bundle
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::feature

#1787 fix TestHostPreflightCustomSpec and TestUnsupportedOverrides
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  e2e/install_test.go
  e2e/kots-release-install-failing-preflights/backup.yaml
  e2e/kots-release-install-failing-preflights/cluster-config.yaml
  e2e/kots-release-install-failing-preflights/config.yaml
  e2e/kots-release-install-failing-preflights/deployment-2.yaml
  e2e/kots-release-install-failing-preflights/deployment.yaml
  e2e/kots-release-install-failing-preflights/failing-preflights.yaml
  e2e/kots-release-install-failing-preflights/k8s-app.yaml
  e2e/kots-release-install-failing-preflights/kots-app.yaml
  e2e/kots-release-install-failing-preflights/kots-lint-config.yaml
  e2e/kots-release-install-failing-preflights/preflight.yaml
  e2e/kots-release-install-failing-preflights/restore.yaml
  e2e/kots-release-install-failing-preflights/troubleshoot.yaml
  e2e/kots-release-install-warning-preflights/backup.yaml
  e2e/kots-release-install-warning-preflights/cluster-config.yaml
  e2e/kots-release-install-warning-preflights/config.yaml
  e2e/kots-release-install-warning-preflights/deployment-2.yaml
  e2e/kots-release-install-warning-preflights/deployment.yaml
  e2e/kots-release-install-warning-preflights/k8s-app.yaml
  e2e/kots-release-install-warning-preflights/kots-app.yaml
  e2e/kots-release-install-warning-preflights/kots-lint-config.yaml
  e2e/kots-release-install-warning-preflights/preflight.yaml
  e2e/kots-release-install-warning-preflights/restore.yaml
  e2e/kots-release-install-warning-preflights/troubleshoot.yaml
  e2e/kots-release-install-warning-preflights/warning-preflights.yaml
  e2e/kots-release-unsupported-overrides/backup.yaml
  e2e/kots-release-unsupported-overrides/cluster-config.yaml
  e2e/kots-release-unsupported-overrides/config.yaml
  e2e/kots-release-unsupported-overrides/deployment-2.yaml
  e2e/kots-release-unsupported-overrides/deployment.yaml
  e2e/kots-release-unsupported-overrides/k8s-app.yaml
  e2e/kots-release-unsupported-overrides/kots-app.yaml
  e2e/kots-release-unsupported-overrides/kots-lint-config.yaml
  e2e/kots-release-unsupported-overrides/preflight.yaml
  e2e/kots-release-unsupported-overrides/restore.yaml
  e2e/kots-release-unsupported-overrides/troubleshoot.yaml
  e2e/scripts/embedded-preflight.sh
  e2e/scripts/unsupported-overrides.sh
  e2e/unsupported-overrides_test.go
Labels: type::chore

#1795 remove operator/pkg/charts as it is now unused
  go.mod
  go.sum
  operator/controllers/installation_controller.go
  operator/pkg/charts/charts.go
  operator/pkg/charts/charts_test.go
  operator/pkg/charts/detection.go
  operator/pkg/charts/helm_test.go
  operator/pkg/charts/reconcile.go
  operator/pkg/charts/reconcile_test.go
Labels: type::chore

#1794 feat(v2): support for restore
  operator/pkg/artifacts/registry.go
  pkg/addons2/adminconsole/adminconsole.go
  pkg/addons2/adminconsole/install.go
  pkg/addons2/adminconsole/upgrade.go
  pkg/addons2/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons2/embeddedclusteroperator/install.go
  pkg/addons2/embeddedclusteroperator/upgrade.go
  pkg/addons2/registry/install.go
  pkg/addons2/registry/registry.go
  pkg/addons2/registry/upgrade.go
  pkg/addons2/seaweedfs/install.go
  pkg/addons2/seaweedfs/seaweedfs.go
  pkg/addons2/seaweedfs/upgrade.go
  pkg/helm/client.go
  pkg/helm/images.go
  pkg/helm/mock_client.go
Labels: type::feature

#1798 check chart contents directly instead of using k0s chart object
  e2e/scripts/check-postupgrade-state.sh
Labels: type::chore

#1797 feat(v2): restore ha
  cmd/installer/cli/restore2.go
  e2e/install_test.go
  e2e/restore_test.go
  e2e/scripts/restore-multi-node-airgap-phase2.exp
  e2e/scripts/restore-multi-node-phase2.exp
  pkg/addons2/highavailability.go
Labels: type::feature

#1800 Fix dryrun tests
  cmd/buildtools/metadata.go
  cmd/buildtools/utils.go
  cmd/installer/cli/install2.go
  cmd/installer/cli/restore2.go
  pkg/addons2/adminconsole/install.go
  pkg/addons2/adminconsole/upgrade.go
  pkg/addons2/embeddedclusteroperator/install.go
  pkg/addons2/embeddedclusteroperator/upgrade.go
  pkg/addons2/highavailability.go
  pkg/addons2/install.go
  pkg/addons2/openebs/install.go
  pkg/addons2/openebs/upgrade.go
  pkg/addons2/registry/install.go
  pkg/addons2/registry/upgrade.go
  pkg/addons2/seaweedfs/install.go
  pkg/addons2/seaweedfs/upgrade.go
  pkg/addons2/types/types.go
  pkg/addons2/upgrade.go
  pkg/addons2/velero/install.go
  pkg/addons2/velero/upgrade.go
  pkg/dryrun/dryrun.go
  pkg/dryrun/kubeutils.go
  pkg/dryrun/types/types.go
  pkg/extensions/install.go
  pkg/extensions/upgrade.go
  pkg/extensions/util.go
  pkg/helm/client.go
  pkg/helm/images.go
  pkg/helm/interface.go
  pkg/helm/mock_client.go
  pkg/kubeutils/interface.go
  pkg/kubeutils/kubeutils.go
  tests/dryrun/install_test.go
  tests/dryrun/util.go
Labels: type::feature

#1799 feat(v2): fix extensions apply
  operator/pkg/upgrade/upgrade.go
  pkg/extensions/upgrade.go
  pkg/extensions/upgrade_test.go
  pkg/extensions/util.go
Labels: type::feature

#1802 chore(v2): mock helm client factory
  cmd/buildtools/adminconsole.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/metadata.go
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/utils.go
  cmd/buildtools/velero.go
  cmd/installer/cli/install2.go
  cmd/installer/cli/join2.go
  cmd/installer/cli/restore2.go
  operator/pkg/cli/upgrade_job.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons2/highavailability.go
  pkg/addons2/install.go
  pkg/addons2/upgrade.go
  pkg/dryrun/dryrun.go
  pkg/extensions/install.go
  pkg/helm/client.go
  pkg/helm/interface.go
  tests/dryrun/install_test.go
Labels: type::chore

#1806 chore(v2): refactor defers
  operator/pkg/cli/migratev2/installation.go
  operator/pkg/cli/migratev2/migrate.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons2/upgrade.go
  pkg/extensions/upgrade.go
Labels: type::chore

#1805 Remove dead and legacy code
  cmd/buildtools/adminconsole.go
  cmd/buildtools/embeddedclusteroperator.go
  cmd/buildtools/openebs.go
  cmd/buildtools/registry.go
  cmd/buildtools/seaweedfs.go
  cmd/buildtools/velero.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  cmd/installer/cli/install_test.go
  cmd/installer/cli/join.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/root.go
  operator/controllers/installation_controller.go
  operator/pkg/cli/migrate.go
  operator/pkg/cli/root.go
  operator/pkg/cli/upgrade_job.go
  operator/pkg/cli/version.go
  operator/pkg/migrations/registry.go
  operator/pkg/registry/labels.go
  operator/pkg/registry/migrate.go
  operator/pkg/registry/registry.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.tpl.yaml
  pkg/addons/applier.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
  pkg/addons/openebs/openebs.go
  pkg/addons/openebs/static.go.bak
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons/openebs/static/values.tpl.yaml
  pkg/addons/options.go
  pkg/addons/registry/registry.go
  pkg/addons/registry/static/metadata.yaml
  pkg/addons/registry/static/values-ha.tpl.yaml
  pkg/addons/registry/static/values.tpl.yaml
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/seaweedfs/seaweedfs_test.go
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons/seaweedfs/static/values.tpl.yaml
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.tpl.yaml
  pkg/addons/velero/velero.go
  pkg/addons2/adminconsole/static/metadata.yaml
  pkg/config/config.go
  pkg/release/addon.go
  tests/integration/kind/openebs/analytics_test.go
  tests/integration/kind/openebs/customdatadir_test.go
Labels: type::feature

#1796 Prompt for admin console password if not provided
  cmd/installer/cli/adminconsole_resetpassword.go
Labels: type::feature

#1811 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1813 fix onrelease ci process
  .github/workflows/release-prod.yaml
  e2e/install_test.go
Labels: type::chore

#1815 feat(v2): add back config values file validation
  cmd/installer/cli/install.go
Labels: type::feature

#1819 Automation/k0s image dependencies
  cmd/buildtools/k0s.go
  pkg/config/static/metadata.yaml
Labels: type::feature

#1822 fix(v2): air gap with space
  cmd/installer/cli/install.go
Labels: type::chore

#1814 chore: remove dead code
  .golangci.yml
  cmd/buildtools/utils.go
  cmd/installer/cli/install.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/restore_test.go
  kinds/apis/v1beta1/config_types.go
  kinds/apis/v1beta1/config_types_test.go
  kinds/apis/v1beta1/installation_types_test.go
  operator/pkg/autopilot/autopilot.go
  operator/pkg/k8sutil/chartHealth.go
  operator/pkg/k8sutil/client.go
  operator/pkg/k8sutil/cluster_version.go
  operator/pkg/k8sutil/cluster_version_test.go
  operator/pkg/openebs/openebs_test.go
  operator/pkg/testutils/testutils.go
  operator/pkg/upgrade/upgrade.go
  operator/pkg/util/cidr.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/disasterrecovery/backup.go
  tests/dryrun/join_test.go
Labels: type::chore

#1817 fix(ci): proxy chart to avoid 429 errors
  e2e/kots-release-upgrade/cluster-config.yaml
  hack/test-installation.yaml
Labels: type::chore

#1766 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#1816 fix(seaweedfs): collect logs from all pods in the namespace
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::chore

#1818 fix(v2): disable atomic rollback on helm install addon
  pkg/helm/client.go
Labels: type::chore

#1825 fix(seaweedfs): new seaweedfs-bucket-hook requires wget
  deploy/images/seaweedfs/apko.tmpl.yaml
Labels: type::bug, bug::normal

#1821 fix(v2): retry enabling ha fails
  pkg/addons/seaweedfs/install.go
Labels: type::bug, bug::normal

#1820 chore: update k0s images
  cmd/buildtools/addon.go
  cmd/buildtools/k0s.go
  cmd/buildtools/utils.go
  deploy/images/calico-cni/apko.tmpl.yaml
  deploy/images/calico-kube-controllers/apko.tmpl.yaml
  deploy/images/calico-node/apko.tmpl.yaml
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1824 update registry image to fix cves
  pkg/addons/registry/static/metadata.yaml
Labels: type::feature

#1827 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1829 fix(seaweedfs): busybox wget required
  deploy/images/seaweedfs/apko.tmpl.yaml
Labels: type::bug, bug::normal

#1828 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1739 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr

#1833 chore: log cli exit error to file and more debug logging on ha enable
  cmd/installer/cli/root.go
  pkg/addons/highavailability.go
  pkg/addons/registry/migrate.go
  pkg/addons/registry/upgrade.go
  pkg/dryrun/kubeutils.go
  pkg/highavailability/enable.go
  pkg/highavailability/enable_test.go
  pkg/highavailability/registry.go
  pkg/highavailability/seaweed.go
  pkg/kubeutils/interface.go
  pkg/kubeutils/kubeutils.go
Labels: type::chore

#1832 do not build a separate binary for the legacy-dr test suite
  .github/workflows/ci.yaml
  e2e/restore_test.go
Labels: type::chore

#1834 Fix cleaning up helm values before install / upgrade
  pkg/addons/adminconsole/static/values.tpl.yaml
  pkg/helm/client.go
  pkg/helm/client_test.go
Labels: type::feature

#1837 Fix ability to resume restores
  cmd/installer/cli/install.go
Labels: type::feature

#1835 fix(seaweedfs): pin to version 3.79
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
  deploy/images/seaweedfs/apko.tmpl.yaml
Labels: type::bug, bug::normal

#1840 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1844 Pin seaweedfs to 3.79
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
Labels: type::feature

#1847 remove 'Types created!' line
  cmd/installer/cli/install.go
Labels: type::chore

#1842 fix(ci): e2e app airgap restore image pull backoff
  cmd/installer/cli/testing/assets/release-restore-newdr/restore.yaml
  e2e/kots-release-install-failing-preflights/restore.yaml
  e2e/kots-release-install-warning-preflights/restore.yaml
  e2e/kots-release-install/restore.yaml
  e2e/kots-release-unsupported-overrides/restore.yaml
  e2e/kots-release-upgrade/restore.yaml
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/playwright/tests/shared/app-state.ts
  e2e/playwright/tests/shared/deploy-app.ts
  e2e/playwright/tests/shared/deploy-ec18-app-version.ts
  e2e/playwright/tests/shared/index.ts
  e2e/playwright/tests/validate-restore-app/test.spec.ts
  e2e/restore_test.go
Labels: type::chore

#1848 fix: make helm.SetValue more robust
  pkg/addons/adminconsole/values.go
  pkg/addons/openebs/values.go
  pkg/addons/seaweedfs/values.go
  pkg/addons/velero/values.go
  pkg/helm/values.go
  pkg/helm/values_test.go
  tests/dryrun/install_test.go
Labels: type::chore

#1831 chore: unify kubeutils
  cmd/installer/cli/logging.go
  cmd/installer/cli/restore_test.go
  cmd/installer/main.go
  operator/pkg/artifacts/upgrade.go
  operator/pkg/artifacts/upgrade_test.go
  operator/pkg/cli/migrate_v2.go
  operator/pkg/cli/root.go
  operator/pkg/cli/upgrade.go
  operator/pkg/cli/upgrade_job.go
  operator/pkg/k8sutil/client.go
  operator/pkg/k8sutil/installation.go
  operator/pkg/upgrade/autopilot.go
  operator/pkg/upgrade/installation.go
  operator/pkg/upgrade/job.go
  operator/pkg/upgrade/upgrade.go
  operator/pkg/upgrade/util.go
  operator/pkg/upgrade/util_test.go
  pkg/addons/upgrade.go
  pkg/extensions/upgrade.go
  pkg/kubeutils/client.go
  pkg/kubeutils/ensure.go
  pkg/kubeutils/ensure_test.go
  pkg/kubeutils/installation.go
  pkg/kubeutils/kubeutils.go
  pkg/kubeutils/scheme.go
Labels: type::chore

#1850 chore(ci): retry network requests
  .github/workflows/release-prod.yaml
  e2e/scripts/common.sh
  e2e/scripts/vandoor-prepare.sh
Labels: type::chore

#1851 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1855 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1856 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1859 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1838 chore: fix generic map conversion
  pkg/extensions/util.go
  pkg/helm/client.go
  pkg/helm/client_test.go
  pkg/helm/images.go
  pkg/helm/values.go
Labels: type::chore

#1861 fix: support for amazon linux 2
  pkg/config/config.go
  pkg/helpers/systemd/dbus.go
Labels: type::bug, bug::normal

#1857 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1841 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1862 Add preflights for rp_filter kernel parameter
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/restore.go
  pkg/configutils/runtime.go
  pkg/configutils/static/99-embedded-cluster.conf
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1865 Default rp_filter to loose mode (2) instead of disabled (0)
  pkg/configutils/static/99-embedded-cluster.conf
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1870 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1869 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1871 Add SELinux host preflight check
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1872 fix: configure kernel modules and settings per k0s
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/restore.go
  pkg/configutils/runtime.go
  pkg/configutils/static/modules-load.d/99-embedded-cluster.conf
  pkg/configutils/static/sysctl.d/99-embedded-cluster.conf
Labels: type::bug, bug::normal

#1874 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1875 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1877 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1878 feat: preflights for sysctl and modules
  Makefile
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
  pkg/preflights/host-preflight.yaml
  pkg/preflights/template.go
Labels: type::feature

#1881 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1882 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1880 Update wording for some host preflights
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#1884 fix(dev): skip kernel module preflight checks on docker for mac
  pkg/preflights/host-preflight.yaml
Labels: type::chore

#1883 fix(lam): wait for service after start
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/kotscli/kotscli.go
Labels: type::bug, bug::normal

#1887 Remove cidr flags from instructions of join preflights
  cmd/installer/cli/join_runpreflights.go
  pkg/preflights/host-preflight.yaml
  pkg/preflights/run.go
  pkg/preflights/template_test.go
  pkg/preflights/types/template.go
  tests/dryrun/join_test.go
Labels: type::feature

#1888 fix(host-preflights): fix kernel modules host preflights for builtin
  Makefile
  go.mod
  go.sum
Labels: type::bug, bug::regression

#1889 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#1891 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1729 fix: [sc-118372] /var/lib/embedded-cluster is not exec by other non-root user
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/root.go
  cmd/installer/main.go
  cmd/local-artifact-mirror/main.go
  go.mod
  operator/pkg/cli/upgrade_job.go
  tests/dryrun/Dockerfile
  tests/dryrun/install_test.go
Labels: type::bug, bug::normal

#1893 Pass if clock is synced even if ntp is inactive
  cmd/installer/goods/support/host-support-bundle.tmpl.yaml
  pkg/preflights/host-preflight.yaml
Labels: type::feature, type::improvement

#1892 feat: configure firewalld
  .github/workflows/distros.yaml
  cmd/installer/cli/firewalld.go
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/reset_firewalld.go
  cmd/installer/cli/restore.go
  dev/distros/dockerfiles/almalinux-8.Dockerfile
  e2e/install_test.go
  e2e/scripts/firewalld-configure.sh
  e2e/scripts/firewalld-reset.sh
  e2e/scripts/firewalld-validate.sh
  pkg/dryrun/dryrun.go
  pkg/dryrun/firewalld.go
  pkg/helpers/command.go
  pkg/helpers/firewalld/client.go
  pkg/helpers/firewalld/client_mock.go
  pkg/helpers/firewalld/interface.go
  pkg/helpers/firewalld/util.go
  pkg/helpers/interface.go
  tests/dryrun/install_test.go
  tests/dryrun/join_test.go
Labels: type::feature

#1894 fix(host-preflights): buildtin kernel modules file from wrong path
  Makefile
  go.mod
  go.sum
Labels: type::bug, bug::normal

#1897 Ensure inotify settings meet the minimum requirements
  pkg/configutils/runtime.go
  pkg/configutils/runtime_test.go
  pkg/preflights/host-preflight.yaml
Labels: type::feature, type::improvement

#1899 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1900 Wait for k0s and node to be ready before proceeding
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
Labels: type::feature, type::improvement

#1860 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1901 Add preflight check for directory permissions to prevent etcd startup failures
  Makefile
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  e2e/preflights_test.go
  go.mod
  go.sum
  pkg/preflights/host-preflight.yaml
Labels: type::feature, type::improvement

#1902 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1903 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1898 feat(host-preflights): check that the data directory is executable
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  cmd/installer/cli/root.go
  e2e/preflights_test.go
  pkg/preflights/preflights.go
Labels: type::feature

#1907 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1908 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1910 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1912 embedded-cluster materialize should not be listed in the help output
  cmd/installer/cli/materialize.go
Labels: type::chore

#1911 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1920 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1916 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1918 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1914 fix: use custom domain for kots install
  .github/workflows/ci.yaml
  cmd/installer/cli/install.go
  cmd/installer/cli/restore.go
  cmd/installer/kotscli/kotscli.go
  e2e/cluster/lxd/utils.go
  e2e/scripts/common.sh
  e2e/scripts/env.exp
  e2e/scripts/install-and-configure-squid.sh
  pkg/metrics/interface.go
  pkg/metrics/reporter.go
Labels: type::bug, bug::normal

#1917 chore(ci): lxd copy dir tar
  e2e/cluster/lxd/cluster.go
Labels: type::chore

#1924 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security
