Repository replicatedhq/embedded-cluster, pull requests merged in 2025-05, with the labels that each got.

#2117 Start moving airgap e2e tests to CMX
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  e2e/README.md
  e2e/airgap.go
  e2e/cluster/cmx/cluster.go
  e2e/cluster/interface.go
  e2e/install_test.go
  e2e/proxy_test.go
  e2e/restore_test.go
  e2e/shared.go
  e2e/sudo_test.go
Labels: type::chore

#2140 chore(ci): ignore 143 exit code on node reset
  e2e/cluster/lxd/cluster.go
Labels: type::chore

#2143 chore(ci): cmx log node and network id for debugging purposes
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2146 fix(ci): enable required kernel modules
  .github/workflows/ci.yaml
Labels: type::chore

#2142 Revert TestMultiNodeAirgapHAInstallation back to LXD
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  e2e/install_test.go
Labels: type::chore

#2150 chore(ci): fix release pipeline cmx tests
  .github/workflows/release-prod.yaml
Labels: type::chore

#2156 Build LAM and operator in parallel
  scripts/ci-build-deps.sh
  scripts/common.sh
Labels: type::chore

#2159 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2157 Fix running TestFiveNodesAirgapUpgrade
  .github/workflows/ci.yaml
Labels: type::chore

#2160 Wait for a bit after creating VM and before getting SSH endpoint
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2141 chore(ci): use new replicated vm create --ssh-public-key flag
  .github/actions/e2e-cmx-setup/action.yml
  .github/actions/e2e/action.yml
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2163 hide install run-preflights command
  cmd/installer/cli/install_runpreflights.go
Labels: type::feature

#2162 Automate EC Release Notes
  .github/workflows/release-prod.yaml
Labels: type::chore

#2164 chore(e2e): make sure we log stderr output from the API
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2168 feat: detect host ca bundle
  cmd/installer/cli/ca.go
  cmd/installer/cli/install.go
  cmd/installer/cli/restore.go
  pkg/addons/install.go
Labels: type::feature

#2166 chore: remove unused code
  cmd/installer/cli/install.go
Labels: type::chore

#2165 feat: update adminconsole version
  .github/workflows/ci.yaml
  .github/workflows/release-prod.yaml
  e2e/install_test.go
  e2e/playwright/tests/deploy-ec18-app/test.spec.ts
  e2e/playwright/tests/get-ec18-join-worker-command/test.spec.ts
  e2e/scripts/check-airgap-installation-state.sh
  e2e/scripts/check-airgap-post-ha-state.sh
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-post-ha-state.sh
  e2e/scripts/check-pre-minio-removal-installation-state.sh
  e2e/scripts/pre-minio-removal-install.sh
  e2e/scripts/single-node-airgap-install.sh
  e2e/scripts/single-node-install.sh
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2170 feat(velero): add support for mitm proxy
  cmd/installer/cli/ca.go
  cmd/installer/cli/install.go
  cmd/installer/cli/restore.go
  e2e/proxy_test.go
  e2e/scripts/vandoor-prepare.sh
  e2e/shared.go
  kinds/apis/v1beta1/runtimeconfig_types.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  pkg/addons/install.go
  pkg/addons/upgrade.go
  pkg/addons/velero/install.go
  pkg/addons/velero/integration/hostcabundle_test.go
  pkg/addons/velero/values.go
  pkg/addons/velero/values_test.go
  pkg/addons/velero/velero.go
  pkg/helm/client.go
  pkg/helm/images.go
  pkg/helm/interface.go
  pkg/helm/mock_client.go
  pkg/runtimeconfig/runtimeconfig.go
  tests/dryrun/install_test.go
  tests/integration/kind/Makefile
  tests/integration/kind/velero/ca_test.go
  tests/integration/util/k8s.go
Labels: type::feature

#2176 chore: add Microsoft Defender Antivirus to the list of security tools
  cmd/installer/goods/support/host-support-bundle.tmpl.yaml
Labels: type::chore

#2184 Create CMX nodes sequentially
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2173 feat(operator): improved private ca support from host
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-operator-deployment.yaml
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons/embeddedclusteroperator/install.go
  pkg/addons/embeddedclusteroperator/install_test.go
  pkg/addons/embeddedclusteroperator/integration/hostcabundle_test.go
  pkg/addons/embeddedclusteroperator/upgrade.go
  pkg/addons/embeddedclusteroperator/values.go
  pkg/addons/embeddedclusteroperator/values_test.go
  pkg/addons/install.go
  pkg/addons/upgrade.go
  tests/dryrun/install_test.go
Labels: type::feature

#2189 add tls configuration
  cmd/installer/cli/install.go
  cmd/installer/cli/restore.go
  pkg-new/tlsutils/tls.go
  pkg/netutils/ips.go
Labels: type::feature

#2175 feat(adminconsole): Mount Host CA Bundle into Admin Console Containers
  e2e/install_test.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/install.go
  pkg/addons/adminconsole/integration/hostcabundle_test.go
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons/adminconsole/static/values.tpl.yaml
  pkg/addons/adminconsole/values.go
  pkg/addons/adminconsole/values_test.go
  pkg/addons/install.go
  pkg/addons/install_test.go
  tests/dryrun/install_test.go
Labels: type::feature

#2083 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2197 chore(api): generated docs
  api/Makefile
  api/README.md
  api/api.go
  api/auth.go
  api/console.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/health.go
  api/install.go
  api/types/errors.go
  api/types/health.go
  go.mod
  go.sum
Labels: type::chore

#2198 chore(api): generated docs - fixes
  api/Makefile
  api/api.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/health.go
  api/install.go
  go.mod
  go.sum
Labels: type::chore

#2202 chore: rename flag to --manager-experience
  cmd/installer/cli/install.go
Labels: type::feature

#2190 chore(api-error): change unauthorized msg and add tests
  api/types/errors.go
  api/types/errors_test.go
Labels: type::chore

#2199 chore(api): generated docs - login
  api/auth.go
  api/client/auth.go
  api/client/client.go
  api/client/client_test.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/auth_controller_test.go
  api/types/auth.go
  cmd/installer/cli/install.go
Labels: type::chore

#2200 feat(operator): Mount CA into Upgrade Artifacts Job Container
  operator/charts/embedded-cluster-operator/values.yaml
  operator/charts/embedded-cluster-operator/values.yaml.tmpl
  operator/pkg/artifacts/upgrade.go
  operator/pkg/artifacts/upgrade_test.go
Labels: type::feature

#2216 Add swagger docs for host preflights api endpoints
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/install.go
  api/types/preflight.go
Labels: type::feature

#2213 chore: various fixes
  cmd/installer/cli/cidr.go
  e2e/cluster/cmx/cluster.go
  e2e/cluster/docker/cluster.go
  e2e/cluster/lxd/cluster.go
  e2e/install_test.go
  e2e/proxy_test.go
  e2e/restore_test.go
  operator/pkg/artifacts/upgrade_test.go
  pkg/addons/embeddedclusteroperator/crds_test.go
  pkg/kubeutils/ensure_test.go
Labels: type::chore

#2186 feat: add prompt to proceed if http proxy is set and https proxy unset
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/install_test.go
Labels: type::feature

#2207 FE minor updates - Add tanstack query, tailwind config, remove unused components, display form errors on the UI
  api/README.md
  api/integration/install_test.go
  api/types/errors.go
  api/types/errors_test.go
  pkg/netutils/nets.go
  web/package-lock.json
  web/package.json
  web/query-client.ts
  web/src/App.tsx
  web/src/components/common/Loader.tsx
  web/src/components/prototype/PrototypeSettings.tsx
  web/src/components/wizard/CompletionStep.tsx
  web/src/components/wizard/InstallWizard.tsx
  web/src/components/wizard/SetupStep.tsx
  web/src/components/wizard/ValidationInstallStep.tsx
  web/src/components/wizard/WelcomeStep.tsx
  web/src/components/wizard/setup/LinuxSetup.tsx
  web/src/components/wizard/validation/ErrorMessage.tsx
  web/src/components/wizard/validation/InstallationProgress.tsx
  web/src/components/wizard/validation/LogViewer.tsx
  web/src/components/wizard/validation/StatusIndicator.tsx
  web/src/contexts/BrandingContext.tsx
  web/tailwind.config.js
Labels: type::feature

#2181 chore(e2e): create multiple VMs in one go through the CLI
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2215 chore(velero): update version to 1.16
  pkg/addons/install.go
  pkg/addons/upgrade.go
  pkg/addons/velero/integration/hostcabundle_test.go
  pkg/addons/velero/integration/k0ssubdir_test.go
  pkg/addons/velero/static/metadata.yaml
  pkg/addons/velero/static/values.tpl.yaml
  pkg/addons/velero/values.go
  pkg/addons/velero/values_test.go
  pkg/addons/velero/velero.go
  tests/dryrun/install_test.go
Labels: type::chore

#2219 Fix prompts showing before required flag errors
  cmd/installer/cli/install.go
Labels: type::bug, bug::normal

#2218 fix(operator): memory leak from opening large files
  cmd/installer/cli/enable_ha.go
  cmd/installer/cli/join.go
  cmd/installer/cli/restore.go
  e2e/cluster/cmx/cluster.go
  go.mod
  operator/controllers/installation_controller.go
  operator/controllers/installation_controller_test.go
  operator/pkg/cli/root.go
  pkg/addons/adminconsole/ca_configmap.go
  pkg/addons/adminconsole/ca_configmap_test.go
  pkg/addons/adminconsole/install.go
  pkg/addons/adminconsole/install_test.go
  pkg/addons/adminconsole/integration/hostcabundle_test.go
  pkg/addons/adminconsole/upgrade.go
  pkg/addons/embeddedclusteroperator/install.go
  pkg/addons/embeddedclusteroperator/integration/hostcabundle_test.go
  pkg/addons/embeddedclusteroperator/upgrade.go
  pkg/addons/highavailability.go
  pkg/addons/install.go
  pkg/addons/openebs/install.go
  pkg/addons/openebs/upgrade.go
  pkg/addons/registry/install.go
  pkg/addons/registry/upgrade.go
  pkg/addons/seaweedfs/install.go
  pkg/addons/seaweedfs/upgrade.go
  pkg/addons/types/types.go
  pkg/addons/upgrade.go
  pkg/addons/velero/install.go
  pkg/addons/velero/integration/hostcabundle_test.go
  pkg/addons/velero/integration/k0ssubdir_test.go
  pkg/addons/velero/upgrade.go
  pkg/dryrun/dryrun.go
  pkg/dryrun/kubeutils.go
  pkg/dryrun/types/types.go
  pkg/kubeutils/client.go
  pkg/kubeutils/interface.go
  tests/integration/.k0s/.gitignore
  tests/integration/.k0s/Makefile
  tests/integration/.k0s/install_test.go
  tests/integration/.k0s/run/main.go
  tests/integration/.k0s/run/vm/pool.go
  tests/integration/.k0s/run/vm/vm.go
  tests/integration/kind/openebs/analytics_test.go
  tests/integration/kind/openebs/customdatadir_test.go
  tests/integration/kind/registry/ha_test.go
  tests/integration/kind/velero/ca_test.go
  tests/integration/util/k8s.go
  web/README.md
Labels: type::feature
