Repository replicatedhq/embedded-cluster, pull requests merged in 2025-10, with the labels that each got.

#2987 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2988 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2991 V3 Frontend Upgrade App Preflights Step
  web/src/components/wizard/InstallWizard.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/installation/UpgradeStep.tsx
  web/src/components/wizard/installation/tests/UpgradeStep.test.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
  web/src/utils/api-base.ts
Labels: type::feature

#2845 Update Claude agents and commands
  .claude/.manifest
  .claude/agents/ci-developer.md
  .claude/agents/go-dep-updater.md
  .claude/agents/go-developer.md
  .claude/agents/project-builder.md
  .claude/agents/proposal-writer.md
  .claude/agents/replicated-cli-user.md
  .claude/agents/researcher.md
  .claude/commands/go-update.md
Labels: type::chore, claude-agent-sync

#2996 feat(ui): add support for dropdown, heading, and readonly
  e2e/kots-release-install-v3/config.yaml
  web/src/components/common/Select.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
  web/src/types/index.ts
Labels: type::feature

#2993 Empty user config values should not override original config value / default
  api/pkg/template/config.go
  api/pkg/template/config_test.go
  api/pkg/template/execute_test.go
  api/types/app.go
Labels: type::bug, bug::normal

#3011 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#3019 ignore .claude in ci
  .github/workflows/ci.yaml
  .github/workflows/distros.yaml
  .github/workflows/image-scan.yaml
  .github/workflows/kinds.yaml
  .github/workflows/release-prod.yaml
  .github/workflows/utils.yaml
Labels: type::chore
