Repository replicatedhq/embedded-cluster, pull requests merged in 2025-03, with the labels that each got.

#1925 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1922 chore(ci): concurrent node create
  e2e/cluster/docker/cluster.go
  e2e/cluster/lxd/cluster.go
Labels: type::chore

#1930 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1931 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1929 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1934 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1935 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1933 feat: ensure use of custom domains in metrics reporting
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/metrics.go
  cmd/installer/cli/release.go
  cmd/installer/cli/restore.go
  pkg/metrics/interface.go
  pkg/metrics/reporter.go
  pkg/metrics/reporter_test.go
Labels: type::feature

#1937 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1940 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1941 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1943 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1942 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1945 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1946 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1939 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#1928 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1947 add eof handling and extra timeout to enable-ha expect script
  e2e/scripts/join-ha.exp
Labels: type::chore

#1949 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, type::feature, automated-pr

#1951 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1956 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1954 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1961 add embedded cluster custom domain types, use those domains for preflights
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/release.go
  kinds/apis/v1beta1/config_types.go
  kinds/apis/v1beta1/zz_generated.deepcopy.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  pkg/release/release.go
  pkg/runtimeconfig/defaults.go
Labels: type::feature

#1962 feat(adminconsole): support for custom domains
  kinds/apis/v1beta1/config_types.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/adminconsole/values.go
  pkg/addons/highavailability.go
  pkg/addons/install.go
  pkg/addons/upgrade.go
Labels: type::feature

#1958 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, type::feature, automated-pr

#1960 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1965 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1967 feat(customdomains): update json schema
  operator/Makefile
  operator/schemas/config-embeddedcluster-v1beta1.json
Labels: type::feature

#1968 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, type::feature, automated-pr

#1969 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1973 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1915 worker profiles investigation
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  e2e/kots-release-install/cluster-config.yaml
  kinds/apis/v1beta1/config_types.go
  kinds/apis/v1beta1/zz_generated.deepcopy.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  operator/schemas/config-embeddedcluster-v1beta1.json
  pkg/config/config.go
  pkg/k0s/install.go
  pkg/runtimeconfig/defaults.go
Labels: type::feature

#1975 feat(customdomains): use proxy service for charts
  e2e/kots-release-install-failing-preflights/cluster-config.yaml
  e2e/kots-release-install-legacydr/cluster-config.yaml
  e2e/kots-release-install-stable/cluster-config.yaml
  e2e/kots-release-install-warning-preflights/cluster-config.yaml
  e2e/kots-release-install/cluster-config.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/proxy_test.go
  e2e/restore_test.go
  e2e/scripts/install-and-configure-squid.sh
Labels: type::feature

#1977 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, type::feature, automated-pr

#1980 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1978 feat(customdomains): add metadata service to default no proxy list
  cmd/installer/cli/proxy_test.go
  pkg/runtimeconfig/defaults.go
Labels: type::feature

#1957 chore: parse release data in init
  cmd/installer/cli/install.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/update.go
  cmd/installer/cli/version.go
  cmd/installer/cli/version_embeddeddata.go
  cmd/installer/kotscli/kotscli.go
  e2e/local-artifact-mirror_test.go
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  pkg/config/config.go
  pkg/k0s/install.go
  pkg/metrics/reporter.go
  pkg/preflights/app.go
  pkg/preflights/run.go
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/release/testdata/release.yaml
  pkg/runtimeconfig/defaults.go
Labels: type::chore

#1983 Unpin seaweedfs version
  .github/workflows/image-deps-updater.yaml
Labels: type::chore

#1986 feat(customdomains): disable support bundle uri
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Labels: type::feature

#1987 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr, images

#1993 Unpin seaweedfs chart version
  .github/workflows/update-addons.yaml
Labels: type::security

#1992 integration tests without custom domains
  go.mod
  tests/dryrun/Dockerfile
  tests/dryrun/assets/cluster-config-nodomains.yaml
  tests/dryrun/assets/cluster-config.yaml
  tests/dryrun/assets/install-release.yaml
  tests/dryrun/install_test.go
  tests/dryrun/util.go
Labels: type::chore

#1998 Use go 1.24
  dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
  dev/dockerfiles/operator/Dockerfile.local
  dev/dockerfiles/operator/Dockerfile.ttlsh
  kinds/go.mod
  utils/go.mod
Labels: type::chore

#2000 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr, images, type::security

#1979 chore(ci): use GITHUB_TOKEN to avoid rate limits
  .github/workflows/ci.yaml
  Makefile
  common.mk
  e2e/proxy_test.go
  e2e/scripts/restore-installation-airgap.exp
  e2e/scripts/restore-installation.exp
  e2e/scripts/restore-multi-node-airgap-phase2.exp
  e2e/scripts/restore-multi-node-phase2.exp
  e2e/scripts/resume-restore.exp
  operator/Makefile
Labels: type::chore

#1999 embed default domains in CI test releases
  scripts/ci-embed-release.sh
Labels: type::chore

#2011 chore: print sbctl shell instead of sbctl serve in GitHub actions log
  .github/actions/e2e-troubleshoot/action.yml
Labels: type::chore

#2019 Wait for worker node to be ready when joining
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  pkg/dryrun/kubeutils.go
  pkg/kubeutils/interface.go
  pkg/kubeutils/kubeutils.go
  pkg/runtimeconfig/runtimeconfig.go
  tests/dryrun/join_test.go
Labels: type::feature

#2002 chore(proxy): fix bad squid conf
  e2e/scripts/enable-squid-whitelist.sh
  e2e/scripts/install-and-configure-squid.sh
Labels: type::chore

#2022 Support custom domains for ECO's goldpinger support bundle spec
  cmd/buildtools/embeddedclusteroperator.go
  operator/charts/embedded-cluster-operator/templates/embedded-cluster-troubleshoot-goldpinger.yaml
  operator/charts/embedded-cluster-operator/values.yaml.tmpl
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
Labels: type::feature

#2006 chore: add Windows Defender security tool in support bundle analyser
  cmd/installer/goods/support/host-support-bundle.tmpl.yaml
Labels: type::chore

#2012 feat(ha): node local loadbalancing
  .github/workflows/ci.yaml
  cmd/buildtools/k0s.go
  cmd/buildtools/utils.go
  deploy/images/envoy-distroless/apko.tmpl.yaml
  e2e/cluster/docker/cluster.go
  e2e/cluster/lxd/cluster.go
  e2e/install_test.go
  e2e/reset_test.go
  e2e/scripts/check-nllb.sh
  e2e/scripts/restore-installation-airgap.exp
  e2e/scripts/restore-installation.exp
  e2e/scripts/restore-multi-node-airgap-phase1.exp
  e2e/scripts/restore-multi-node-phase1.exp
  e2e/scripts/resume-restore.exp
  operator/pkg/upgrade/upgrade.go
  operator/pkg/upgrade/upgrade_test.go
  pkg/config/config.go
  pkg/config/images.go
  pkg/config/images_test.go
  pkg/config/static/metadata.yaml
Labels: type::feature

#2026 fix(ec): 7443 only required on loopback interface
  pkg/preflights/host-preflight.yaml
Labels: type::feature

#2020 add jobs to scan released images
  .github/workflows/daily-container-scans.yml
  .github/workflows/scan-container-image.yml
Labels: type::chore

#2028 Only run our components on controller nodes
  operator/charts/embedded-cluster-operator/values.yaml.tmpl
  pkg/addons/openebs/static/values.tpl.yaml
  pkg/addons/registry/static/values-ha.tpl.yaml
  pkg/addons/registry/static/values.tpl.yaml
  pkg/addons/seaweedfs/static/values.tpl.yaml
  pkg/addons/velero/static/values.tpl.yaml
Labels: type::feature

#2008 don't report preflights bypassed if they weren't
  pkg/preflights/run.go
Labels: type::bug, bug::normal

#2031 Fix previous-stable ci test
  e2e/kots-release-install-stable/nginx-app-helm-v1beta2.yaml
Labels: type::chore

#1974 worker profiles (#1915)
  cmd/installer/cli/join.go
  e2e/install_test.go
  e2e/kots-release-install-failing-preflights/cluster-config.yaml
  e2e/kots-release-install-legacydr/cluster-config.yaml
  e2e/kots-release-install-stable/cluster-config.yaml
  e2e/kots-release-install-warning-preflights/cluster-config.yaml
  e2e/kots-release-install/cluster-config.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/scripts/check-installation-state.sh
  e2e/scripts/check-worker-profile.sh
  e2e/scripts/common.sh
  pkg/config/config.go
  pkg/helpers/k0s.go
  pkg/k0s/install.go
  pkg/kotsadm/types.go
  pkg/runtimeconfig/defaults.go
  tests/dryrun/join_test.go
Labels: type::feature

#2030 add -y alias for --yes
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
Labels: type::feature

#2027 fix(ha): make more resilient
  cmd/installer/cli/enable_ha.go
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/root.go
  e2e/cluster/lxd/cluster.go
  e2e/install_test.go
  e2e/scripts/common.sh
  go.mod
  operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
  operator/pkg/cli/migrate.go
  operator/pkg/cli/root.go
  operator/pkg/upgrade/installation.go
  operator/pkg/util/crds.go
  pkg/addons/embeddedclusteroperator/crds.go
  pkg/addons/embeddedclusteroperator/upgrade.go
  pkg/addons/highavailability.go
  pkg/addons/highavailability_test.go
  pkg/addons/metadata.go
  pkg/addons/openebs/upgrade.go
  pkg/addons/registry/install.go
  pkg/addons/registry/migrate.go
  pkg/addons/registry/migrate/migrate.go
  pkg/addons/registry/migrate/pod.go
  pkg/addons/registry/migrate/pod_test.go
  pkg/addons/registry/registry.go
  pkg/addons/registry/upgrade.go
  pkg/addons/seaweedfs/install.go
  pkg/addons/seaweedfs/seaweedfs.go
  pkg/addons/seaweedfs/upgrade.go
  pkg/addons/velero/upgrade.go
  pkg/disasterrecovery/backup.go
  pkg/dryrun/kubeutils.go
  pkg/helm/client.go
  pkg/kubeutils/client.go
  pkg/kubeutils/interface.go
  pkg/kubeutils/kubeutils.go
Labels: type::bug, bug::normal

#2029 Remove --enable-ha flag
  cmd/installer/cli/join.go
  e2e/host-support-bundle_test.go
  e2e/install_test.go
  e2e/local-artifact-mirror_test.go
  e2e/proxy_test.go
  e2e/reset_test.go
  e2e/restore_test.go
  e2e/scripts/join-ha.exp
  e2e/shared.go
  tests/dryrun/join_test.go
Labels: type::feature

#2035 show controller role name in prompts
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  e2e/install_test.go
  pkg/config/config.go
Labels: type::feature

#2038 chore: include the embedded cluster and k0s versions in the debug logs
  cmd/installer/cli/logging.go
Labels: type::chore

#2036 ToLower() hostnames where it'll be used to address nodes
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  e2e/cluster/lxd/cluster.go
  e2e/install_test.go
Labels: type::bug, bug::normal

#2040 skip LXD cleanup in e2e tests within CI
  .github/actions/e2e/action.yml
  e2e/cluster/lxd/cluster.go
Labels: type::chore

#2041 chore(customdomains): fail on TCP_DENIED
  e2e/proxy_test.go
  e2e/restore_test.go
  e2e/scripts/enable-squid-whitelist.sh
Labels: type::feature

#2045 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2047 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2044 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2046 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2042 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2054 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security
