Repository replicatedhq/embedded-cluster, pull requests merged in 2025-09, with the labels that each got.

#2789 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2790 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2772 chore(web): standardise styling for code blocks across components
  web/src/components/common/Markdown.tsx
Labels: type::bug, bug::normal

#2774 chore: standardize on k8s nodeutil.GetHostname
  api/integration/kubernetes/install/infra_test.go
  api/integration/linux/install/infra_test.go
  api/internal/managers/kubernetes/infra/util.go
  api/internal/managers/linux/infra/util.go
  cmd/installer/cli/install.go
  cmd/installer/cli/join.go
  cmd/installer/cli/reset.go
  go.mod
  go.sum
  pkg/metrics/reporter.go
  tests/integration/.k0s/.gitignore
  tests/integration/.k0s/Makefile
  tests/integration/.k0s/install_test.go
  tests/integration/.k0s/run/main.go
  tests/integration/.k0s/run/vm/pool.go
  tests/integration/.k0s/run/vm/vm.go
Labels: type::chore

#2797 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2792 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2798 feat(web): setup page should not pre-fill default values
  web/src/components/common/Select.tsx
  web/src/components/wizard/setup/KubernetesSetupStep.tsx
  web/src/components/wizard/setup/LinuxSetupStep.tsx
  web/src/components/wizard/tests/KubernetesSetupStep.test.tsx
  web/src/components/wizard/tests/LinuxSetupStep.test.tsx
  web/src/contexts/KubernetesConfigContext.tsx
  web/src/contexts/LinuxConfigContext.tsx
  web/src/contexts/WizardModeContext.tsx
  web/src/providers/KubernetesConfigProvider.tsx
  web/src/providers/LinuxConfigProvider.tsx
  web/src/providers/WizardProvider.tsx
  web/src/test/setup.tsx
  web/src/test/testData.ts
  web/src/types/index.ts
Labels: type::feature

#2794 fix(seaweedfs) fix upgrades from version lower than 2.7.3
  pkg/addons/seaweedfs/upgrade.go
  pkg/addons/seaweedfs/upgrade_test.go
Labels: type::bug, bug::normal

#2818 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2817 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2802 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2816 chore: update k0s images
  pkg/config/static/metadata-1_32.yaml
  pkg/config/static/metadata-1_33.yaml
Labels: automated-pr, images, type::security

#2831 Update Makefile versions
  pkg/config/static/metadata-1_32.yaml
  pkg/config/static/metadata-1_33.yaml
Labels: type::chore, automated-pr, makefile

#2834 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2837 chore(ci): fix update addons openebs and velero new kubectl image
  cmd/buildtools/openebs.go
  cmd/buildtools/velero.go
Labels: type::chore

#2840 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2839 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#2879 chore(ci): fix previous stable version e2e tests
  .github/workflows/ci.yaml
Labels: type::chore

#2866 Add support for strict app preflights (backend)
  api/controllers/app/install/install.go
  api/controllers/app/install/test_suite.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/kubernetes/install/appinstall_test.go
  api/integration/kubernetes/install/apppreflight_test.go
  api/integration/linux/install/appinstall_test.go
  api/integration/linux/install/apppreflight_test.go
  api/internal/handlers/kubernetes/install.go
  api/internal/handlers/linux/install.go
  api/types/preflight.go
  api/types/preflight_test.go
  api/types/responses.go
  proposals/strict_preflight_blocking.md
Labels: type::feature

#2885 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2892 chore: update registry images
  pkg/addons/registry/static/metadata.yaml
Labels: automated-pr, images, type::security

#2888 chore: use securebuild for openebs images
  .github/workflows/image-deps-updater.yaml
  .github/workflows/update-addons.yaml
  cmd/buildtools/openebs.go
  cmd/buildtools/utils.go
  e2e/version_test.go
  pkg/addons/openebs/static/metadata.yaml
  pkg/helm/images.go
Labels: type::chore

#2901 chore: update k0s images
  pkg/config/static/metadata-1_32.yaml
  pkg/config/static/metadata-1_33.yaml
Labels: automated-pr, images, type::security

#2915 fix(openebs): delete leftover pre-upgrade hook resources before upgrade
  .github/workflows/ci.yaml
  pkg/addons/openebs/upgrade.go
  pkg/addons/openebs/upgrade_test.go
  tests/integration/kind/openebs/upgrade_hook_cleanup_test.go
  tests/integration/util/kind.go
Labels: type::bug, bug::normal

#2916 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2936 chore: update k0s images
  pkg/config/static/metadata-1_31.yaml
  pkg/config/static/metadata-1_32.yaml
  pkg/config/static/metadata-1_33.yaml
Labels: automated-pr, images, type::security

#2930 chore(ci): cmx cleanup clusters on cancel workflow
  .github/actions/e2e/action.yml
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2941 fix(web): styling issues for typography in v3
  web/src/index.css
  web/tailwind.config.js
Labels: type::bug, bug::regression

#2942 chore: use securebuild for ec-utils image
  cmd/buildtools/embeddedclusteroperator.go
  deploy/images/seaweedfs/apko.tmpl.yaml
  deploy/images/utils/apko.tmpl.yaml
  pkg/addons/embeddedclusteroperator/static/metadata.yaml
  pkg/addons/upgrade_test.go
  pkg/addons/util.go
  pkg/addons/util_test.go
Labels: type::chore

#2919 chore: use securebuild for k0s core images
  cmd/buildtools/k0s.go
  cmd/buildtools/utils.go
  pkg/config/static/metadata-1_31.yaml
  pkg/config/static/metadata-1_32.yaml
  pkg/config/static/metadata-1_33.yaml
Labels: type::chore

#2952 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2953 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2956 Update Makefile versions
  pkg/config/static/metadata-1_31.yaml
  pkg/config/static/metadata-1_32.yaml
  pkg/config/static/metadata-1_33.yaml
Labels: type::chore, automated-pr, makefile

#2960 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2962 chore: update registry images
  pkg/addons/registry/static/metadata.yaml
Labels: automated-pr, images, type::security

#2963 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2965 Update Makefile versions
  pkg/config/static/metadata-1_31.yaml
Labels: type::chore, automated-pr, makefile

#2955 feat(web): add initial upgrade flow
  web/src/components/wizard/InstallWizard.tsx
  web/src/components/wizard/StepNavigation.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/installation/InstallationTimeline.tsx
  web/src/components/wizard/installation/UpgradeStep.tsx
  web/src/components/wizard/installation/phases/AppInstallationPhase.tsx
  web/src/components/wizard/installation/phases/AppPreflightCheck.tsx
  web/src/components/wizard/installation/phases/AppPreflightPhase.tsx
  web/src/components/wizard/installation/phases/KubernetesInstallationPhase.tsx
  web/src/components/wizard/installation/phases/LinuxInstallationPhase.tsx
  web/src/components/wizard/installation/phases/LinuxPreflightCheck.tsx
  web/src/components/wizard/installation/phases/LinuxPreflightPhase.tsx
  web/src/components/wizard/installation/phases/UpgradeConfirmationPhase.tsx
  web/src/components/wizard/installation/tests/AppInstallationPhase.test.tsx
  web/src/components/wizard/installation/tests/UpgradeConfirmationPhase.test.tsx
  web/src/components/wizard/installation/tests/UpgradeStep.test.tsx
  web/src/components/wizard/setup/KubernetesSetupStep.tsx
  web/src/components/wizard/setup/LinuxSetupStep.tsx
  web/src/components/wizard/tests/InstallWizard.test.tsx
  web/src/components/wizard/tests/KubernetesSetupStep.test.tsx
  web/src/components/wizard/tests/StepNavigation.test.tsx
  web/src/contexts/InitialStateContext.tsx
  web/src/contexts/WizardModeContext.tsx
  web/src/contexts/tests/InitialStateContext.test.tsx
  web/src/providers/InitialStateProvider.tsx
  web/src/providers/WizardProvider.tsx
  web/src/test/setup.tsx
  web/src/types/index.ts
  web/src/types/wizard-mode.ts
  web/src/utils/api-base.test.ts
  web/src/utils/api-base.ts
Labels: type::feature
