Repository replicatedhq/embedded-cluster, pull requests merged in 2025-07, with the labels that each got.

#2396 feat: Use the app name in the help menu output
  api/internal/managers/infra/install.go
  api/pkg/logger/logger.go
  cmd/installer/cli/adminconsole.go
  cmd/installer/cli/adminconsole_resetpassword.go
  cmd/installer/cli/enable_ha.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_printcommand.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/logging.go
  cmd/installer/cli/materialize.go
  cmd/installer/cli/node.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/reset_firewalld.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/root.go
  cmd/installer/cli/shell.go
  cmd/installer/cli/supportbundle.go
  cmd/installer/cli/update.go
  cmd/installer/cli/version.go
  cmd/installer/cli/version_embeddeddata.go
  cmd/installer/cli/version_listimages.go
  cmd/installer/cli/version_metadata.go
  cmd/installer/goods/materializer.go
  cmd/installer/main.go
  pkg-new/hostutils/system.go
  pkg-new/k0s/k0s.go
  pkg-new/metadata/metadata.go
  pkg/kubeutils/installation.go
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/runtimeconfig/defaults.go
  pkg/runtimeconfig/util/util.go
  tests/dryrun/util.go
Labels: type::feature

#2397 Document Architecture Decision: Kubernetes as a Subset of Linux
  api/README.md
Labels: type::feature

#2401 feat: use ENABLE_V3 env var instead of flag
  cmd/installer/cli/flags.go
  cmd/installer/cli/install.go
  cmd/installer/cli/update.go
  e2e/scripts/install-and-configure-squid.sh
Labels: type::feature

#2400 fix: parse flags before prompting, do not prompt in flag parsing code
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/restore.go
Labels: type::bug, bug::normal

#2403 Add Kubernetes installation and completion pages
  web/src/components/common/Button.tsx
  web/src/components/wizard/InstallWizard.tsx
  web/src/components/wizard/StepNavigation.tsx
  web/src/components/wizard/completion/KubernetesCompletionStep.tsx
  web/src/components/wizard/completion/LinuxCompletionStep.tsx
  web/src/components/wizard/installation/KubernetesInstallationStep.tsx
  web/src/components/wizard/setup/KubernetesSetupStep.tsx
  web/src/components/wizard/setup/LinuxSetupStep.tsx
  web/src/components/wizard/tests/KubernetesCompletionStep.test.tsx
  web/src/components/wizard/tests/KubernetesInstallationStep.test.tsx
  web/src/components/wizard/tests/KubernetesSetupStep.test.tsx
  web/src/components/wizard/tests/LinuxCompletionStep.test.tsx
  web/src/components/wizard/tests/LinuxSetupStep.test.tsx
  web/src/components/wizard/tests/StepNavigation.test.tsx
  web/src/test/setup.tsx
  web/src/test/testData.ts
  web/src/types/index.ts
Labels: type::feature

#2405 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#2210 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2321 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr

#2324 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#2414 chore(ci): bump sigs.k8s.io/controller-runtime from 0.20.4 to 0.21.0
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
Labels: type::chore

#2411 chore(ci): controller-gen version v0.18.0
  kinds/Makefile
  operator/Makefile
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_kubernetesinstallations.yaml
  pkg/crds/resources.yaml
Labels: type::chore

#2422 chore: dependabot security group only patches
  .github/dependabot.yml
Labels: type::chore

#2423 chore: dependabot does not work with dagger
  .github/dependabot.yml
Labels: type::chore

#2424 chore: group dependabot actions
  .github/dependabot.yml
Labels: type::chore

#2421 API to get Config from release
  api/Makefile
  api/client/client.go
  api/client/client_test.go
  api/client/install.go
  api/controllers/kubernetes/install/app.go
  api/controllers/kubernetes/install/app_test.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/linux/install/app.go
  api/controllers/linux/install/app_test.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_mock.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/install_test.go
  api/internal/handlers/kubernetes/install.go
  api/internal/handlers/linux/install.go
  api/internal/managers/app/config/manager_mock.go
  api/internal/store/app/config/store_test.go
  api/routes.go
  pkg/release/release.go
Labels: type::feature

#2426 feat(kubernetes): validate kubeconfig
  cmd/installer/cli/install.go
Labels: type::feature

#2429 feat: update seaweedfs version
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: type::chore, automated-pr

#2430 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2433 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2420 chore(ci): update kustomize to v5.7.0
  operator/Makefile
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/kustomization.yaml
  pkg/crds/resources.yaml
Labels: type::chore

#2417 feat: Add adm install command to k8s target UI
  web/src/components/wizard/completion/KubernetesCompletionStep.tsx
  web/src/components/wizard/completion/LinuxCompletionStep.tsx
  web/src/components/wizard/tests/KubernetesCompletionStep.test.tsx
  web/src/contexts/KubernetesConfigContext.tsx
  web/src/test/setup.tsx
Labels: type::feature

#2434 Add API endpoint to set config values
  api/controllers/kubernetes/install/app.go
  api/controllers/kubernetes/install/app_test.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/linux/install/app.go
  api/controllers/linux/install/app_test.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_mock.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/install_test.go
  api/internal/handlers/kubernetes/install.go
  api/internal/handlers/linux/install.go
  api/internal/managers/app/config/config.go
  api/internal/managers/app/config/config_test.go
  api/internal/managers/app/config/manager.go
  api/internal/managers/app/config/manager_mock.go
  api/internal/store/app/config/store.go
  api/internal/store/app/config/store_mock.go
  api/internal/store/app/config/store_test.go
  api/routes.go
  api/types/requests.go
Labels: type::feature

#2441 Support the radio config item type
  web/src/components/common/Input.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
Labels: type::feature

#2442 chore(ci): fix ha test
  e2e/scripts/check-airgap-post-ha-state.sh
Labels: type::chore

#2446 chore(api): do not expose kubernetes api type
  api/client/client.go
  api/client/client_test.go
  api/client/install.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/kubernetes/install/app_test.go
  api/integration/linux/install/app_test.go
  api/internal/handlers/kubernetes/install.go
  api/internal/handlers/linux/install.go
  api/types/app.go
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
  web/src/types/index.ts
Labels: type::chore

#2440 feat: pass config values from memory store to kots cli
  .cursor/rules/go-best-practices.mdc
  .cursor/rules/go-ec-api-architecture.mdc
  .cursor/rules/go-testing.mdc
  api/README.md
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_test.go
  api/controllers/linux/install/infra.go
  api/internal/handlers/linux/linux.go
  api/internal/managers/linux/infra/install.go
  api/internal/managers/linux/infra/install_test.go
  api/internal/managers/linux/infra/manager.go
  api/internal/managers/linux/infra/manager_mock.go
  api/internal/store/app/config/store_test.go
  cmd/installer/kotscli/kotscli.go
  cmd/installer/kotscli/kotscli_test.go
Labels: type::feature

#2447 feat(ui): add support for textarea config option
  web/src/components/common/Textarea.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
  web/src/vite.setup.ts
Labels: type::feature

#2444 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2454 fix(ci): run integration tests
  api/Makefile
Labels: type::bug, bug::normal

#2449 feat(ui): add support for label config option
  web/package-lock.json
  web/package.json
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
Labels: type::feature

#2450 feat(api): handle config item "when" attribute
  api/controllers/kubernetes/install/app.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/linux/install/app.go
  api/controllers/linux/install/controller_mock.go
  api/internal/managers/app/config/config.go
  api/internal/managers/app/config/config_test.go
  api/internal/managers/app/config/manager.go
  api/internal/managers/app/config/manager_mock.go
Labels: type::feature

#2455 fix: markdown styling for label config option
  web/package-lock.json
  web/package.json
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/tailwind.config.js
Labels: type::bug, bug::normal

#2458 fix(ui): use installation target from initial state in authcontext
  web/src/contexts/AuthContext.tsx
Labels: type::bug, bug::normal

#2459 chore(ci): upgrade golangci-lint
  .github/workflows/ci.yaml
  .golangci.yml
  api/integration/linux/install/infra_test.go
  api/internal/handlers/kubernetes/kubernetes.go
  api/internal/managers/linux/infra/install.go
  api/internal/statemachine/event_handler.go
  cmd/installer/cli/install.go
  cmd/installer/cli/logging.go
  cmd/installer/cli/restore.go
  cmd/local-artifact-mirror/serve_test.go
  e2e/cluster/cmx/cluster.go
  operator/controllers/installation_controller.go
  operator/controllers/installation_controller_test.go
  operator/pkg/artifacts/registry.go
  operator/pkg/artifacts/upgrade.go
  operator/pkg/artifacts/upgrade_test.go
  operator/pkg/cli/migratev2/k0s.go
  operator/pkg/openebs/openebs.go
  pkg/addons/adminconsole/ca_configmap_test.go
  pkg/addons/adminconsole/integration/hostcabundle_test.go
  pkg/addons/embeddedclusteroperator/integration/hostcabundle_test.go
  pkg/addons/registry/migrate/pod.go
  pkg/addons/registry/upgrade.go
  pkg/addons/seaweedfs/install.go
  pkg/addons/velero/integration/hostcabundle_test.go
  pkg/addons/velero/integration/k0ssubdir_test.go
  pkg/disasterrecovery/backup.go
  pkg/helpers/k0s.go
  pkg/kubeutils/installation.go
  pkg/netutils/nets.go
  tests/dryrun/install_test.go
  tests/integration/kind/velero/ca_test.go
  tests/integration/util/k8s.go
Labels: type::chore

#2460 chore(web): consistent usage of the intial state context
  web/package-lock.json
  web/src/App.tsx
  web/src/components/common/Logo.tsx
  web/src/components/wizard/completion/KubernetesCompletionStep.tsx
  web/src/components/wizard/completion/LinuxCompletionStep.tsx
  web/src/components/wizard/setup/LinuxSetupStep.tsx
  web/src/contexts/AuthContext.tsx
  web/src/contexts/BrandingContext.tsx
  web/src/contexts/InitialStateContext.tsx
  web/src/contexts/WizardModeContext.tsx
  web/src/contexts/tests/InitialStateContext.test.tsx
  web/src/global.d.ts
  web/src/test/setup.tsx
  web/src/types/index.ts
  web/src/types/installation-target.ts
Labels: type::chore

#2478 Add CLAUDE.md file
  .gitignore
  CLAUDE.md
Labels: type::chore

#2475 chore(api): validate app release data on instantiation
  .cursor/rules/go-best-practices.mdc
  api/controllers/kubernetes/install/app.go
  api/controllers/kubernetes/install/app_test.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_test.go
  api/controllers/kubernetes/install/infra.go
  api/controllers/linux/install/app.go
  api/controllers/linux/install/app_test.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_test.go
  api/controllers/linux/install/infra.go
  api/integration/auth/controller_test.go
  api/integration/console/controller_test.go
  api/integration/kubernetes/install/app_test.go
  api/integration/kubernetes/install/infra_test.go
  api/integration/kubernetes/install/installation_test.go
  api/integration/linux/install/app_test.go
  api/integration/linux/install/hostpreflight_test.go
  api/integration/linux/install/infra_test.go
  api/integration/linux/install/installation_test.go
  api/integration/util.go
  cmd/installer/cli/api_test.go
Labels: type::feature

#2342 only auto scroll if at bottom of logs
  web/src/components/wizard/installation/shared/LogViewer.test.tsx
  web/src/components/wizard/installation/shared/LogViewer.tsx
Labels: type::feature

#2481 chore(ci): conditionally run e2e tests
  .github/workflows/ci.yaml
Labels: type::chore

#2476 fix(ui): fixed widths for config input items
  web/src/components/common/Input.tsx
  web/src/components/common/Select.tsx
  web/src/components/common/Textarea.tsx
  web/src/components/wizard/WelcomeStep.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/setup/KubernetesSetupStep.tsx
  web/src/components/wizard/setup/LinuxSetupStep.tsx
Labels: type::chore

#2487 chore(ci): github rate limits when running api integration tests
  .github/workflows/ci.yaml
Labels: type::chore

#2480 feat(ui:) add support for default config values
  web/src/components/common/Checkbox.tsx
  web/src/components/common/HelpText.tsx
  web/src/components/common/Input.tsx
  web/src/components/common/Label.tsx
  web/src/components/common/Radio.tsx
  web/src/components/common/Textarea.tsx
  web/src/components/common/tests/HelpText.test.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
Labels: type::feature

#2486 chore(app): add config values types
  .github/workflows/ci.yaml
  api/client/client.go
  api/client/client_test.go
  api/client/install.go
  api/controllers/kubernetes/install/app.go
  api/controllers/kubernetes/install/app_test.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/linux/install/app.go
  api/controllers/linux/install/app_test.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_mock.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/kubernetes/install/app_test.go
  api/integration/linux/install/app_test.go
  api/internal/managers/app/config/config.go
  api/internal/managers/app/config/config_test.go
  api/internal/managers/app/config/manager.go
  api/internal/managers/app/config/manager_mock.go
  api/internal/store/app/config/store.go
  api/internal/store/app/config/store_mock.go
  api/internal/store/app/config/store_test.go
  api/types/api.go
  api/types/app.go
  api/types/requests.go
  api/types/responses.go
  cmd/installer/cli/install.go
  go.mod
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
  web/src/types/index.ts
Labels: type::chore

#2493 Add file Config Item Type - Frontend File Input Component
  web/src/components/common/FileInput.test.tsx
  web/src/components/common/FileInput.tsx
  web/src/vite.setup.ts
Labels: type::feature

#2491 feat(app): add support for the file type item
  api/integration/kubernetes/install/app_test.go
  api/integration/linux/install/app_test.go
  api/internal/managers/app/config/config.go
  api/internal/managers/app/config/config_test.go
Labels: type::feature

#2482 try to resolve relative data dir paths
  cmd/installer/cli/install.go
Labels: type::bug, bug::normal

#2498 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2500 chore(app-manager): cleanup of helper methods
  api/internal/managers/app/config/config.go
Labels: type::chore

#2496 bug: Fix markdown paragraph and line breaks
  web/src/components/common/HelpText.tsx
  web/src/components/common/Label.tsx
  web/src/components/common/tests/HelpText.test.tsx
Labels: type::bug, bug::normal

#2506 Revert "build(deps-dev): bump vite from 6.3.5 to 7.0.4 in /web"
  web/package-lock.json
  web/package.json
Labels: type::chore

#2505 Core Recursive Config Template Engine
  .github/workflows/ci.yaml
  api/pkg/template/engine.go
  api/pkg/template/engine_test.go
Labels: type::feature

#2517 Support repl templates - Template API Endpoint
  api/client/client.go
  api/client/client_test.go
  api/client/install.go
  api/controllers/kubernetes/install/app.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/linux/install/app.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_mock.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/kubernetes/install/app_test.go
  api/integration/linux/install/app_test.go
  api/internal/handlers/kubernetes/install.go
  api/internal/handlers/linux/install.go
  api/routes.go
  api/types/requests.go
Labels: type::feature

#2518 chore(ci): dryrun test airgap prompt
  .cursor/rules/code-quality-checks.mdc
  pkg/dryrun/dryrun.go
  pkg/dryrun/types/types.go
  pkg/prompts/mock_prompts.go
  pkg/prompts/prompts.go
  tests/dryrun/install_prompts_test.go
Labels: type::chore

#2509 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2524 Support repl templates - Optimize template performance
  api/pkg/template/engine.go
  api/pkg/template/engine_test.go
Labels: type::feature

#2529 chore(web): fix lint errors
  Makefile
  common.mk
  web/src/App.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/setup/KubernetesSetupStep.tsx
  web/src/components/wizard/setup/LinuxSetupStep.tsx
  web/src/components/wizard/tests/KubernetesSetupStep.test.tsx
  web/src/components/wizard/tests/LinuxSetupStep.test.tsx
  web/src/contexts/AuthContext.tsx
  web/src/contexts/InitialStateContext.tsx
  web/src/contexts/KubernetesConfigContext.tsx
  web/src/contexts/LinuxConfigContext.tsx
  web/src/contexts/SettingsContext.tsx
  web/src/contexts/WizardModeContext.tsx
  web/src/contexts/tests/InitialStateContext.test.tsx
  web/src/providers/AuthProvider.tsx
  web/src/providers/InitialStateProvider.tsx
  web/src/providers/KubernetesConfigProvider.tsx
  web/src/providers/LinuxConfigProvider.tsx
  web/src/providers/SettingsProvider.tsx
  web/src/providers/WizardProvider.tsx
  web/src/test/setup.tsx
  web/src/utils/auth.ts
  web/src/utils/errorMessage.ts
  web/src/utils/errorMessages.test.ts
Labels: type::chore

#2530 chore(ci): test http proxy used in request to check for new app versions
  pkg/dryrun/dryrun.go
  tests/dryrun/install_http_proxy_test.go
  tests/dryrun/install_test.go
Labels: type::chore

#2531 feat(api): config template function support
  api/pkg/template/engine.go
  api/pkg/template/engine_test.go
Labels: type::feature

#2528 feat(file-input): add support for default values
  web/src/components/common/HelpText.tsx
  web/src/components/common/file/File.tsx
  web/src/components/common/file/FileInput.tsx
  web/src/components/common/file/index.ts
  web/src/components/common/tests/File.test.tsx
  web/src/components/common/tests/FileInput.test.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/vite.setup.ts
Labels: type::feature

#2540 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#2545 fix(app-config): validation of required password fields
  api/integration/kubernetes/install/app_test.go
  api/integration/linux/install/app_test.go
  api/internal/managers/app/config/config.go
  api/internal/managers/app/config/config_test.go
Labels: type::bug, bug::normal

#2543 Support repl templates - Optimize template performance for top-level items
  api/client/client_test.go
  api/controllers/kubernetes/install/app_test.go
  api/controllers/kubernetes/install/controller_test.go
  api/controllers/linux/install/app_test.go
  api/controllers/linux/install/controller_test.go
  api/integration/kubernetes/install/app_test.go
  api/integration/kubernetes/install/infra_test.go
  api/integration/linux/install/app_test.go
  api/integration/linux/install/infra_test.go
  api/internal/managers/app/config/config_test.go
  api/internal/managers/app/config/manager.go
  api/internal/managers/app/config/template.go
  api/internal/managers/app/config/template_test.go
  api/pkg/template/config.go
  api/pkg/template/config_test.go
  api/pkg/template/engine.go
  api/pkg/template/engine_test.go
  api/pkg/template/license.go
Labels: type::feature

#2544 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2548 feat(api): LicenseDockerCfg template function support
  api/pkg/template/engine.go
  api/pkg/template/engine_test.go
  api/pkg/template/license.go
  api/pkg/template/license_test.go
Labels: type::feature

#2539 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2550 chore(web): upgrade deps
  web/package-lock.json
  web/package.json
Labels: type::chore

#2549 feat(api): static template function support
  api/pkg/template/engine.go
  api/pkg/template/static.go
  api/pkg/template/static_test.go
  go.mod
Labels: type::feature

#2559 fix(ui): show error message for empty password in UI
  web/src/components/wizard/WelcomeStep.tsx
  web/src/components/wizard/tests/WelcomeStep.test.tsx
Labels: type::bug, bug::normal

#2551 Support repl templates - Integrate Template API Endpoint with UI
  GEMINI.md
  api/client/client.go
  api/client/client_test.go
  api/client/install.go
  api/controllers/kubernetes/install/app.go
  api/controllers/kubernetes/install/app_test.go
  api/controllers/kubernetes/install/controller.go
  api/controllers/kubernetes/install/controller_mock.go
  api/controllers/linux/install/app.go
  api/controllers/linux/install/app_test.go
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/controller_mock.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/integration/kubernetes/install/app_test.go
  api/integration/linux/install/app_test.go
  api/internal/handlers/kubernetes/install.go
  api/internal/handlers/linux/install.go
  api/internal/managers/app/config/config.go
  api/internal/managers/app/config/config_test.go
  api/internal/managers/app/config/manager.go
  api/internal/managers/app/config/manager_mock.go
  api/pkg/template/config.go
  api/pkg/template/engine_test.go
  api/routes.go
  e2e/kots-release-install-v3/config.yaml
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
  web/src/components/wizard/tests/InstallWizard.test.tsx
  web/src/utils/debouncedFetch.test.ts
  web/src/utils/debouncedFetch.ts
Labels: type::feature

#2563 chore: update k0s images
  pkg/config/static/metadata.yaml
Labels: automated-pr, images, type::security

#2565 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#2546 feat(ui): highlight required items
  Makefile
  api/integration/kubernetes/install/app_test.go
  api/integration/linux/install/app_test.go
  api/internal/managers/app/config/config.go
  web/src/components/common/Button.tsx
  web/src/components/common/Checkbox.tsx
  web/src/components/common/Input.tsx
  web/src/components/common/Radio.tsx
  web/src/components/common/Textarea.tsx
  web/src/components/common/file/FileInput.tsx
  web/src/components/wizard/config/ConfigurationStep.tsx
  web/src/components/wizard/tests/ConfigurationStep.test.tsx
Labels: type::feature

#2573 chore(ci): pin k0s upgrade automation to current minor
  .github/workflows/dependencies.yaml
Labels: type::chore

#604 Update Makefile versions
  Makefile
  go.mod
  go.sum
  kinds/go.mod
  kinds/go.sum
Labels: type::chore, automated-pr, makefile

#2574 feat(api): empty app config hidden required fields should return error
  api/internal/managers/app/config/config.go
  api/internal/managers/app/config/config_test.go
  e2e/kots-release-install-v3/config.yaml
Labels: type::feature

#2594 Do not fail image scan workflows until we fully utilize SecureBuild images
  .github/workflows/image-scan.yaml
Labels: type::chore

#2336 feat: preflight storage needed to perform airgap install
  api/controllers/linux/install/controller.go
  api/controllers/linux/install/hostpreflight.go
  api/internal/handlers/linux/linux.go
  api/internal/managers/linux/infra/install.go
  api/internal/managers/linux/infra/manager.go
  api/internal/managers/linux/preflight/hostpreflight.go
  api/types/api.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/join.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/update.go
  cmd/installer/goods/materializer.go
  go.mod
  go.sum
  kinds/apis/v1beta1/installation_types.go
  operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
  operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
  pkg-new/preflights/host-preflight.yaml
  pkg-new/preflights/prepare.go
  pkg-new/preflights/template.go
  pkg-new/preflights/template_test.go
  pkg-new/preflights/types/template.go
  pkg/airgap/airgapinfo.go
  pkg/airgap/airgapinfo_test.go
  pkg/airgap/materialize.go
  pkg/airgap/testfiles/tiny-airgap-noimages-app/embedded-cluster/images-amd64.tar
  pkg/airgap/testfiles/tiny-airgap-noimages/airgap.yaml
  pkg/airgap/testfiles/tiny-airgap-noimages/embedded-cluster/images-amd64.tar
  pkg/airgap/version.go
  pkg/crds/resources.yaml
  pkg/kubeutils/installation.go
  pkg/kubeutils/installation_test.go
  tests/dryrun/assets/bundle.airgap
Labels: type::feature

#2597 chore(ci): Handle exit code 143 during reset within CMX
  e2e/cluster/cmx/cluster.go
Labels: type::chore

#2601 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#2609 feat: skip KOTS app preflights when manager experience installer is enabled
  api/internal/managers/linux/infra/install.go
  cmd/installer/kotscli/kotscli.go
Labels: type::feature
