Repository replicatedhq/embedded-cluster, pull requests merged in 2025-01, with the labels that each got.

#1676 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1675 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1678 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1656 chore(ci): run TestFiveNodesAirgapUpgrade on main only
  .github/workflows/ci.yaml
Labels: type::chore

#1679 fix(dr): use Status.CompletionTimestamp for sorting backups
  cmd/installer/cli/restore.go
  pkg/disasterrecovery/backup.go
  pkg/disasterrecovery/backup_test.go
Labels: type::feature

#1680 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1684 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1686 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1682 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1683 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1691 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1701 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1704 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1703 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1705 Make restore fail messages more user-facing
  cmd/installer/cli/restore.go
Labels: type::feature

#1706 fix(dr): improved dr should not restore the component app backup
  cmd/installer/cli/restore.go
Labels: type::feature

#1710 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1709 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1700 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1692 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1725 feat(ec): migration from v1 to v2 - fixes
  kinds/apis/v1beta1/installation_types.go
  operator/controllers/installation_controller.go
  operator/pkg/charts/reconcile.go
  operator/pkg/cli/logging.go
  operator/pkg/cli/migrate_v2_pod.go
  operator/pkg/cli/migratev2/installation.go
  operator/pkg/cli/migratev2/installation_test.go
  operator/pkg/cli/migratev2/migrate.go
  operator/pkg/cli/migratev2/operator.go
  operator/pkg/cli/migratev2/operator_test.go
  pkg/kubeutils/kubeutils.go
Labels: type::feature

#1717 feat: ability to upgrade ec manager
  Makefile
  cmd/manager/start.go
  pkg/extensions/util.go
  pkg/manager/upgrade.go
  pkg/websocket/client.go
  pkg/websocket/client_test.go
  pkg/websocket/report.go
  pkg/websocket/reporter.go
  pkg/websocket/server.go
  pkg/websocket/types/types.go
  pkg/websocket/util.go
Labels: type::feature

#1730 fix(ci): fix manager integration test
  cmd/manager/start.go
  pkg/manager/install.go
  tests/integration/manager/Makefile
  tests/integration/manager/install_test.go
Labels: type::chore

#1728 upgrade k0s to v1.30.9
  Makefile
  go.mod
  go.sum
Labels: type::chore

#1732 Keep 'v' when pushing manager binary to s3
  scripts/ci-upload-binaries.sh
Labels: type::feature

#1731 chore: separate goods package
  .gitignore
  Makefile
  cmd/installer/cli/adminconsole_resetpassword.go
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/materialize.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/update.go
  cmd/installer/goods/bins/.placeholder
  cmd/installer/goods/completion.go
  cmd/installer/goods/goods.go
  cmd/installer/goods/internal/bins/.placeholder
  cmd/installer/goods/materializer.go
  cmd/installer/goods/materializer_test.go
  cmd/installer/goods/static/compalias_bash.tmpl.sh
  cmd/installer/goods/support/host-support-bundle.tmpl.yaml
  cmd/installer/goods/systemd/calico-network-manager.conf
  cmd/installer/goods/systemd/local-artifact-mirror.service
  cmd/installer/kotscli/kotscli.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons/adminconsole/adminconsole.go
  pkg/addons/applier.go
  pkg/addons/options.go
  pkg/addons2/addons.go
  pkg/addons2/adminconsole/adminconsole.go
  pkg/addons2/adminconsole/install.go
  pkg/configutils/runtime.go
  pkg/configutils/static/99-embedded-cluster.conf
  pkg/goods/materializer_test.go
  pkg/support/hostbundle.go
  pkg/support/static/host-support-bundle-remote.yaml
  pkg/upgrade/upgrade.go
  tests/integration/manager/Makefile
Labels: type::chore

#1712 feat: update adminconsole version
  e2e/kots-release-upgrade/cluster-config.yaml
  pkg/addons/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1740 feat: update velero version
  pkg/addons/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1741 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1743 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1748 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1733 helm chart install should work when airgapped
  .github/workflows/ci.yaml
  cmd/installer/cli/install2.go
  e2e/install2_test.go
  e2e/kots-release-install-legacydr/preflight.yaml
  e2e/kots-release-install-stable/preflight.yaml
  e2e/kots-release-install/preflight.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/kots-release-upgrade/preflight.yaml
  e2e/playwright/tests/deploy-upgrade/test.spec.ts
  e2e/playwright/tests/shared/deploy-app.ts
  e2e/scripts/check-installation-state2.sh
  e2e/scripts/common.sh
  e2e/scripts/single-node-install2.sh
  pkg/addons2/addons.go
  pkg/addons2/adminconsole/install.go
  pkg/addons2/adminconsole/static/metadata.yaml
  pkg/addons2/highavailability.go
  pkg/addons2/openebs/install.go
  pkg/addons2/openebs/openebs.go
  pkg/addons2/openebs/static/metadata.yaml
  pkg/addons2/registry/install.go
  pkg/addons2/seaweedfs/install.go
  pkg/addons2/seaweedfs/static/metadata.yaml
  pkg/addons2/types/types.go
  pkg/addons2/velero/install.go
  pkg/addons2/velero/static/metadata.yaml
  pkg/extensions/extensions.go
  pkg/helm/client.go
Labels: type::feature

#1749 include postupgrade cluster state checking in install2 tests
  .github/workflows/ci.yaml
  e2e/install2_test.go
  e2e/scripts/check-postupgrade-state2.sh
  pkg/addons2/openebs/static/metadata.yaml
Labels: type::chore, run-failing-install2-tests

#1750 update addon2 image metadata when relevant
  pkg/release/addon.go
Labels: type::chore

#1752 feat: update velero version
  pkg/addons2/velero/static/metadata.yaml
Labels: type::chore, automated-pr

#1754 copy license file to data dir in install2 like install1
  cmd/installer/cli/install2.go
  e2e/scripts/single-node-install2.sh
Labels: type::chore

#1738 feat: update openebs version
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons2/openebs/static/metadata.yaml
Labels: type::chore, automated-pr

#1755 feat(v2): upgrades without manager
  kinds/apis/v1beta1/installation_types.go
  operator/controllers/installation_controller.go
  operator/pkg/cli/migrate_v2.go
  operator/pkg/cli/migrate_v2_installmanager.go
  operator/pkg/cli/migrate_v2_pod.go
  operator/pkg/cli/migrate_v2_pod_test.go
  operator/pkg/cli/migratev2/adminconsole.go
  operator/pkg/cli/migratev2/adminconsole_test.go
  operator/pkg/cli/migratev2/installation.go
  operator/pkg/cli/migratev2/installation_test.go
  operator/pkg/cli/migratev2/k0s.go
  operator/pkg/cli/migratev2/k0s_test.go
  operator/pkg/cli/migratev2/manager.go
  operator/pkg/cli/migratev2/manager_test.go
  operator/pkg/cli/migratev2/managerpod.go
  operator/pkg/cli/migratev2/migrate.go
  operator/pkg/cli/migratev2/operator.go
  operator/pkg/cli/migratev2/operator_test.go
  operator/pkg/cli/upgrade.go
  operator/pkg/cli/upgrade_job.go
  operator/pkg/upgrade/job.go
Labels: type::feature

#1751 chore: update seaweedfs images
  pkg/addons/seaweedfs/static/metadata.yaml
  pkg/addons2/seaweedfs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1758 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons2/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1759 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons2/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1756 install operator with no custom values in install2
  cmd/installer/cli/install2.go
  e2e/scripts/check-installation-state2.sh
  kinds/apis/v1beta1/installation_types.go
  operator/charts/crd.go
  pkg/addons2/addons.go
  pkg/addons2/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons2/embeddedclusteroperator/install.go
  pkg/addons2/embeddedclusteroperator/prepare.go
  pkg/addons2/embeddedclusteroperator/static/metadata.yaml
  pkg/addons2/embeddedclusteroperator/static/values.tpl.yaml
  pkg/kubeutils/kubeutils.go
  pkg/release/addon.go
Labels: type::chore

#1769 chore: update openebs images
  pkg/addons/openebs/static/metadata.yaml
  pkg/addons2/openebs/static/metadata.yaml
Labels: automated-pr, images, type::security

#1770 chore: update velero images
  pkg/addons/velero/static/metadata.yaml
  pkg/addons2/velero/static/metadata.yaml
Labels: automated-pr, images, type::security

#1764 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons2/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1772 move all installs to v2
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  operator/controllers/installation_controller.go
  pkg/helm/client.go
  pkg/helm/client_test.go
  pkg/kubeutils/kubeutils.go
Labels: type::chore

#1767 feat(v2): restore and run preflights commands
  .github/workflows/ci.yaml
  .github/workflows/image-scan.yaml
  .github/workflows/release-prod.yaml
  cmd/installer/cli/install.go
  cmd/installer/cli/install2.go
  cmd/installer/cli/install_runpreflights.go
  cmd/installer/cli/install_runpreflights_test.go
  cmd/installer/cli/install_test.go
  cmd/installer/cli/join2.go
  cmd/installer/cli/join_runpreflights.go
  cmd/installer/cli/reset.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/restore2.go
  cmd/installer/cli/root.go
  dagger.json
  dagger/go.mod
  dagger/go.sum
  e2e/install2_test.go
  e2e/restore_test.go
  operator/controllers/installation_controller.go
  pkg/addons2/addons.go
  pkg/addons2/embeddedclusteroperator/prepare.go
  pkg/dryrun/kubeutils.go
  pkg/highavailability/enable_test.go
  pkg/k0s/install.go
  pkg/kubeutils/kubeutils.go
  pkg/metrics/reporter.go
  pkg/runtimeconfig/defaults.go
Labels: type::feature

#1777 feat: update adminconsole version
  pkg/addons/adminconsole/static/metadata.yaml
  pkg/addons2/adminconsole/static/metadata.yaml
Labels: type::chore, automated-pr

#1775 run all v1 install tests in v2
  .github/workflows/ci.yaml
  e2e/kots-release-upgrade/cluster-config.yaml
  e2e/scripts/check-postupgrade-state.sh
  e2e/scripts/check-postupgrade-state2.sh
  e2e/scripts/common.sh
  operator/controllers/installation_controller.go
  pkg/addons2/embeddedclusteroperator/values.go
  pkg/extensions/upgrade.go
Labels: type::chore

#1778 chore: no spinner if no terminal
  pkg/spinner/spinner.go
  pkg/spinner/spinner_test.go
Labels: type::chore

#1776 feat(v2): enable v2 restore
  cmd/installer/cli/install2.go
  cmd/installer/cli/restore.go
  cmd/installer/cli/restore2.go
  e2e/scripts/resume-restore.exp
  operator/controllers/installation_controller.go
  operator/pkg/cli/upgrade.go
  operator/pkg/k8sutil/installation.go
  operator/pkg/upgrade/installation.go
  operator/pkg/upgrade/upgrade.go
  pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
  pkg/addons2/adminconsole/values.go
  pkg/addons2/highavailability.go
  pkg/dryrun/kubeutils.go
  pkg/extensions/install.go
  pkg/highavailability/enable.go
  pkg/kubeutils/interface.go
  pkg/kubeutils/kubeutils.go
Labels: type::feature

#1779 chore: remove dead code
  cmd/buildtools/embeddedclusteroperator.go
  e2e/cluster/docker/utils.go
  e2e/utils.go
  pkg/addons2/seaweedfs/types.go
Labels: type::chore

#1782 fix TestLocalArtifactMirror and TestCommandsRequireSudo
  cmd/installer/cli/install2.go
  cmd/installer/cli/metrics.go
  cmd/installer/cli/node.go
  e2e/local-artifact-mirror_test.go
  e2e/scripts/default-install.sh
  e2e/scripts/embedded-preflight.sh
  e2e/sudo_test.go
  operator/pkg/cli/migratev2/installation_test.go
  pkg/spinner/spinner.go
  pkg/spinner/spinner_test.go
Labels: type::chore

#1786 chore(ci): fix TestGetInstallation migrate data dirs
  pkg/kubeutils/kubeutils.go
Labels: type::chore

#1784 feat(v2): fix e2e TestVersion
  cmd/buildtools/metadata.go
  cmd/installer/cli/install2.go
  e2e/version_test.go
  operator/pkg/release/release_test.go
Labels: type::feature
